/* Listas planejadas para uso do professor em aula. */
(()=>{
'use strict';
const MM=window.MM=window.MM||{};
const text=value=>({type:'text',value});
const base={arquivo:'Lista trabalhada em aula — Dilatação térmica',origem_declarada:'Autoral — Matheus Moreira',dificuldade_declarada:'Progressiva',formato_declarado:'Múltipla escolha',verificacao:'Questão autoral revisada para a lista de aula',dependencia_visual:'Sem figura'};
const questions=[
 {id:'AULA-DIL-01',numero_no_arquivo:1,resumo:'Primeiro cálculo de dilatação linear',tema:'Dilatação linear',raciocinio:'Substituir diretamente em ΔL = L₀αΔT',tipo_de_pratica:'Cálculo direto',answer:'B',prompt:[text('Uma barra de alumínio tem comprimento inicial de 2,0 m. Seu coeficiente de dilatação linear é 12 × 10⁻⁶ °C⁻¹, e a temperatura aumenta 50 °C. Qual é o aumento do comprimento da barra?'),text('a) 0,12 mm'),text('b) 1,2 mm'),text('c) 12 mm'),text('d) 120 mm')],solution:[text('Use ΔL = L₀αΔT.'),text('ΔL = 2,0 × 12 × 10⁻⁶ × 50 = 1,2 × 10⁻³ m = 1,2 mm.')]},
 {id:'AULA-DIL-02',numero_no_arquivo:2,resumo:'Comprimento final de uma barra',tema:'Dilatação linear',raciocinio:'Calcular ΔT, encontrar ΔL e somar a L₀',tipo_de_pratica:'Cálculo em duas etapas',answer:'C',prompt:[text('Uma barra mede 1,500 m a 20 °C. O material tem α = 20 × 10⁻⁶ °C⁻¹. Qual será o comprimento da barra a 120 °C?'),text('a) 1,5003 m'),text('b) 1,5010 m'),text('c) 1,5030 m'),text('d) 1,5300 m')],solution:[text('Primeiro, ΔT = 120 − 20 = 100 °C.'),text('ΔL = 1,500 × 20 × 10⁻⁶ × 100 = 0,003 m. Logo, L = 1,500 + 0,003 = 1,503 m.')]},
 {id:'AULA-DIL-03',numero_no_arquivo:3,resumo:'Aumento do volume',tema:'Dilatação volumétrica',raciocinio:'Aplicar diretamente ΔV = V₀γΔT',tipo_de_pratica:'Cálculo direto',answer:'C',prompt:[text('Um recipiente rígido de demonstração tem volume inicial de 2,0 L. Considere γ = 60 × 10⁻⁶ °C⁻¹ e um aumento de temperatura de 100 °C. Qual é o aumento de volume previsto pelo modelo?'),text('a) 1,2 mL'),text('b) 6,0 mL'),text('c) 12 mL'),text('d) 120 mL')],solution:[text('ΔV = V₀γΔT = 2,0 × 60 × 10⁻⁶ × 100 L = 0,012 L.'),text('Como 0,012 L = 12 mL, o gabarito é C.')]},
 {id:'AULA-DIL-04',numero_no_arquivo:4,resumo:'De alfa para beta',tema:'Conversão de coeficientes',raciocinio:'Converter α em β antes de calcular a área',tipo_de_pratica:'Conversão e cálculo',answer:'B',prompt:[text('Uma placa tem área inicial de 0,80 m² e α = 15 × 10⁻⁶ °C⁻¹. Ela é aquecida em 80 °C. Qual é o aumento aproximado de sua área?'),text('a) 9,6 cm²'),text('b) 19,2 cm²'),text('c) 30,0 cm²'),text('d) 192 cm²')],solution:[text('Como a questão acompanha uma área, use β ≈ 2α = 30 × 10⁻⁶ °C⁻¹.'),text('ΔA = 0,80 × 30 × 10⁻⁶ × 80 = 0,00192 m² = 19,2 cm².')]},
 {id:'AULA-DIL-05',numero_no_arquivo:5,resumo:'De alfa para gama',tema:'Conversão de coeficientes',raciocinio:'Converter α em γ antes de calcular o volume',tipo_de_pratica:'Conversão e cálculo',answer:'D',prompt:[text('Um bloco isotrópico tem volume inicial de 500 cm³ e α = 18 × 10⁻⁶ °C⁻¹. Sua temperatura aumenta 100 °C. Qual é o aumento aproximado do volume?'),text('a) 0,9 cm³'),text('b) 1,8 cm³'),text('c) 2,0 cm³'),text('d) 2,7 cm³')],solution:[text('Para o volume, γ ≈ 3α = 54 × 10⁻⁶ °C⁻¹.'),text('ΔV = 500 × 54 × 10⁻⁶ × 100 = 2,7 cm³.')]},
 {id:'AULA-DIL-06',numero_no_arquivo:6,resumo:'De beta para gama',tema:'Conversão de coeficientes',raciocinio:'Recuperar α a partir de β e então obter γ',tipo_de_pratica:'Conversão em duas etapas',answer:'C',prompt:[text('Um material isotrópico tem β = 44 × 10⁻⁶ °C⁻¹. Um corpo desse material tem volume inicial de 1 200 cm³ e é aquecido em 50 °C. Qual é o aumento aproximado do volume?'),text('a) 1,32 cm³'),text('b) 2,64 cm³'),text('c) 3,96 cm³'),text('d) 7,92 cm³')],solution:[text('Se β ≈ 2α, então α = 22 × 10⁻⁶ °C⁻¹. Assim, γ ≈ 3α = 66 × 10⁻⁶ °C⁻¹.'),text('ΔV = 1 200 × 66 × 10⁻⁶ × 50 = 3,96 cm³.') ]},
 {id:'AULA-DIL-07',numero_no_arquivo:7,origem_declarada:'Unicamp',resumo:'Um material que encolhe ao aquecer',tema:'Gráfico e dilatação linear negativa',raciocinio:'Ler dois pontos do gráfico e calcular α',tipo_de_pratica:'Gráfico e cálculo',dependencia_visual:'Gráfico essencial',answer:'B',prompt:[text('Alguns materiais apresentam coeficiente de dilatação linear negativo: eles diminuem de comprimento quando a temperatura aumenta. O gráfico mostra o comprimento de uma barra entre 0 °C e 200 °C.'),{type:'image',src:'assets/questions/aula-dil-07-grafico-unicamp.png'},text('Considerando o intervalo de 0 °C a 50 °C, qual é aproximadamente o coeficiente de dilatação linear do material?'),text('a) −2,5 × 10⁻⁶ °C⁻¹'),text('b) −5,0 × 10⁻⁶ °C⁻¹'),text('c) 5,0 × 10⁻⁶ °C⁻¹'),text('d) 2,5 × 10⁻⁵ °C⁻¹')],solution:[text('Do gráfico: L₀ = 2,0000 mm e L = 1,9995 mm a 50 °C. Portanto, ΔL = −0,0005 mm.'),text('α = ΔL/(L₀ΔT) = −0,0005/(2,0000 × 50) = −5,0 × 10⁻⁶ °C⁻¹. O sinal negativo representa a contração durante o aquecimento.')]},
 {id:'AULA-DIL-08',numero_no_arquivo:8,origem_declarada:'ENEM PPL',resumo:'Qual material deve formar a porca?',tema:'Comparação de coeficientes',raciocinio:'Escolher menor α para o parafuso e maior α para a porca',tipo_de_pratica:'Tabela e interpretação',dependencia_visual:'Tirinha e tabela essenciais',answer:'C',prompt:[{type:'image',src:'assets/questions/aula-dil-08-tirinha-enem.png'},text('Para soltar o conjunto com o menor aquecimento possível, o parafuso deve dilatar pouco e a porca deve dilatar muito. Consulte a tabela e escolha os materiais, respectivamente, do parafuso e da porca.'),{type:'table',value:'materials'},text('a) aço e níquel'),text('b) alumínio e chumbo'),text('c) platina e chumbo'),text('d) ouro e latão'),text('e) cobre e bronze')],solution:[text('Procure o menor coeficiente para o parafuso e o maior para a porca.'),text('A platina tem α = 0,9 × 10⁻⁵ °C⁻¹, enquanto o chumbo tem α = 2,9 × 10⁻⁵ °C⁻¹. Por isso, a alternativa correta é C.')]},
 {id:'AULA-DIL-09',numero_no_arquivo:9,origem_declarada:'PUCRS',resumo:'Coeficiente obtido pelo gráfico',tema:'Gráfico de comprimento e temperatura',raciocinio:'Extrair L₀, ΔL e ΔT do gráfico',tipo_de_pratica:'Gráfico e cálculo',dependencia_visual:'Gráfico essencial',answer:'E',prompt:[text('Um grupo mediu o comprimento de uma barra metálica enquanto sua temperatura aumentava e construiu o gráfico.'),{type:'image',src:'assets/questions/aula-dil-09-grafico-pucrs.png'},text('Qual é o coeficiente de dilatação linear da barra?'),text('a) 1,05 × 10⁻⁵ °C⁻¹'),text('b) 1,14 × 10⁻⁵ °C⁻¹'),text('c) 1,18 × 10⁻⁵ °C⁻¹'),text('d) 1,22 × 10⁻⁵ °C⁻¹'),text('e) 1,25 × 10⁻⁵ °C⁻¹')],solution:[text('Pelo gráfico, L₀ = 800 mm, ΔL = 1 mm e ΔT = 110 − 10 = 100 °C.'),text('α = 1/(800 × 100) = 1,25 × 10⁻⁵ °C⁻¹.')]},
 {id:'AULA-DIL-10',numero_no_arquivo:10,origem_declarada:'CPS',resumo:'Por que os cabos fazem barriga?',tema:'Contração térmica',raciocinio:'Relacionar a folga dos cabos à contração em dias frios',tipo_de_pratica:'Interpretação conceitual',dependencia_visual:'Figura contextual',answer:'D',prompt:[text('Nas linhas de transmissão, os cabos são instalados arqueados, formando uma “barriga”, como mostra a figura.'),{type:'image',src:'assets/questions/aula-dil-10-cabos-cps.png'},text('A razão dessa disposição é que'),text('a) a densidade dos cabos tende a diminuir com o passar dos anos.'),text('b) a condução da eletricidade em alta tensão é facilitada desse modo.'),text('c) o metal usado nos cabos não pode ser esticado.'),text('d) os cabos podem se contrair nos dias frios sem derrubar as torres.'),text('e) os cabos arqueados não balançam quando há ventos fortes.')],solution:[text('Quando a temperatura diminui, o metal sofre contração térmica.'),text('A folga permite que o comprimento diminua sem produzir uma tração tão grande a ponto de danificar os cabos ou as torres. Por isso, a alternativa correta é D.')]}
].map(q=>({...base,...q}));
MM.originalQuestions=MM.originalQuestions||[];
questions.forEach(q=>{if(!MM.originalQuestions.some(item=>item.id===q.id))MM.originalQuestions.push(q)});
MM.classLists=MM.classLists||[];
MM.classLists.push({id:'aula-dilatacao-01',title:'Trabalhadas na aula — Dilatação térmica',description:'Dez questões em progressão: aplicação direta, conversão de coeficientes, tabela e leitura de gráficos.',chapter:'dilatacao',questionIds:questions.map(q=>q.id),pendingSlots:0});
const lesson=(MM.lessons||[]).find(item=>item.id==='dilatacao');
if(lesson?.slides?.length){const last=lesson.slides.at(-1);if(!last.html.includes('data-class-list-link'))last.html+=`<aside class="chapter-exercise-cta"><p class="eyebrow">Próximo passo</p><h2>Leve este capítulo para a lousa</h2><p>A lista começa com aplicações diretas, passa pelas conversões entre α, β e γ e termina com tabela e gráficos.</p><a class="primary" href="#exercicios" data-class-list-link="aula-dilatacao-01">Abrir as dez questões da aula</a></aside>`;}
document.addEventListener('click',event=>{const link=event.target.closest('[data-class-list-link]');if(link)sessionStorage.setItem('mm-pending-class-list',link.dataset.classListLink)});
})();
