/* Aula de Linguagens: conectivos e relações de sentido. */
(()=>{'use strict';
const MM=window.MM;
const p=s=>`<p>${s}</p>`;
const note=s=>`<div class="callout"><strong class="summary-label">Ou seja</strong><p>${s}</p></div>`;
const sec=(title,body)=>`<section class="deep-section"><h2>${title}</h2>${body}</section>`;
const lab=()=>`<div class="lab connective-lab" data-connective-explorer><div class="lab-head"><span>Leia as relações entre as ideias</span><span>Explore</span></div><div class="connective-workspace"><article class="connective-text"><p>O racismo estrutural não aparece apenas em atitudes individuais. <button data-connective="além disso">Além disso</button>, ele pode ser percebido em desigualdades que se repetem no acesso à educação, à renda e à segurança. <button data-connective="por exemplo">Por exemplo</button>, quando grupos enfrentam obstáculos semelhantes por muitas gerações, o problema não pode ser explicado somente por escolhas pessoais. <button data-connective="portanto">Portanto</button>, enfrentar o racismo exige rever comportamentos e também as estruturas que mantêm essas desigualdades.</p></article><aside class="connective-explanation" aria-live="polite"><span>Escolha um conectivo</span><h3>Qual relação ele cria?</h3><p>Passe o mouse, toque ou use o teclado em uma palavra destacada.</p></aside></div><div class="observation-bar"><span>Observação interativa</span></div></div>`;
const slides=[
 {label:'Para que servem',title:'Conectivos: ideias que <em>conversam entre si.</em>',subtitle:'Uma palavra pequena pode mudar o caminho do argumento.',html:`<div class="lesson-flow">${p('Conectivos mostram ao leitor como uma ideia se liga à seguinte. Eles podem acrescentar, explicar, comparar, contrariar, indicar causa ou fechar uma conclusão.')}${note('o conectivo não enfeita a frase. Ele anuncia a relação de sentido que o leitor deve construir.')}${lab()}</div>`},
 {label:'Adição',title:'Somar sem apenas <em>repetir.</em>',subtitle:'Além disso, também, ainda e bem como.',html:`<div class="lesson-flow">${sec('O que a adição faz',p('Ela acrescenta um argumento que ajuda a sustentar a mesma direção de raciocínio. O novo trecho precisa trazer informação, exemplo ou consequência; repetir a frase anterior não fortalece o texto.'))}${note('use “além disso” quando a segunda ideia amplia a primeira.')}${lab()}</div>`},
 {label:'Explicação e exemplo',title:'Tornar a ideia <em>visível.</em>',subtitle:'Por exemplo, isto é, ou seja e em outras palavras.',html:`<div class="lesson-flow">${sec('Duas funções próximas',p('“Por exemplo” apresenta um caso concreto. “Isto é” e “ou seja” reformulam ou esclarecem o que acabou de ser dito. Escolher entre eles depende do que o próximo trecho realmente faz.'))}${note('um exemplo mostra um caso; uma reformulação diz novamente com mais clareza.')}${lab()}</div>`},
 {label:'Contraste',title:'Mudar a direção do <em>raciocínio.</em>',subtitle:'Mas, porém, contudo e embora.',html:`<div class="lesson-flow">${sec('O leitor precisa sentir a virada',p('Conectivos de oposição avisam que a próxima ideia limita, corrige ou contrasta com a anterior. “Embora” costuma introduzir uma concessão: algo é reconhecido, mas não impede a conclusão principal.'))}${note('use oposição quando existe uma tensão real entre as ideias.')}${lab()}</div>`},
 {label:'Causa e consequência',title:'O que explica? <em>O que resulta?</em>',subtitle:'Porque, já que, por isso e desse modo.',html:`<div class="lesson-flow">${sec('Não troque a ordem sem perceber',p('“Porque” e “já que” apresentam uma causa ou justificativa. “Por isso” e “desse modo” introduzem uma consequência. Ler a frase como pergunta ajuda: por quê? ou o que aconteceu por causa disso?'))}${note('causa olha para a razão; consequência olha para o resultado.')}${lab()}</div>`},
 {label:'Conclusão',title:'Fechar o caminho sem <em>dar um salto.</em>',subtitle:'Portanto, assim, logo e em síntese.',html:`<div class="lesson-flow">${sec('Conclusão precisa ser construída',p('“Portanto” avisa que o texto chegou a uma conclusão apoiada nas ideias anteriores. No exemplo, ele encerra a análise do racismo estrutural e apresenta a ação que decorre dessa análise.'))}${note('“portanto” não cria a conclusão sozinho; ele mostra que a conclusão vem do que já foi defendido.')}${lab()}</div>`},
 {label:'Síntese',title:'Escolha pela <em>relação de sentido.</em>',subtitle:'Primeiro entenda o vínculo; depois escolha a palavra.',html:`<div class="summary-grid"><article><h3>Some</h3><p>além disso · também</p></article><article><h3>Mostre</h3><p>por exemplo · ou seja</p></article><article><h3>Conclua</h3><p>portanto · assim</p></article></div>${note('um bom conectivo permite que o leitor antecipe a função da próxima ideia.')}<div class="next-study"><a class="primary" href="#estudos">Voltar aos estudos</a></div>`}
];
MM.lessons.push({id:'conectivos',area:'Linguagens',title:'Conectivos e relações de sentido',desc:'Como ligar ideias, orientar o leitor e construir um argumento claro.',symbol:'ideia → relação → ideia',time:'35–50 min',slides});
MM.chapterModes.conectivos={modes:['professor','aluno','autodidata']};
MM.initConnectiveExplorer=root=>root.querySelectorAll('[data-connective-explorer]').forEach(host=>{
 const info={
  'além disso':['Adição','Acrescenta outra evidência na mesma direção: o problema também aparece em desigualdades repetidas.'],
  'por exemplo':['Exemplificação','Transforma uma afirmação geral em uma situação concreta que o leitor consegue examinar.'],
  'portanto':['Conclusão','Fecha o raciocínio: depois de mostrar que o problema é individual e estrutural, o texto conclui que a resposta precisa atuar nos dois níveis.']
 };
 const box=host.querySelector('.connective-explanation');
 const show=button=>{const [title,text]=info[button.dataset.connective];host.querySelectorAll('[data-connective]').forEach(x=>x.classList.toggle('is-active',x===button));box.innerHTML=`<span>${button.dataset.connective}</span><h3>${title}</h3><p>${text}</p>`;};
 host.querySelectorAll('[data-connective]').forEach(button=>{button.addEventListener('mouseenter',()=>show(button));button.addEventListener('focus',()=>show(button));button.addEventListener('click',()=>show(button));});
 });

/* Provocação enviada pelo professor para abrir Dilatação Térmica. */
const thermal=MM.lessons.find(lesson=>lesson.id==='dilatacao');
if(thermal?.slides?.[0]){
 const provocation=`<section class="thermal-provocation"><div class="provocation-copy"><p class="eyebrow">Provocação inicial</p><h2>Você está em casa num domingo e vê o piso levantar. O que faz?</h2><div class="sunday-reaction">SENHOR!</div><p>Antes de explicar, observe os dois registros e formule uma hipótese: o que pode acontecer quando as peças tentam se expandir, mas quase não encontram espaço para isso?</p><aside><strong>Investigue antes de concluir</strong><p>Folgas insuficientes e variações térmicas podem gerar esforços e contribuir para o levantamento. Em situações reais, instalação, aderência, umidade e condições da base também precisam ser verificadas.</p></aside></div><div class="provocation-videos"><iframe src="https://www.youtube-nocookie.com/embed/SJqHLkuvgWU" title="Registro de piso levantando" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><iframe src="https://www.youtube-nocookie.com/embed/RNST_35Svqg" title="Segundo registro de piso estourando" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div></section>`;
 thermal.slides[0].html=provocation+thermal.slides[0].html;
}
})();
