/* Aula de Linguagens: conectivos e relações de sentido. */
(()=>{'use strict';
const MM=window.MM;
const p=s=>`<p>${s}</p>`;
const note=s=>`<aside class="connective-takeaway"><span>O que fica</span><p>${s}</p></aside>`;
const relationLab=()=>`<section class="connective-lab relation-reader" data-connective-explorer><header><span>Leia o parágrafo</span><strong>Passe pelos conectivos</strong></header><div class="connective-workspace"><article class="connective-text"><p>O racismo estrutural não aparece apenas em atitudes individuais. <button data-connective="além disso">Além disso</button>, ele pode ser percebido em desigualdades que se repetem no acesso à educação, à renda e à segurança. <button data-connective="por exemplo">Por exemplo</button>, quando grupos enfrentam obstáculos semelhantes por muitas gerações, o problema não pode ser explicado somente por escolhas pessoais. <button data-connective="portanto">Portanto</button>, enfrentar o racismo exige rever comportamentos e também as estruturas que mantêm essas desigualdades.</p></article><aside class="connective-explanation" aria-live="polite"><span>Escolha uma passagem</span><h3>Que trabalho essa palavra faz?</h3><p>Passe o mouse, toque ou use o teclado.</p></aside></div></section>`;
const choiceLab=(title,stem,choices)=>`<section class="connector-choice" data-connector-choice><p class="eyebrow">Teste de leitura</p><h2>${title}</h2><p class="choice-stem">${stem}</p><div class="choice-words">${choices.map(c=>`<button data-message="${c[1]}">${c[0]}</button>`).join('')}</div><p class="choice-response" aria-live="polite">Escolha uma palavra e observe como ela muda a expectativa do leitor.</p></section>`;
const slides=[
 {label:'Sentido antes do nome',title:'A palavra muda. <em>O raciocínio também.</em>',subtitle:'Comece lendo o efeito, sem decorar uma lista.',html:`<div class="language-lesson">${p('Compare duas continuações para a mesma ideia. Nenhuma palavra é neutra: cada uma prepara o leitor para um caminho.')}${choiceLab('O que a segunda frase fará?','A escola ampliou o acesso aos livros. ___, muitos estudantes ainda encontram dificuldade para ler em casa.',[['Além disso','“Além disso” promete outra informação na mesma direção. Aqui ele apaga a tensão entre avanço e dificuldade.'],['Porém','“Porém” avisa que vem um limite ou contraste. É a relação mais coerente neste contexto.'],['Portanto','“Portanto” apresentaria a dificuldade como conclusão do aumento do acesso, o que não foi demonstrado.']])}${note('antes de escolher o conectivo, pergunte: a próxima ideia soma, explica, contrasta, causa ou conclui?')}</div>`},
 {label:'Leitura em movimento',title:'Veja as costuras <em>do parágrafo.</em>',subtitle:'O conectivo orienta a passagem de uma ideia à outra.',html:`<div class="language-lesson">${p('Agora leia um parágrafo inteiro. Os conectivos destacados não são etiquetas soltas: cada um responde ao trecho anterior e prepara o próximo.')}${relationLab()}${note('o sentido nasce da relação entre os trechos. A mesma palavra pode soar correta numa frase e inadequada em outra.')}</div>`},
 {label:'Somar, mostrar, explicar',title:'Nem todo acréscimo faz <em>o mesmo trabalho.</em>',subtitle:'Adicionar, exemplificar e reformular são movimentos diferentes.',html:`<div class="language-lesson"><div class="relation-columns"><article><span>Somar</span><h2>Além disso</h2><p>Acrescenta outro argumento na mesma direção.</p></article><article><span>Mostrar</span><h2>Por exemplo</h2><p>Apresenta um caso que torna a afirmação concreta.</p></article><article><span>Explicar de novo</span><h2>Ou seja</h2><p>Reformula a ideia para deixá-la mais clara.</p></article></div>${choiceLab('Qual passagem vem agora?','A evasão escolar tem causas econômicas. ___, alguns jovens deixam a escola para ajudar na renda da família.',[['Ou seja','A segunda frase não repete toda a primeira; ela apresenta uma situação específica.'],['Por exemplo','A segunda frase funciona como um caso concreto da afirmação geral.'],['Além disso','A frase não oferece um novo argumento independente; ela mostra um caso do que já foi dito.']])}${note('exemplo mostra um caso; reformulação diz novamente; adição traz outro ponto.')}</div>`},
 {label:'Virada e concessão',title:'Discordar, limitar e reconhecer <em>não são iguais.</em>',subtitle:'Mas, porém e embora criam tensões diferentes.',html:`<div class="language-lesson">${p('“Mas” e “porém” costumam marcar oposição. “Embora” reconhece um fato e o coloca como insuficiente para impedir a ideia principal.')}${choiceLab('Onde está a ideia principal?','Embora a internet amplie o acesso à informação, ela não garante que todas as fontes sejam confiáveis.',[['No acesso ampliado','Esse fato é reconhecido, mas fica em segundo plano por causa de “embora”.'],['Na falta de garantia','Esta é a afirmação principal; a concessão apenas prepara o contraste.'],['Nas duas igualmente','A construção cria uma hierarquia: uma ideia é concedida e a outra é defendida.']])}${note('“embora” não é apenas um sinônimo elegante de “mas”: ele muda a organização e o peso das ideias.')}</div>`},
 {label:'Causa ou resultado',title:'Não confunda o motivo <em>com a consequência.</em>',subtitle:'A ordem das ideias decide a palavra.',html:`<div class="language-lesson"><div class="cause-chain"><span>Chuvas intensas</span><b>→</b><span>alagamentos</span><b>→</b><span>aulas suspensas</span></div>${choiceLab('Complete pelo ponto de vista pedido','As aulas foram suspensas ___ várias ruas ficaram alagadas.',[['porque','“Porque” introduz a razão da suspensão.'],['por isso','“Por isso” exigiria que o alagamento viesse primeiro: “As ruas alagaram; por isso...”'],['contudo','Não há oposição entre as duas informações.']])}${note('“porque” aponta para a razão; “por isso” parte da razão e anuncia o resultado.')}</div>`},
 {label:'Oficina do parágrafo',title:'Escolha pelo contexto. <em>Depois releia o todo.</em>',subtitle:'Um parágrafo coerente distribui funções, não palavras bonitas.',html:`<div class="language-lesson"><section class="paragraph-workshop" data-paragraph-workshop><p>A biblioteca passou a abrir aos sábados. <label><span class="sr-only">Primeiro conectivo</span><select data-answer="além disso"><option value="">escolha</option><option>além disso</option><option>porém</option><option>portanto</option></select></label>, criou rodas de leitura conduzidas pelos estudantes. <label><span class="sr-only">Segundo conectivo</span><select data-answer="por exemplo"><option value="">escolha</option><option>por exemplo</option><option>contudo</option><option>logo</option></select></label>, uma turma passou a discutir contos de autores locais. A participação cresceu; <label><span class="sr-only">Terceiro conectivo</span><select data-answer="portanto"><option value="">escolha</option><option>embora</option><option>portanto</option><option>porque</option></select></label>, o projeto será mantido no próximo semestre.</p><button class="primary" data-check-paragraph>Conferir relações</button><div data-paragraph-feedback aria-live="polite"></div></section>${note('depois de preencher, leia o parágrafo inteiro: coerência não se confere palavra por palavra.')}</div>`},
 {label:'Escrita com intenção',title:'Agora você decide <em>o caminho do leitor.</em>',subtitle:'Escreva quatro frases ligadas por três relações diferentes.',html:`<div class="language-lesson"><section class="writing-studio" data-writing-studio><div><p class="eyebrow">Proposta de escrita</p><h2>O uso do celular durante a aula</h2><ol><li>Apresente uma posição.</li><li>Acrescente uma razão.</li><li>Reconheça um limite ou contraponto.</li><li>Chegue a uma conclusão possível.</li></ol></div><div><textarea rows="9" placeholder="Escreva seu parágrafo aqui..."></textarea><p class="writing-status" aria-live="polite">0 palavras · nenhuma relação marcada ainda</p></div></section>${note('o conectivo vem depois da intenção: primeiro decida o que a próxima frase fará.')}</div>`},
 {label:'Síntese',title:'Conectivo é uma <em>decisão de sentido.</em>',subtitle:'Leia a relação, escolha a palavra e confira o efeito.',html:`<div class="language-lesson"><div class="connective-map"><article><span>1</span><h3>Leia os dois trechos</h3><p>O vínculo já existe ou precisa ser construído?</p></article><article><span>2</span><h3>Dê nome ao movimento</h3><p>Soma, exemplo, explicação, contraste, causa, resultado ou conclusão?</p></article><article><span>3</span><h3>Escolha e releia</h3><p>A palavra promete exatamente o que a frase seguinte entrega?</p></article></div>${note('um bom conectivo não chama atenção para si; ele ajuda o leitor a não se perder.')}<div class="next-study"><a class="primary" href="#estudos">Voltar aos estudos</a></div></div>`}
];
MM.lessons.push({id:'conectivos',area:'Linguagens',title:'Conectivos e relações de sentido',desc:'Como ligar ideias, orientar o leitor e construir um argumento claro.',symbol:'ideia → relação → ideia',time:'35–50 min',slides});
MM.chapterModes.conectivos={modes:['professor','aluno','autodidata']};
/* Entradas do banco: no estudo individual elas abrem as oficinas interativas;
   na apresentação servem como roteiro de discussão e resolução coletiva. */
const exerciseText=value=>({type:'text',value});
const connectiveQuestions=[
 {id:'CON-01',numero_no_arquivo:1,resumo:'Complete o caminho do argumento',tema:'Progressão de ideias',raciocinio:'Ler antes e depois da lacuna',tipo_de_pratica:'Preenchimento contextual',prompt:[exerciseText('Complete três passagens de um parágrafo. Em cada lacuna, explique se a próxima ideia acrescenta informação, apresenta um exemplo ou mostra uma consequência.')],solution:[exerciseText('A primeira relação é de adição; a segunda introduz um caso concreto; a terceira parte do resultado observado para uma decisão. O caminho possível é: “além disso”, “por exemplo” e “por isso”.')]},
 {id:'CON-02',numero_no_arquivo:2,resumo:'Compare efeitos na mesma fala',tema:'Efeito de sentido',raciocinio:'Trocar o conectivo e comparar a expectativa',tipo_de_pratica:'Comparação de versões',prompt:[exerciseText('Leia: “Eu entendo seu ponto, ___ ainda discordo da conclusão.” Compare o efeito produzido por “mas”, “e”, “portanto” e “embora”. A frase pode precisar ser reorganizada quando a palavra muda.')],solution:[exerciseText('“Mas” anuncia oposição direta. “E” promete uma simples soma e enfraquece a virada. “Portanto” apresenta uma conclusão que ainda não foi sustentada. “Embora” pode funcionar, mas exige outra estrutura: “Embora eu entenda seu ponto, ainda discordo da conclusão”.')]},
 {id:'CON-03',numero_no_arquivo:3,resumo:'Caça aos conectivos incoerentes',tema:'Coerência textual',raciocinio:'Conferir se a promessa do conectivo é cumprida',tipo_de_pratica:'Investigação em redação',prompt:[exerciseText('Em uma pequena redação sobre coleta seletiva, localize três conectivos que prometem uma relação diferente daquela realizada pela frase seguinte. Justifique cada suspeita e proponha uma substituição.')],solution:[exerciseText('A análise precisa relacionar cada palavra às duas ideias que ela une. Um conectivo de conclusão não pode introduzir contraste; um marcador de exemplo precisa apresentar um caso da afirmação anterior; um conector causal precisa introduzir uma causa real.')]},
 {id:'CON-04',numero_no_arquivo:4,resumo:'Organize o parágrafo pelas pistas',tema:'Organização do parágrafo',raciocinio:'Usar conectivos para reconstruir a sequência',tipo_de_pratica:'Ordenação',prompt:[exerciseText('Organize quatro frases sobre leitura. Use as pistas: a afirmação geral abre o texto; “por exemplo” depende dela; “no entanto” apresenta um limite; “portanto” fecha o raciocínio.')],solution:[exerciseText('A sequência coerente é: afirmação geral sobre a leitura, exemplo dos romances, limite sobre apenas disponibilizar livros e conclusão sobre investimento e acompanhamento.')]},
 {id:'CON-05',numero_no_arquivo:5,resumo:'Inverta causa e consequência',tema:'Causa e consequência',raciocinio:'Mudar a ordem e adequar o conectivo',tipo_de_pratica:'Transformação',prompt:[exerciseText('Relacione o alagamento das ruas à suspensão das aulas. Escreva primeiro começando pela causa e depois começando pelo resultado. Observe por que o conectivo precisa mudar.')],solution:[exerciseText('Da causa para o resultado: “As ruas ficaram alagadas; por isso, as aulas foram suspensas”. Do resultado para a causa: “As aulas foram suspensas porque as ruas ficaram alagadas”.')]},
 {id:'CON-06',numero_no_arquivo:6,resumo:'Reescreva um texto que usa “e” para tudo',tema:'Revisão autoral',raciocinio:'Identificar relações escondidas pela repetição',tipo_de_pratica:'Reescrita',prompt:[exerciseText('Reescreva um parágrafo sobre uma horta escolar que liga todas as informações com “e”. Torne visíveis pelo menos três relações entre as ideias, sem procurar uma variedade artificial de palavras.')],solution:[exerciseText('Uma versão possível usa “além disso” para somar a participação, “porém” para contrastar a falta de experiência com a aprendizagem e “portanto” para concluir pela continuidade do projeto. Outras escolhas são válidas quando preservam essas relações.')]}
].map(q=>({arquivo:'Laboratório de Conectivos',origem_declarada:'Autoral — Matheus Moreira',dificuldade_declarada:'Progressiva',formato_declarado:'Oficina interativa',verificacao:'Atividade autoral revisada',dependencia_visual:'Interação no site',solutionEditorial:true,answer:'',...q}));
MM.originalQuestions=MM.originalQuestions||[];
connectiveQuestions.forEach(q=>{if(!MM.originalQuestions.some(item=>item.id===q.id))MM.originalQuestions.push(q)});
MM.connectiveModeNotes=[
 ['Perceber que trocar o conectivo altera a expectativa criada para a segunda frase.','Leia as três versões em voz alta e peça que a turma explique o efeito antes de nomear a categoria.','Registre: relação pretendida → conectivo possível.'],
 ['Ler conectivos dentro de um parágrafo completo.','Peça que os estudantes antecipem o próximo movimento antes de passar sobre cada palavra.','Desenhe setas entre os trechos e escreva a função sobre cada seta.'],
 ['Distinguir adição, exemplo e reformulação.','Troque um conectivo por outro e pergunte o que o leitor passa a esperar.','Monte três colunas: soma, caso concreto, explicação de novo.'],
 ['Reconhecer oposição e concessão, observando qual ideia ganha destaque.','Compare “mas” e “embora” sem tratá-los como equivalentes automáticos.','Sublinhe a ideia reconhecida e circule a ideia principal.'],
 ['Diferenciar causa e consequência pela ordem lógica.','Faça a turma inverter as frases e escolher novamente o conectivo.','Use uma cadeia de acontecimentos e setas.'],
 ['Revisar a coerência do parágrafo inteiro.','Não confira apenas as lacunas: leia o texto completo depois de cada escolha.','Marque A de adição, E de exemplo e C de conclusão.'],
 ['Usar conectivos a serviço de uma posição autoral.','Acompanhe a intenção de cada frase e evite impor uma lista obrigatória de palavras.','Esboce quatro linhas: posição, razão, limite, conclusão.'],
 ['Construir um procedimento de revisão textual.','Peça exemplos em que uma palavra gramaticalmente correta produz uma relação inadequada.','Feche com três verbos: ler, nomear, reler.']
];
MM.connectiveDetailedExplanations=[
 `<section class="language-explanation"><p class="eyebrow">Entenda passo a passo</p><h2>O conectivo não é um enfeite entre duas frases</h2><p>Primeiro existe uma relação de sentido. Uma ideia pode acrescentar informação à anterior, contrariá-la, explicar sua causa ou apresentar uma conclusão. O conectivo torna essa relação visível para quem lê.</p><div class="language-explanation-grid"><article><strong>1. Leia a primeira ideia</strong><p>Descubra o que ela afirma sem pensar ainda numa lista de palavras.</p></article><article><strong>2. Observe a continuação</strong><p>Pergunte se ela segue na mesma direção ou muda o rumo do raciocínio.</p></article><article><strong>3. Só então escolha</strong><p>Use a palavra que anuncia exatamente o movimento feito pela segunda ideia.</p></article></div><aside class="language-common-trap"><strong>Armadilha comum</strong><p>Uma frase pode estar correta na gramática e continuar incoerente no sentido. “Portanto” cabe na estrutura, mas fica errado se a segunda ideia não for consequência da primeira.</p></aside></section>`,
 `<section class="language-explanation"><p class="eyebrow">Leia a costura</p><h2>Cada conectivo olha para trás e aponta para a frente</h2><p>Quando encontramos “por exemplo”, procuramos no trecho anterior uma afirmação mais geral. Ao mesmo tempo, esperamos que o próximo trecho mostre um caso concreto. É esse trabalho duplo que ajuda o leitor a atravessar o parágrafo sem se perder.</p><p>Por isso, não basta sublinhar uma palavra isolada. Leia a frase anterior, diga o que o conectivo promete e confira se a frase seguinte cumpre essa promessa.</p><aside class="language-common-trap"><strong>Armadilha comum</strong><p>Classificar “portanto” como conclusão sem identificar o raciocínio concluído transforma a análise em decoração gramatical. Sempre mostre de quais ideias a conclusão nasceu.</p></aside></section>`,
 `<section class="language-explanation"><p class="eyebrow">Três movimentos próximos</p><h2>Somar, exemplificar e reformular não fazem a mesma coisa</h2><p><strong>Somar</strong> traz outro argumento: “A biblioteca ampliou o horário. Além disso, comprou livros novos.” <strong>Exemplificar</strong> aproxima uma ideia geral da realidade: “Há novas atividades. Por exemplo, agora existe um clube de leitura.” <strong>Reformular</strong> explica novamente: “O acesso foi ampliado, ou seja, mais pessoas podem usar o espaço.”</p><p>Para decidir, tente retirar a segunda frase. Se ela é mais um motivo, há adição. Se é um caso da primeira, há exemplo. Se diz quase a mesma coisa de outro jeito, há reformulação.</p></section>`,
 `<section class="language-explanation"><p class="eyebrow">Peso das ideias</p><h2>Oposição e concessão organizam o destaque</h2><p>“Mas” e “porém” criam uma virada direta. Em “A proposta é útil, mas custa caro”, o leitor chega à segunda ideia sentindo uma mudança de direção. “Embora” funciona de outro modo: reconhece uma informação e prepara a ideia que o autor quer sustentar.</p><p>Compare: “A internet amplia o acesso, mas não garante fontes confiáveis” e “Embora a internet amplie o acesso, ela não garante fontes confiáveis”. A segunda construção coloca a ampliação como fato reconhecido e concentra o peso argumentativo na falta de garantia.</p><aside class="language-common-trap"><strong>A pontuação também participa</strong><p>Quando a oração iniciada por “embora” vem primeiro, a vírgula ajuda a separar a informação concedida da afirmação principal.</p></aside></section>`,
 `<section class="language-explanation"><p class="eyebrow">Siga a seta do raciocínio</p><h2>Causa explica de onde veio; consequência mostra o que aconteceu depois</h2><p>Em “As aulas foram suspensas porque as ruas alagaram”, começamos pelo resultado e voltamos ao motivo. Em “As ruas alagaram; por isso, as aulas foram suspensas”, começamos pelo motivo e avançamos para o resultado.</p><p>O acontecimento físico pode ser o mesmo, mas o caminho da frase muda. Antes de completar uma lacuna, desenhe mentalmente uma seta: <strong>motivo → consequência</strong>. Depois veja em qual lado da seta está a parte que falta.</p></section>`,
 `<section class="language-explanation"><p class="eyebrow">Coerência do conjunto</p><h2>Uma escolha local precisa funcionar no parágrafo inteiro</h2><p>Cada lacuna pede uma relação específica, mas o trabalho não termina quando as três palavras parecem corretas. Releia desde o início e observe a progressão: o texto apresenta uma ação, acrescenta outra, mostra um caso e chega a uma decisão.</p><p>Essa releitura permite notar repetições, saltos de assunto e conclusões apressadas. Um conectivo não conserta sozinho duas ideias que não possuem relação lógica.</p></section>`,
 `<section class="language-explanation"><p class="eyebrow">Escrever é conduzir</p><h2>Decida a intenção antes de procurar a palavra</h2><p>Ao começar uma nova frase, pergunte o que ela precisa fazer pelo argumento. Ela dará outra razão? Reconhecerá um limite? Mostrará um exemplo? Tirará uma conclusão possível? Com a intenção definida, a escolha do conectivo deixa de ser um chute.</p><p>Também não é necessário usar uma palavra diferente em cada linha só para parecer sofisticado. Clareza vale mais que variedade forçada. Se duas frases já se ligam bem sem conectivo, não acrescente um apenas para preencher espaço.</p><aside class="language-common-trap"><strong>Revisão útil</strong><p>Leia em voz alta. Se a palavra promete uma virada e a frase continua na mesma direção, ou promete conclusão sem haver raciocínio anterior, revise a relação.</p></aside></section>`,
 `<section class="language-explanation"><p class="eyebrow">Procedimento de revisão</p><h2>Quatro perguntas para qualquer texto</h2><div class="language-explanation-grid"><article><strong>O que foi dito?</strong><p>Resuma cada trecho com poucas palavras.</p></article><article><strong>Qual é a relação?</strong><p>Nomeie o movimento: soma, exemplo, contraste, causa, resultado ou conclusão.</p></article><article><strong>A palavra cumpre isso?</strong><p>Confira a expectativa criada pelo conectivo.</p></article><article><strong>O todo ficou claro?</strong><p>Releia o parágrafo e veja se o argumento avança sem saltos.</p></article></div><p>Esse procedimento serve tanto para interpretar um texto pronto quanto para revisar a própria redação. O objetivo final não é decorar uma tabela: é perceber como uma escolha pequena muda o caminho do leitor.</p></section>`
];
MM.renderConnectiveModeBody=(lesson,index,mode,html)=>{const [goal,focus,board]=MM.connectiveModeNotes[index],content=html+(MM.connectiveDetailedExplanations[index]||'');if(mode==='professor')return `<div class="language-teacher-stage"><section class="classroom-preview">${content}</section><aside class="language-teacher-guide"><p class="pedagogy-label">Apoio para condução</p><h2>Intenção da etapa</h2><p>${goal}</p><h2>Como mediar</h2><p>${focus}</p><h2>Registro possível</h2><p>${board}</p></aside></div>`;if(mode==='aluno')return `<div class="language-workshop">${content}</div>`;return `<div class="language-workshop">${content}<details class="language-self-check"><summary>Como conferir meu raciocínio</summary><p>${goal}</p><p>Explique com suas palavras qual relação você quis criar antes de conferir o nome do conectivo.</p></details></div>`;};
MM.initConnectiveExplorer=root=>root.querySelectorAll('[data-connective-explorer]').forEach(host=>{
 const info={
  'além disso':['Adição','Acrescenta outra evidência na mesma direção: o problema também aparece em desigualdades repetidas.'],
  'por exemplo':['Exemplificação','Transforma uma afirmação geral em uma situação concreta que o leitor consegue examinar.'],
  'portanto':['Conclusão','Fecha o raciocínio: depois de mostrar que o problema é individual e estrutural, o texto conclui que a resposta precisa atuar nos dois níveis.']
 };
 const box=host.querySelector('.connective-explanation');
 const show=button=>{const [title,text]=info[button.dataset.connective];host.querySelectorAll('[data-connective]').forEach(x=>x.classList.toggle('is-active',x===button));box.innerHTML=`<span>${button.dataset.connective}</span><h3>${title}</h3><p>${text}</p>`;};
 host.querySelectorAll('[data-connective]').forEach(button=>{button.addEventListener('mouseenter',()=>show(button));button.addEventListener('focus',()=>show(button));button.addEventListener('click',()=>show(button));});
 });
MM.initConnectiveWorkshop=root=>{root.querySelectorAll('[data-connector-choice]').forEach(box=>box.querySelectorAll('[data-message]').forEach(button=>button.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.classList.toggle('is-active',x===button));box.querySelector('.choice-response').textContent=button.dataset.message;}));root.querySelectorAll('[data-paragraph-workshop]').forEach(box=>box.querySelector('[data-check-paragraph]').onclick=()=>{const selects=[...box.querySelectorAll('select')],hits=selects.filter(s=>s.value===s.dataset.answer).length;selects.forEach(s=>s.classList.toggle('is-correct',s.value===s.dataset.answer));box.querySelector('[data-paragraph-feedback]').innerHTML=hits===selects.length?'<strong>As três relações ficaram coerentes.</strong><p>Agora releia o parágrafo e observe a progressão: acréscimo, exemplo e conclusão.</p>':`<strong>${hits} de ${selects.length} relações coerentes.</strong><p>Leia o trecho anterior e pergunte o que a próxima frase realmente faz.</p>`;});root.querySelectorAll('[data-writing-studio]').forEach(box=>{const area=box.querySelector('textarea'),status=box.querySelector('.writing-status'),update=()=>{const text=area.value.trim(),words=text?text.split(/\s+/).length:0,relations=['adição','contraste','causa','conclusão'].filter((_,i)=>[/(além disso|também|ainda)/i,/(mas|porém|contudo|embora)/i,/(porque|já que|por isso|desse modo)/i,/(portanto|logo|assim|em síntese)/i][i].test(text));status.textContent=`${words} ${words===1?'palavra':'palavras'} · ${relations.length?relations.join(', '):'nenhuma relação marcada ainda'}`;};area.addEventListener('input',update);});};

/* Provocação enviada pelo professor para abrir Dilatação Térmica. */
const thermal=MM.lessons.find(lesson=>lesson.id==='dilatacao');
if(thermal?.slides?.[0]){
 const provocation=`<section class="thermal-provocation"><div class="provocation-copy"><p class="eyebrow">Provocação inicial</p><h2>Você está em casa num domingo e vê o piso levantar. O que faz?</h2><div class="sunday-reaction">SENHOR!</div><p>Antes de explicar, observe os dois registros e formule uma hipótese: o que pode acontecer quando as peças tentam se expandir, mas quase não encontram espaço para isso?</p><aside><strong>Investigue antes de concluir</strong><p>Folgas insuficientes e variações térmicas podem gerar esforços e contribuir para o levantamento. Em situações reais, instalação, aderência, umidade e condições da base também precisam ser verificadas.</p></aside></div><div class="provocation-videos"><iframe src="https://www.youtube-nocookie.com/embed/SJqHLkuvgWU" title="Registro de piso levantando" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><iframe src="https://www.youtube-nocookie.com/embed/RNST_35Svqg" title="Segundo registro de piso estourando" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div></section>`;
 thermal.slides[0].html=provocation+thermal.slides[0].html;
}
})();
