/* Conteúdo editorial separado do motor de navegação. Sem dependências externas. */
window.MM = (() => {
const para = s => `<p>${s}</p>`;
const note = s => `<div class="callout">${s}</div>`;
const formula = (s, terms = []) => `<div class="formula">${s}</div>${terms.length ? `<div class="formula">${terms.map(([t,d])=>`<button data-definition="${d}" aria-label="Explorar ${t}">${t}</button>`).join(' · ')}</div><p class="formula-explanation" role="status">Toque em um termo para explorar seu significado.</p>`:''}`;
const story = (id,title) => `<a class="story-link" href="#historia/${id}/0" data-story="${id}"><span>Por trás da Física</span><strong>${title}</strong><small>Conheça a história</small></a>`;
const report = () => '';
const lab = (id,label) => `<div class="lab" data-lab="${id}"><div class="lab-head"><span>${label}</span><span>Explore</span></div><div class="lab-body"></div><div class="observation-bar"><span>Observação interativa</span>${report('observação',label)}</div></div>`;
const split = (copy,right) => `<div class="split"><div class="copy">${copy}</div>${right}</div>`;
const quiz = (id,title,q,options,correct,hint,steps) => ({id,title,q,options,correct,hint,steps});
const quizzes = {
 depth:quiz('depth','Pressão a 5 metros','Um reservatório aberto contém água de densidade 1.000 kg/m³. Adote g = 10 m/s² e pressão atmosférica de 100 kPa. Qual é a pressão absoluta a 5 m de profundidade?',['50 kPa','100 kPa','150 kPa','500 kPa'],2,'A pressão absoluta inclui a pressão na superfície e a contribuição da coluna de água.',['Contribuição hidrostática: ρgh = 1.000 × 10 × 5 = 50.000 Pa = 50 kPa.','Some a pressão atmosférica: p = 100 + 50 = 150 kPa.','50 kPa seria a pressão manométrica nesse reservatório, não a absoluta.']),
 density:quiz('density','Uma medida de densidade','Uma peça homogênea tem massa de 540 g e volume de 200 cm³. Qual é sua densidade em unidades do SI?',['2,7 kg/m³','270 kg/m³','2.700 kg/m³','27.000 kg/m³'],2,'Calcule em g/cm³; depois use 1 g/cm³ = 1.000 kg/m³.',['ρ = m/V = 540/200 = 2,7 g/cm³.','Como 1 g = 10⁻³ kg e 1 cm³ = 10⁻⁶ m³, 1 g/cm³ = 10³ kg/m³.','Logo, ρ = 2.700 kg/m³.']),
 press:quiz('press','A prensa hidráulica','Em uma prensa ideal, os êmbolos estão na mesma altura. A₁ = 5 cm², A₂ = 100 cm² e F₁ = 80 N. Qual força útil F₂ é produzida?',['4 N','80 N','400 N','1.600 N'],3,'Use a razão entre as áreas. Elas podem ficar em cm² porque a unidade se cancela.',['F₁/A₁ = F₂/A₂. A razão A₂/A₁ é 100/5 = 20.','F₂ = 80 × 20 = 1.600 N.','O êmbolo maior percorre uma distância 20 vezes menor: não há criação de energia.']),
 buoy:quiz('buoy','O peso que parece desaparecer','Um corpo de volume 2 L e peso 30 N está totalmente imerso em água, suspenso por um fio. Com ρ = 1.000 kg/m³ e g = 10 m/s², qual é a tração no fio?',['10 N','20 N','30 N','50 N'],0,'Primeiro calcule o empuxo; o fio sustenta a parte do peso não compensada por ele.',['2 L = 0,002 m³. E = ρgV = 1.000 × 10 × 0,002 = 20 N.','Em equilíbrio: T + E = P. Logo, T = 30 − 20 = 10 N.','O peso gravitacional continua sendo 30 N. O dinamômetro mede a tração de 10 N.']),
 bar:quiz('bar','Um pequeno alongamento','Uma barra de 2 m tem α = 12 × 10⁻⁶ °C⁻¹. A temperatura passa de 20 °C a 120 °C. Quanto ela se alonga?',['0,24 mm','2,4 mm','24 mm','2,4 m'],1,'Use ΔT = 120 − 20. A variação calculada em metros deve ser convertida para milímetros.',['ΔT = 100 °C. ΔL = L₀αΔT.','ΔL = 2 × 12 × 10⁻⁶ × 100 = 0,0024 m = 2,4 mm.','O comprimento final é 2,0024 m. ΔL e L final são grandezas diferentes.']),
 liquid:quiz('liquid','O líquido que transborda','Um recipiente está cheio com 1.000 mL de líquido. γlíquido = 9 × 10⁻⁴ °C⁻¹ e γrecipiente = 3 × 10⁻⁴ °C⁻¹. Ao aquecer tudo em 10 °C, quanto transborda?',['3 mL','6 mL','9 mL','12 mL'],1,'O transbordamento corresponde à expansão aparente, pois a capacidade do recipiente também aumenta.',['ΔVreal = 1.000 × 9 × 10⁻⁴ × 10 = 9 mL.','ΔVrecipiente = 1.000 × 3 × 10⁻⁴ × 10 = 3 mL.','ΔVaparente = 9 − 3 = 6 mL. Supomos aquecimento uniforme e nenhuma evaporação.'])
};
const exercise = id => `<div class="quiz" data-quiz="${id}"></div>`;
const lessons = [
{id:'hidrostatica',area:'Mecânica',title:'Introdução à Hidrostática',desc:'Densidade, pressão e o peso de uma coluna de líquido.',symbol:'ρ · g · h',time:'25–35 min',slides:[
{label:'Observar',title:'O que muda quando você <em>mergulha?</em>',html:split(para('A água parece a mesma. Mas a cada metro de descida, a pressão aumenta. A hidrostática estuda fluidos em repouso e as forças associadas a eles.')+para('Mova o sensor e acompanhe a pressão. Depois, troque o líquido. O que muda quando a profundidade fica igual?')+note('Nesta aula: densidade → pressão → equilíbrio dos fluidos → pressão absoluta. Você precisa apenas de proporções e conversão de unidades.')+story('torricelli','O peso do ar invisível'),lab('depth','Um sensor sob a superfície'))},
{label:'Densidade',title:'A mesma medida. <em>Outra massa.</em>',html:split(para('Densidade relaciona a massa à quantidade de espaço ocupado. Para um corpo homogêneo, ela caracteriza o material nas condições de temperatura e pressão consideradas.')+formula('ρ = m / V',[['ρ','Densidade: massa por unidade de volume. No SI, kg/m³.'],['m','Massa, medida em quilogramas no SI.'],['V','Volume, medido em metros cúbicos no SI.']])+note('1 L = 10⁻³ m³ · 1 cm³ = 10⁻⁶ m³<br>1 g/cm³ = 1.000 kg/m³.')+para('Um objeto grande não precisa ser mais denso que um pequeno. Para comparar materiais, compare a massa de volumes iguais.'),lab('density','Massa e volume'))},
{label:'Pressão',title:'A força importa. <em>A área também.</em>',html:split(para('Uma mesma força perpendicular, distribuída por uma área menor, produz uma pressão média maior. É por isso que uma ponta concentra o efeito de uma força.')+formula('p = F⊥ / A')+para('A unidade de pressão no SI é o pascal: <strong>1 Pa = 1 N/m²</strong>. Pressão é uma grandeza escalar; a força de pressão sobre uma superfície tem direção normal a ela.')+note('Não confunda pressão com força. Em um fluido em repouso, a pressão em um ponto é a mesma em todas as direções.'),lab('pressure','Distribua a força'))},
{label:'Lei de Stevin',title:'Mais fundo. <em>Mais pressão.</em>',html:split(para('Em um fluido homogêneo em repouso, com g constante, a diferença de pressão entre dois níveis depende do desnível vertical.')+formula('Δp = ρgΔh')+para('À profundidade h abaixo da superfície: <strong>p = p₀ + ρgh</strong>. A parcela ρgh é a contribuição hidrostática da coluna de líquido.')+note('A profundidade é vertical. O formato do recipiente não entra na equação. Pontos no mesmo nível de um mesmo líquido conectado e em repouso têm a mesma pressão.')+para('Vasos comunicantes abertos ao mesmo ambiente atingem o mesmo nível quando contêm o mesmo líquido. Com líquidos diferentes e imiscíveis, compare as pressões na mesma altura.'),lab('depth','Profundidade e densidade'))},
{label:'Referências de pressão',title:'Absoluta ou relativa <em>a quê?</em>',html:split(para('<strong>Pressão absoluta</strong> usa o vácuo como referência. <strong>Pressão manométrica</strong> usa a pressão atmosférica local.')+formula('pabs = patm + pman')+para('Em um reservatório aberto, p₀ = patm e pman = ρgh. Em um reservatório fechado e pressurizado, p₀ pode ser diferente de patm: a parcela ρgh continua sendo o acréscimo devido à profundidade.')+note('Exemplo: água a 3 m, com g = 10 m/s² e patm = 100 kPa.<br>pman = 30 kPa; pabs = 130 kPa. Na superfície, a pressão manométrica é zero, mas a absoluta não é.')+para('A atmosfera padrão vale 101,325 kPa. Aqui adotamos 100 kPa como aproximação didática.'),lab('depth','Compare as duas leituras'))},
{label:'Praticar · 1',title:'Qual pressão <em>você está calculando?</em>',html:split(para('Faça uma previsão antes de calcular. A pressão absoluta debaixo da água precisa ser maior que a pressão na superfície.')+note('Questão autoral. Use as pistas se precisar e revele a resolução por etapas.'),exercise('depth'))},
{label:'Praticar · 2',title:'Uma boa resposta começa <em>nas unidades.</em>',html:split(para('Densidade não é massa. Escreva as unidades ao lado dos valores e confira a ordem de grandeza do resultado.'),exercise('density'))},
{label:'Síntese',title:'Uma coluna de líquido. <em>Três ideias.</em>',html:`<div class="summary-grid"><article><h3>Constituição</h3>${formula('ρ = m / V')}<p>Mais massa no mesmo volume significa maior densidade.</p></article><article><h3>Distribuição</h3>${formula('p = F⊥ / A')}<p>A pressão relaciona força normal e área.</p></article><article><h3>Profundidade</h3>${formula('p = p₀ + ρgh')}<p>O líquido acrescenta pressão à que já existe na superfície.</p></article></div>${story('torricelli','Como medir o peso do ar?')}<div class="next-study"><a class="primary" href="#aula/pascal-arquimedes/0">Estudar Pascal e Arquimedes</a><a class="secondary" href="#estudos">Voltar aos estudos</a></div>`}
]},
{id:'pascal-arquimedes',area:'Mecânica',title:'Pascal e Arquimedes',desc:'Como um fluido transmite forças e sustenta um corpo.',symbol:'F / A · ρgV',time:'30–40 min',slides:[
{label:'Observar',title:'Uma força pequena. <em>Um efeito maior.</em>',html:split(para('Uma prensa hidráulica usa um fluido para conectar dois êmbolos. Aumente a área do êmbolo de saída e observe a força disponível.')+para('Depois, investigaremos outro efeito da pressão: o empuxo, que ajuda a sustentar corpos imersos.')+note('Pré-requisitos: pressão, densidade e equilíbrio de forças. Modelo ideal: fluido incompressível, sem vazamentos ou atrito; êmbolos à mesma altura.')+story('arquimedes-pascal','Duas maneiras de compreender a água'),lab('pascal','Prensa hidráulica ideal'))},
{label:'Princípio de Pascal',title:'A pressão <em>se transmite.</em>',html:split(para('Uma variação de pressão aplicada a um fluido confinado em equilíbrio é transmitida integralmente a todas as suas partes e às paredes do recipiente.')+formula('Δp₁ = Δp₂ &nbsp; ⇒ &nbsp; F₁/A₁ = F₂/A₂')+note('O princípio trata da <strong>variação</strong> de pressão. A pressão total ainda pode ser diferente em pontos de alturas diferentes por causa da gravidade.')+para('Uma área maior converte a mesma variação de pressão em uma força maior. Freios e elevadores hidráulicos usam esse princípio.'),lab('pascal','Explore a razão entre áreas'))},
{label:'Energia',title:'Ganha-se força. <em>Percorre-se menos.</em>',html:split(para('Em uma prensa ideal, o volume deslocado de um lado é o volume recebido do outro. A vantagem em força vem acompanhada de uma redução no deslocamento.')+formula('A₁d₁ = A₂d₂')+formula('F₁d₁ = F₂d₂')+note('Se A₂ = 10A₁, então F₂ = 10F₁ e d₂ = d₁/10. O trabalho de entrada e o de saída são iguais no modelo ideal.')+para('Máquinas reais têm perdas. A energia útil de saída é menor que a energia fornecida.'),lab('pascal','Força e deslocamento'))},
{label:'Princípio de Arquimedes',title:'O líquido também <em>empurra para cima.</em>',html:split(para('A pressão aumenta com a profundidade. Em um corpo imerso, a resultante das forças exercidas pelo fluido aponta para cima: é o empuxo.')+formula('E = ρfluido g Vdeslocado',[['ρfluido','Use a densidade do fluido, não a densidade do corpo.'],['Vdeslocado','Volume de fluido deslocado: corresponde à parte submersa do corpo.']])+para('O empuxo tem módulo igual ao peso do fluido deslocado. Para um corpo totalmente imerso, o volume deslocado é seu volume externo.')+note('O resultado supõe fluido em equilíbrio e contato com a superfície imersa do corpo, inclusive por baixo.'),lab('buoyancy','Um corpo na água'))},
{label:'Flutuação',title:'Flutuar é encontrar <em>um equilíbrio.</em>',html:split(para('Sem apoio ou fio, um corpo em repouso flutuando tem <strong>E = P</strong>. Se for homogêneo, a fração submersa é:')+formula('Vsub / Vcorpo = ρcorpo / ρfluido')+para('Menor densidade média que o fluido: flutua parcialmente. Mesma densidade: pode ficar totalmente imerso em equilíbrio indiferente. Maior densidade: afunda, até encontrar apoio.')+note('Um navio de aço pode flutuar porque sua densidade média inclui o espaço interno. A massa por volume total é o que importa.')+para('Corpo suspenso e parado: T = P − E. O peso real não diminui; a força de sustentação necessária diminui.'),lab('buoyancy','Compare peso e empuxo'))},
{label:'Praticar · 1',title:'A área muda <em>a força.</em>',html:split(para('Verifique as condições do modelo antes de usar a proporção. Aqui os êmbolos estão na mesma altura e as perdas são desprezíveis.'),exercise('press'))},
{label:'Praticar · 2',title:'O que o dinamômetro <em>mostraria?</em>',html:split(para('Desenhe mentalmente as forças: peso para baixo, empuxo e tração para cima. O corpo está em equilíbrio.'),exercise('buoy'))},
{label:'Síntese',title:'O mesmo fluido. <em>Dois princípios.</em>',html:`<div class="summary-grid"><article><h3>Pascal</h3>${formula('F₁/A₁ = F₂/A₂')}<p>A variação de pressão se transmite; a área transforma pressão em força.</p></article><article><h3>Arquimedes</h3>${formula('E = ρfluido g Vsub')}<p>O empuxo corresponde ao peso do fluido deslocado.</p></article><article><h3>Equilíbrio</h3>${formula('ΣF = 0')}<p>Considere todas as forças: peso, empuxo, tração e apoios, quando existirem.</p></article></div>${story('arquimedes-pascal','Da geometria dos corpos flutuantes à prensa hidráulica')}<div class="next-study"><a href="#aula/dilatacao/0" class="primary">Estudar dilatação térmica</a><a href="#estudos" class="secondary">Voltar aos estudos</a></div>`}
]},
{id:'dilatacao',area:'Termologia',title:'Dilatação térmica',desc:'Dos sólidos aos líquidos: a matéria muda de dimensão.',symbol:'ΔL = L₀αΔT',time:'35–45 min',slides:[
{label:'Observar',title:'A matéria <em>se move.</em>',html:split(para('Em muitos sólidos, aquecer aumenta a agitação térmica e o afastamento médio entre as partículas. O resultado aparece em uma escala maior: o corpo se dilata.')+note('As partículas não crescem. A expansão está relacionada à mudança no afastamento médio, e não apenas ao fato de elas vibrarem mais.')+para('Aqueça o modelo. Ao resfriar, observe a contração. A rede é esquemática: movimentos e distâncias estão ampliados.')+story('termometros','Quando o calor ganhou uma medida'),lab('particles','Modelo microscópico'))},
{label:'Dilatação linear',title:'O comprimento <em>se transforma.</em>',html:split(para('A variação de comprimento depende do comprimento inicial, do material e da mudança de temperatura.')+formula('ΔL = L₀ α ΔT',[['L₀','Comprimento inicial. Uma barra maior se alonga mais para o mesmo material e a mesma variação de temperatura.'],['α','Coeficiente de dilatação linear do material. Unidade: °C⁻¹ ou K⁻¹.'],['ΔT','Temperatura final menos temperatura inicial. Variações em °C e K têm o mesmo valor numérico.']])+note('L = L₀ + ΔL. Para resfriamento, ΔT é negativo e, com α positivo, ocorre contração. Aproximação para pequenas dilatações e α constante.'),lab('bar','Uma barra de 2 metros'))},
{label:'Duas e três dimensões',title:'Da linha <em>ao volume.</em>',html:split(para('Uma placa se expande em duas direções; um sólido, em três. Para materiais isotrópicos, as propriedades são iguais em todas as direções.')+formula('ΔA = A₀ β ΔT<br>ΔV = V₀ γ ΔT')+note('Para pequenas dilatações: β ≈ 2α e γ ≈ 3α. Essas relações não são universais para materiais anisotrópicos.')+para('Um furo em uma placa também aumenta ao aquecer uniformemente. Imagine que o espaço vazio estivesse preenchido pelo mesmo material: ele acompanharia a expansão.'),lab('dimensions','Comprimento, área e volume'))},
{label:'Praticar · sólidos',title:'Pequenas mudanças. <em>Medidas precisas.</em>',html:split(para('Juntas de dilatação permitem que estruturas mudem de comprimento. O alongamento pode ser pequeno, mas impedir essa expansão pode gerar tensões importantes.'),exercise('bar'))},
{label:'Líquidos',title:'Dois corpos. <em>Duas expansões.</em>',html:split(para('Ao aquecer um líquido dentro de um recipiente, os dois podem se expandir. O recipiente ganha capacidade enquanto o líquido ganha volume.')+formula('ΔVreal = ΔVaparente + ΔVrecipiente')+para('Se o recipiente estava completamente cheio, o volume que transborda é a dilatação aparente, quando positiva.')+note('Aqui V₀ = 1.000 mL, γlíquido = 9 × 10⁻⁴ °C⁻¹ e γrecipiente = 3 × 10⁻⁴ °C⁻¹. A ilustração amplia as mudanças e mostra a parte que transborda.'),lab('liquid','Líquido e recipiente'))},
{label:'Dilatação aparente',title:'A parte <em>que não aparece.</em>',html:split(para('O aumento da capacidade do recipiente acomoda uma parte do líquido que se expandiu. Por isso, a medida aparente é menor que a expansão real neste exemplo.')+formula('γaparente ≈ γlíquido − γrecipiente')+note('Essa relação usa volumes iniciais iguais e pequenas expansões. Se o recipiente dilatar mais que o líquido, o nível relativo pode cair, sem transbordamento.')+para('Toque nas parcelas para entender a conta: 9 mL de expansão real = 6 mL aparentes + 3 mL de aumento da capacidade.'),lab('volume','Explore cada parcela'))},
{label:'A água',title:'A exceção <em>está em 4 °C.</em>',html:split(para('À pressão atmosférica, a água líquida tem densidade máxima perto de 4 °C. Entre 0 e 4 °C, aquecer provoca contração; acima de 4 °C, a tendência se inverte.')+formula('Mesma massa: ρ ↑ quando V ↓')+para('A estrutura das ligações de hidrogênio ajuda a explicar esse comportamento. O gelo é menos denso que a água líquida e flutua.')+note('Em lagos de água doce no inverno, o gelo superficial pode isolar a água abaixo. Não é uma regra de temperatura para qualquer lago em qualquer condição.'),lab('water','Densidade da água líquida'))},
{label:'Praticar · líquidos',title:'O que realmente <em>transbordou?</em>',html:split(para('Calcule separadamente as expansões do líquido e do recipiente. Depois interprete a diferença.'),exercise('liquid'))},
{label:'Síntese',title:'Temperatura muda. <em>Dimensões respondem.</em>',html:`<div class="summary-grid"><article><h3>Sólidos</h3>${formula('ΔL = L₀αΔT')}<p>Também: ΔA = A₀βΔT e ΔV = V₀γΔT. Escolha a grandeza adequada.</p></article><article><h3>Líquidos</h3>${formula('γap ≈ γliq − γrec')}<p>Considere o recipiente ao interpretar o volume aparente.</p></article><article><h3>Água</h3>${formula('ρmáx ≈ 4 °C')}<p>De 0 a 4 °C, a água líquida se contrai ao aquecer, à pressão atmosférica.</p></article></div>${story('termometros','Do termoscópio ao termômetro')}<div class="next-study"><a href="#estudos" class="primary">Voltar aos estudos</a><a href="#historias" class="secondary">Explorar as histórias</a></div>`}
]}
];
const source = (url,name) => `<div class="history-source">Para continuar a leitura (requer internet):<a href="${url}" target="_blank" rel="noopener noreferrer">${name}</a></div>`;
const historyPanel = (date,caption) => `<aside class="lab"><p class="eyebrow">Uma ideia em seu tempo</p><div class="history-number">${date}</div><p>${caption}</p></aside>`;
const histories = [
{id:'torricelli',title:'O peso do ar invisível',date:'1644',desc:'Torricelli e a coluna que tornou visível a pressão da atmosfera.',lesson:'hidrostatica',slides:[
{label:'O problema',title:'O espaço vazio <em>podia existir?</em>',html:split(para('Durante muito tempo, fenômenos envolvendo sucção e bombas foram explicados pela ideia de que a natureza evitaria o vazio. O estudo das colunas de líquido ofereceu outra maneira de pensar.')+para('Em Florença, em 1644, Torricelli realizou seu célebre experimento com mercúrio: um tubo cheio, invertido sobre uma cuba, manteve uma coluna suspensa e deixou uma região quase vazia no alto.')+source('https://catalogue.museogalileo.it/multimedia/TorricellisBarometricExperimentBis.html','Museo Galileo — O experimento barométrico de Torricelli'),historyPanel('1644','Uma coluna de líquido ajudou a transformar o ar em algo mensurável.'))},
{label:'A interpretação',title:'A atmosfera <em>sustenta a coluna.</em>',html:split(para('A pressão do ar sobre a superfície da cuba equilibra a coluna. Desprezando a pequena pressão de vapor no alto do tubo:')+formula('patm ≈ ρmercúrio g h')+para('O barômetro transforma uma pressão em uma altura. A leitura varia com a pressão atmosférica; não é uma altura universal e imutável.')+note('A experiência histórica usa mercúrio, um material tóxico. Aqui, explore apenas o modelo digital.')+para('O mesmo raciocínio reaparece na aula: é preciso escolher uma referência e somar a contribuição hidrostática.'),lab('depth','Reencontre a lei hidrostática'))},
{label:'Conexão',title:'O ar já estava <em>na equação.</em>',html:split(para('Um tanque aberto não começa com pressão absoluta zero na superfície. Antes mesmo de mergulhar, a atmosfera já exerce pressão.')+para('O experimento de Torricelli nos ajuda a distinguir pressão absoluta e manométrica — uma diferença que muda o resultado de muitos problemas.')+note('Volte à aula para aplicar p = p₀ + ρgh.'),historyPanel('p₀','Toda medida de pressão precisa de uma referência.'))}
]},
{id:'arquimedes-pascal',title:'A água sustenta. A água transmite.',date:'III a.C. / XVII',desc:'Arquimedes e Pascal: perguntas diferentes, conectadas pela pressão.',lesson:'pascal-arquimedes',slides:[
{label:'Arquimedes',title:'Antes do “Eureka”, <em>um problema de equilíbrio.</em>',html:split(para('Arquimedes, que viveu no século III a.C., investigou geometricamente o equilíbrio de corpos flutuantes. Sua obra tornou o estudo da flutuação um problema matemático.')+para('A história da coroa e do banho é famosa, mas chegou até nós por um relato posterior de Vitrúvio. Ela não deve ser tratada como um registro contemporâneo da descoberta.')+source('https://math.nyu.edu/Archimedes/contents.html','Chris Rorres — Arquimedes, obra e história'),historyPanel('III a.C.','Uma tradição de demonstrações sobre corpos, volumes e equilíbrio.'))},
{label:'Pascal',title:'Da sustentação <em>à transmissão.</em>',html:split(para('Séculos depois, Blaise Pascal (1623–1662) formulou o princípio de transmissão das variações de pressão em um fluido confinado.')+para('A conexão é a pressão. Em Arquimedes, sua variação com a profundidade produz empuxo. Em Pascal, uma pressão adicional é transmitida pelo fluido e pode produzir forças diferentes em áreas diferentes.')+source('https://openstax.org/books/college-physics-2e/pages/11-5-pascals-principle','OpenStax — Princípio de Pascal'),lab('pascal','Da ideia à prensa ideal'))},
{label:'Conexão',title:'Dois nomes. <em>Dois raciocínios.</em>',html:split(para('Não escolha uma fórmula apenas porque o problema menciona água. Pergunte qual é a situação física.')+note('<strong>Êmbolos conectados?</strong> Relacione força e área.<br><strong>Corpo imerso?</strong> Calcule o empuxo e faça o balanço de forças.')+para('A mesma ferramenta conceitual — pressão — permite explicar como uma máquina amplia uma força e como um líquido sustenta um corpo.'),lab('buoyancy','Volte ao equilíbrio'))}
]},
{id:'termometros',title:'Quando o calor ganhou uma medida',date:'Século XVII',desc:'Da indicação de aquecimento à comparação de temperaturas.',lesson:'dilatacao',slides:[
{label:'O termoscópio',title:'Ver uma mudança <em>antes de dar-lhe um número.</em>',html:split(para('No início da instrumentação térmica moderna, o termoscópio permitia observar mudanças de temperatura. A expansão do ar em um bulbo deslocava o líquido conectado a ele.')+para('O Museo Galileo apresenta o instrumento associado às experiências de Galileo como precursor do termômetro. Observar uma mudança, porém, não é o mesmo que medi-la com uma escala padronizada.')+source('https://catalogue.museogalileo.it/multimedia/ThermoscopeBis.html','Museo Galileo — O termoscópio'),historyPanel('XVII','Instrumentos tornam comparáveis fenômenos que os sentidos percebem de forma subjetiva.'))},
{label:'Da indicação à medida',title:'Uma expansão <em>pode ser uma régua.</em>',html:split(para('Termômetros de líquido usam uma propriedade que varia com a temperatura. Quando o líquido se expande relativamente ao vidro, o nível se desloca em um tubo estreito.')+para('Para transformar essa indicação em temperatura, é preciso calibrar uma escala. A expansão do recipiente também participa da leitura.')+note('O modelo ao lado mostra volumes ampliados para visualização. Ele não reproduz a geometria capilar de um termômetro.')+source('https://openstax.org/books/college-physics-2e/pages/13-2-thermal-expansion-of-solids-and-liquids','OpenStax — Expansão térmica dos sólidos e líquidos'),lab('liquid','Duas expansões, uma leitura'))},
{label:'Conexão',title:'Medir exige <em>conhecer o material.</em>',html:split(para('Uma boa escala depende de uma propriedade previsível. Nem todos os materiais respondem do mesmo modo: a água, perto de 4 °C, mostra por que generalizações precisam de limites.')+para('Volte à aula para comparar a dilatação real do líquido com a aparente e explorar a densidade da água.'),lab('water','Uma exceção reveladora'))}
]}
];
return {lessons,histories,quizzes,report};
})();

/* Segunda edição: aprofundamento autoral para estudo independente. */
(() => {
const {lessons,histories,quizzes,report}=window.MM;
const titles=[
 ['Introdução à Hidrostática','Densidade e massa específica','Pressão e área de contato','Pressão hidrostática: lei de Stevin','Pressão absoluta e manométrica','Exercício: pressão absoluta','Exercício: densidade e unidades','Resumo de Hidrostática'],
 ['Prensa hidráulica','Princípio de Pascal','Conservação de volume e trabalho','Princípio de Arquimedes','Flutuação e peso aparente','Exercício: prensa hidráulica','Exercício: empuxo e tração','Resumo de Pascal e Arquimedes'],
 ['Temperatura e agitação térmica','Dilatação linear dos sólidos','Dilatação superficial e volumétrica','Exercício: dilatação linear','Dilatação dos líquidos e do recipiente','Dilatação real e aparente','Dilatação anômala da água','Exercício: transbordamento','Resumo de dilatação térmica']
];
lessons.forEach((l,j)=>l.slides.forEach((s,i)=>{s.subtitle=s.title;s.title=titles[j][i];s.label=titles[j][i];}));
lessons[1].title='Princípios de Pascal e Arquimedes';
lessons[2].title='Dilatação dos sólidos e líquidos';
lessons.forEach((l,i)=>l.time=['45–60 min','50–65 min','60–80 min'][i]);
const p=s=>`<p>${s}</p>`;
const eq=(s)=>`<div class="equation">${s}</div>`;
const frac=(a,b)=>`<span class="fraction"><span>${a}</span><span>${b}</span></span>`;
const section=(title,body)=>`<section class="deep-section"><h2>${title}</h2>${body}</section>`;
const example=(title,body)=>`<aside class="worked-example"><p class="eyebrow">Exemplo resolvido</p><h3>${title}</h3>${body}</aside>`;
const check=(q,answer)=>`<details class="self-check"><summary>${q}</summary><div>${answer}</div>${report('questão',q)}</details>`;
const more=(l,i,html)=>lessons[l].slides[i].html+=`<div class="study-notes">${html}</div>`;

const sim=(id,label)=>`<div class="lab" data-lab="${id}"><div class="lab-head"><span>${label}</span><span>Laboratório</span></div><div class="lab-body"></div><div class="observation-bar"><span>Observação interativa</span>${report('observação',label)}</div></div>`;
more(0,0,section('O que significa um fluido estar em repouso?',p('Um fluido pode escoar e se deformar continuamente sob uma força tangencial. Líquidos e gases são fluidos. A hidrostática descreve situações em que, na escala observada, não existe escoamento macroscópico em relação ao recipiente. Isso não significa que as moléculas tenham parado de se mover.')+p('Para começar, adotamos um líquido homogêneo: sua densidade é a mesma em todos os pontos. Também desprezamos sua compressão. São aproximações úteis para pequenas variações de pressão; não devem ser estendidas automaticamente ao interior de estrelas ou a toda a atmosfera.'))+section('Leia o experimento em três passos',`<ol><li><strong>Preveja:</strong> se a profundidade dobrar, qual parcela da pressão dobra?</li><li><strong>Compare:</strong> observe a pressão hidrostática e a absoluta. Só a primeira é proporcional à profundidade.</li><li><strong>Explique:</strong> a cápsula contém gás e se comprime quando a pressão externa aumenta. O modelo usa gás a temperatura constante e membrana flexível.</li></ol>`)+check('Na superfície de um tanque aberto, a pressão é zero?',p('A pressão manométrica é zero porque a pressão ali é igual à atmosférica. A pressão absoluta é aproximadamente 100 kPa no nosso modelo. É preciso declarar a referência.')));
more(0,1,section('O que a densidade permite comparar?',p('A razão m/V responde quanto de massa existe em cada unidade de volume. Dobrar a quantidade de um mesmo líquido dobra sua massa e seu volume, mas não muda essa razão. Por isso, densidade não depende apenas do tamanho da amostra.')+p('Para um corpo com espaços vazios ou diferentes materiais, m/V é a densidade média do objeto. Já a massa específica descreve o material. Em uma amostra homogênea sem cavidades, os dois valores coincidem. Um bloco oco pode ter densidade média menor que a do metal que compõe suas paredes.'))+example('Dois recipientes de mesmo volume',p('Um recipiente contém 750 g de um líquido em 1.000 cm³. Outro contém 1.200 g no mesmo volume. A primeira densidade é 0,75 g/cm³; a segunda, 1,20 g/cm³. O segundo líquido tem mais massa por unidade de volume, embora os recipientes ocupem o mesmo espaço.')+eq(`ρ = ${frac('750 g','1.000 cm³')} = 0,75 g/cm³ = 750 kg/m³`))+section('Como usar a simulação',p('Mude somente a massa e mantenha o volume: você altera a densidade média. Depois faça o inverso. A comparação com a água usa 1 g/cm³. Ao atravessar esse valor, muda a condição de flutuação. Os pontos representam porções iguais de massa, não átomos que surgem ou desaparecem.'))+check('Um objeto de 2 kg é necessariamente mais denso que um de 1 kg?',p('Não. Precisamos conhecer os volumes. Um objeto de 2 kg em 4 L tem densidade média 0,5 kg/L; um de 1 kg em 0,5 L tem 2 kg/L.')));
more(0,2,section('Da força ao efeito local',p('A força descreve uma interação entre corpos; a pressão informa como a componente normal dessa força se distribui na área de contato. Se a distribuição não for uniforme, F/A fornece a pressão média. A pressão em cada pequeno trecho pode ser diferente.')+eq(`p = ${frac('F<sub>⊥</sub>','A')} &nbsp; · &nbsp; 1 Pa = ${frac('1 N','1 m²')}`)+p('A conversão de área exige elevar a conversão de comprimento ao quadrado: 1 cm² = (10⁻² m)² = 10⁻⁴ m². É um erro frequente dividir por 100 quando seria necessário dividir por 10.000.'))+example('A mesma força, duas áreas',p('Uma força de 300 N sobre 100 cm² produz 30 kPa. Se a área cair para 25 cm², a pressão média sobe para 120 kPa: a área ficou quatro vezes menor e a pressão quatro vezes maior.'))+section('O que significa a placa quebrar?',p('A simulação inclui uma placa fictícia que cede acima de 150 kPa. O exagero visual mostra a concentração do carregamento, mas não prevê a ruptura de uma mesa real. Na prática, material, espessura, apoios e distribuição das tensões também importam. Pressão sozinha não determina toda a resistência estrutural.'))+check('Se força e área dobrarem juntas, o que acontece com a pressão?',p('Ela permanece igual: (2F)/(2A) = F/A. Experimente combinar os dois controles.')));
more(0,3,section('De onde vem a lei de Stevin?',p('Imagine uma coluna de líquido de área A e altura h. A força de pressão na base aponta para cima; na face superior, para baixo. O peso da coluna também aponta para baixo. Em equilíbrio, a força de baixo compensa as outras duas.')+eq('pA − p<sub>0</sub>A − mg = 0')+p('A coluna tem volume Ah e massa ρAh. Substituindo a massa e dividindo a equação por A, a área desaparece:')+eq('p − p<sub>0</sub> = ρgh')+p('Isso explica por que recipientes estreitos ou largos podem ter a mesma pressão no fundo se contiverem o mesmo líquido, a mesma altura e a mesma pressão superficial. A força no fundo ainda depende da área do fundo.'))+example('Uma diferença de nível',p('Dois pontos na água têm profundidades de 1,5 m e 4,0 m. O desnível é 2,5 m. A diferença de pressão é 1.000 × 10 × 2,5 = 25.000 Pa. A pressão atmosférica se cancela porque é a mesma referência para os dois pontos.'))+check('A distância inclinada até a superfície pode substituir h?',p('Não. A coluna que entra no balanço gravitacional usa a distância vertical. Um tubo inclinado pode ser comprido e ainda ter um pequeno desnível.')));
more(0,4,section('Escolha a referência antes de calcular',p('Uma pressão absoluta é medida a partir do vácuo. Um manômetro comum compara a pressão do sistema com a pressão externa. Uma leitura manométrica negativa indica pressão menor que a do ambiente, não pressão absoluta negativa.')+eq('p<sub>abs</sub> = p<sub>atm</sub> + p<sub>man</sub>')+p('Em um tanque aberto, a superfície recebe a pressão do ar: p₀ = p<sub>atm</sub>. Em um tanque fechado, a superfície pode ser pressionada por um gás; nesse caso, use a pressão absoluta desse gás como p₀. Não some a pressão atmosférica duas vezes.'))+example('Um tanque fechado',p('Um gás acima da água tem pressão absoluta de 160 kPa. A 2 m de profundidade, a água acrescenta 20 kPa: a pressão absoluta é 180 kPa. Se o ambiente está a 100 kPa, a pressão manométrica nesse ponto é 80 kPa.'))+check('Um manômetro registra −20 kPa em um ambiente de 100 kPa. Qual é a pressão absoluta?',p('80 kPa. O sinal negativo descreve a diferença em relação ao ambiente. A pressão absoluta continua positiva.')));
more(1,0,section('Antes de mover os êmbolos',p('O circuito precisa estar preenchido. Quando o êmbolo menor desce, o volume de fluido deslocado percorre o canal e empurra o outro êmbolo. O canal e os cilindros formam uma região contínua: o volume expulso de um lado precisa ser acomodado do outro.')+p('Use “Acionar prensa” para comparar os deslocamentos. A representação é esquemática; as leituras apresentam a razão física correta. Para a relação de forças adotada, desprezamos perdas e diferenças de pressão causadas pelo desnível durante o pequeno curso.')));
more(1,1,section('Pressão transmitida não é força transmitida',p('Aplicar 50 N em 5 cm² acrescenta 100 kPa ao fluido. Em um êmbolo de 50 cm², esse mesmo acréscimo de pressão corresponde a 500 N. A força cresce porque a área cresce; o acréscimo de pressão permanece igual.')+eq(`${frac('F<sub>1</sub>','A<sub>1</sub>')} = ${frac('F<sub>2</sub>','A<sub>2</sub>')} &nbsp; ⇒ &nbsp; F<sub>2</sub> = F<sub>1</sub>${frac('A<sub>2</sub>','A<sub>1</sub>')}`)+p('Se a questão fornecer os raios, calcule áreas. Para êmbolos circulares, A = πr². Dobrar o raio multiplica a área por quatro, e não por dois.'))+example('Raios e áreas',p('Um êmbolo tem raio de 2 cm e o outro de 6 cm. A razão entre áreas é (6/2)² = 9. Uma força de 70 N no menor pode equilibrar uma força útil de 630 N no maior, no modelo ideal.'))+check('Pascal afirma que a pressão total é igual em qualquer ponto do fluido?',p('Não. O acréscimo aplicado se transmite. Pontos em alturas diferentes ainda podem ter pressões totais diferentes por causa de ρgΔh.')));
more(1,2,section('Por que não há energia gratuita?',p('Cada êmbolo desloca um volume igual à área multiplicada pelo percurso. Como o líquido é incompressível e o circuito não vaza, o volume que sai de um cilindro entra no outro.')+eq('A<sub>1</sub>d<sub>1</sub> = A<sub>2</sub>d<sub>2</sub>')+p('Multiplicando a igualdade de pressões pela igualdade dos volumes, obtemos a igualdade dos trabalhos. Com força constante e deslocamento paralelo à força, W = Fd.')+eq('W<sub>entrada</sub> = F<sub>1</sub>d<sub>1</sub> = F<sub>2</sub>d<sub>2</sub> = W<sub>saída</sub>')+example('Uma força dez vezes maior',p('Se F₁ = 80 N e A₂/A₁ = 10, então F₂ = 800 N. Para d₁ = 10 cm = 0,10 m, d₂ = 1 cm = 0,01 m. Os dois trabalhos valem 8 J. Na máquina real, parte da energia se dissipa.'))));
more(1,3,section('Derivando o empuxo em um bloco',p('Considere um bloco com faces horizontais de área A e altura H, totalmente imerso. As forças nas faces laterais se cancelam em pares. Na face inferior, a pressão é maior que na superior em ρgH.')+eq('E = (p<sub>baixo</sub> − p<sub>cima</sub>)A = ρ<sub>fluido</sub>gHA')+p('Como HA é o volume submerso do bloco, E = ρ<sub>fluido</sub> g V<sub>sub</sub>. O teorema de Arquimedes estende esse resultado a corpos de formas gerais. Se o corpo estiver parcialmente imerso, conte só o volume abaixo da superfície.')+p('Não coloque a densidade do objeto no lugar da densidade do fluido. O fluido é quem exerce o empuxo. A densidade do objeto entra no cálculo de seu peso.'))+check('Aprofundar um corpo totalmente imerso sempre aumenta o empuxo?',p('Não em um líquido homogêneo incompressível, com g constante e volume do corpo fixo. As pressões de cima e de baixo aumentam juntas, mas sua diferença permanece a mesma.')));
more(1,4,section('Três situações que precisam ser separadas',`<ol><li><strong>Flutuando sem apoio:</strong> o volume submerso se ajusta até E = P.</li><li><strong>Totalmente imerso e suspenso:</strong> se P > E, um fio acima pode fornecer T = P − E.</li><li><strong>Afundado e apoiado:</strong> surge uma força normal. É preciso analisar o contato; não aplique automaticamente o modelo de corpo livre.</li></ol>`)+p('No laboratório, solte o bloco. O movimento é amortecido para facilitar a observação e termina no equilíbrio ou no fundo. O traço de força mostra qual sentido a resultante favorece; o modelo de movimento é didático, sem pretensão de reproduzir o arrasto de um objeto real.')+example('Uma peça que flutua',p('Um corpo homogêneo com densidade média 600 kg/m³ flutua na água. A fração submersa é 600/1.000 = 0,60. Portanto, 60% do volume fica submerso e 40% acima da superfície. Essa proporção é volumétrica, não necessariamente uma proporção de alturas para qualquer formato.'))+check('Um corpo pode receber empuxo e mesmo assim afundar?',p('Sim. Se estiver totalmente imerso e seu peso for maior que o empuxo, a resultante aponta para baixo. Receber uma força para cima não basta para garantir a subida.')));
more(2,0,section('Temperatura, calor e energia interna',p('Temperatura é uma grandeza de estado que permite prever o sentido da transferência espontânea de energia por diferença térmica. Em modelos clássicos simples, ela se relaciona à energia cinética média microscópica. Não é correto dizer que a temperatura mede toda a energia de um corpo.')+p('Calor é energia em transferência devido a uma diferença de temperatura. Um corpo possui energia interna; não contém uma substância chamada calor. Dois corpos podem ter a mesma temperatura e energias internas diferentes, por terem quantidades ou composições diferentes.')+p('Em um sólido, os átomos oscilam em torno de posições de equilíbrio. A dilatação usual depende também da assimetria das interações entre eles: mais vibração, sozinha, não prova que a distância média precise aumentar.'))+section('Celsius e kelvin: temperatura não é variação',eq('T<sub>K</sub> = θ<sub>C</sub> + 273,15')+p('0 °C corresponde a 273,15 K. Já 0 K corresponde a −273,15 °C. Ao converter uma variação, o deslocamento de 273,15 se cancela: aquecer de 20 a 30 °C é aumentar 10 °C, ou 10 K.')+p('Kelvin é escrito sem o símbolo de grau. A simulação mantém o mesmo estado físico ao trocar de escala. O limite de 0 K abre uma curiosidade: não representa um experimento que conseguiu atingir o zero absoluto.'))+check('Se um corpo recebe calor, sua temperatura sempre aumenta?',p('Não. Durante uma mudança de fase, por exemplo, pode haver absorção de energia sem aumento de temperatura, sob condições adequadas. O modelo de rede desta tela não simula fusão.')));
more(2,1,section('Use a variação, não a temperatura final',eq('ΔT = T<sub>f</sub> − T<sub>0</sub> &nbsp; · &nbsp; ΔL = L<sub>0</sub>αΔT')+p('O coeficiente α descreve a sensibilidade do comprimento à temperatura. Sua unidade é o inverso de uma unidade de temperatura. Se α está em °C⁻¹, use a variação em °C; o mesmo valor numérico serve para variações em K.')+p('Na simulação, trocar o material mantém o comprimento inicial e a variação térmica. Assim você isola o efeito de α. As três referências tracejadas ajudam a comparar materiais na mesma temperatura.')+eq('L<sub>f</sub> = L<sub>0</sub>(1 + αΔT)')+p('O gráfico ΔL × ΔT é uma reta quando α é constante. Sua inclinação é L₀α. Comparar inclinações só permite comparar α diretamente se os comprimentos iniciais forem iguais.'))+example('Resfriamento também conta',p('Uma haste de cobre de 1,5 m, com α = 17 × 10⁻⁶ °C⁻¹, esfria de 80 a 20 °C. A variação é −60 °C. Logo, ΔL = −0,00153 m = −1,53 mm. O sinal negativo indica contração; o comprimento final é 1,49847 m.'))+check('Uma barra aquecida de 20 para 40 °C dilata o dobro de outra aquecida de 20 para 30 °C?',p('Sim, se as barras tiverem o mesmo comprimento inicial, material e coeficiente constante. As variações são 20 °C e 10 °C. Não use a razão 40/30.')));
more(2,2,section('Por que β ≈ 2α e γ ≈ 3α?',p('Para um quadrado isotrópico, cada lado passa de L₀ a L₀(1 + αΔT). A área final é o quadrado dessa expressão. Expandindo:')+eq('A<sub>f</sub> = A<sub>0</sub>[1 + 2αΔT + (αΔT)²]')+p('Quando |αΔT| é muito menor que 1, o termo quadrático é pequeno em comparação com o linear. Resulta ΔA ≈ 2A₀αΔT, ou β ≈ 2α. Para o volume, a expansão do cubo produz 3α no termo linear.')+p('O critério não é simplesmente “α é pequeno”: a variação de temperatura também importa. Materiais anisotrópicos e grandes variações podem exigir outro modelo.'))+section('O furo também dilata',p('Uma abertura acompanha o aumento das distâncias da placa. Ela não se fecha porque há “mais material em volta”. O contorno do furo se afasta do centro junto com a placa. A simulação deixa visíveis os contornos inicial e final.')));
more(2,4,section('Volume real e capacidade disponível',p('Para o líquido, calcule ΔV<sub>real</sub> = V₀γ<sub>líquido</sub>ΔT. Para o recipiente, calcule o aumento de sua capacidade interna: ΔV<sub>recipiente</sub> = V₀γ<sub>recipiente</sub>ΔT, quando ambos começam com o mesmo volume.')+p('Se o recipiente estava cheio até a borda, a diferença positiva transborda. Se houver espaço livre inicialmente, parte ou toda essa diferença poderá ser acomodada: expansão aparente não implica necessariamente derramamento.')+eq('ΔV<sub>aparente</sub> = V<sub>0</sub>(γ<sub>líquido</sub> − γ<sub>recipiente</sub>)ΔT')+p('O controle permite comparar a deformação do recipiente. Os volumes numéricos usam a aproximação linear; o deslocamento visual foi ampliado. Não são previstos evaporação, fervura nem alterações de fase.')));
more(2,5,example('O recipiente importa mesmo quando parece rígido',p('Considere 800 mL de líquido, γ<sub>líquido</sub> = 7 × 10⁻⁴ °C⁻¹, γ<sub>recipiente</sub> = 2 × 10⁻⁴ °C⁻¹ e aquecimento de 25 °C. O líquido ganha 14 mL; a capacidade ganha 4 mL; a expansão aparente é 10 mL.')+p('Ignorar o recipiente daria 14 mL como transbordamento, superestimando o resultado.'))+check('Se γ<sub>líquido</sub> = γ<sub>recipiente</sub>, o líquido deixa de dilatar?',p('Não. Os dois se expandem na mesma proporção e a dilatação aparente é zero. A dilatação real do líquido pode ser positiva.')));
more(2,6,section('Por que a água exige um tratamento especial?',p('As ligações de hidrogênio favorecem estruturas relativamente abertas. Perto de 0 °C, parte da organização se reorganiza ao aquecer, permitindo maior aproximação média. Até perto de 4 °C, essa contração predomina sobre a expansão térmica usual.')+p('De 0 a 4 °C, o volume de uma massa fixa diminui e sua densidade aumenta. Acima dessa região, a expansão volta a predominar. Por isso, usar um único coeficiente positivo constante atravessando esse intervalo daria uma previsão errada.')+p('No gráfico, a escala vertical da densidade é ampliada para mostrar uma variação pequena. O máximo é próximo de 3,98 °C a pressão atmosférica, frequentemente arredondado para 4 °C.'))+check('A água mais densa em um lago está sempre no fundo a 4 °C?',p('Não é uma descrição universal. Temperaturas do ambiente, estação, salinidade, vento e circulação influenciam o lago. A imagem é uma situação didática de água doce sob frio intenso.')));
// Acrescenta um exercício original sobre conversão, sem ampliar o catálogo de aulas.
quizzes.kelvin={id:'kelvin',title:'Temperatura e variação nas duas escalas',q:'Uma amostra passa de 0 °C para 25 °C. Quais são a temperatura final em kelvin e a variação em kelvin?',options:['25 K e 25 K','273,15 K e 298,15 K','298,15 K e 25 K','298,15 K e 273,15 K'],correct:2,hint:'Some 273,15 para converter uma temperatura. Para a variação, subtraia os estados final e inicial.',steps:['T₀ = 273,15 K; T<sub>f</sub> = 25 + 273,15 = 298,15 K.','ΔT = 298,15 − 273,15 = 25 K.','Uma variação de 25 °C tem o mesmo valor numérico que 25 K; uma temperatura de 25 °C não é 25 K.']};
lessons[2].slides.splice(1,0,{label:'Exercício: Celsius e kelvin',title:'Exercício: Celsius e kelvin',subtitle:'Duas escalas, o mesmo estado térmico.',html:`<div class="split"><div class="copy">${p('Antes de usar uma equação de dilatação, diferencie a temperatura de um estado da diferença entre duas temperaturas. Não acrescente 273,15 a uma variação.')}${eq('ΔT<sub>K</sub> = Δθ<sub>C</sub>')}</div><div class="quiz" data-quiz="kelvin"></div></div>`});
histories.push({id:'zero-absoluto',title:'Zero absoluto e movimento quântico',date:'Curiosidade',desc:'Por que 0 °C não é ausência de agitação — e o que muda perto de 0 K.',lesson:'dilatacao',slides:[
{label:'Celsius e kelvin',title:'0 °C e 0 K são temperaturas diferentes',subtitle:'O zero de uma escala não é o zero da outra.',html:`<div class="split"><div class="copy">${p('O zero Celsius é um ponto convencional da escala. Ele não marca a ausência de energia microscópica. À temperatura de 0 °C, o valor na escala absoluta é 273,15 K.')}${eq('0 °C = 273,15 K<br>0 K = −273,15 °C')}${p('A temperatura descreve um estado estatístico de um sistema. Falar na “temperatura de uma única partícula” exige definir com cuidado o contexto; não é o mesmo que olhar uma bolinha e medir quanto ela se move.')}</div>${sim('particles','Temperatura e limite do modelo')}</div>`},
{label:'Terceira lei',title:'É possível atingir o zero absoluto?',subtitle:'Aproximar-se é diferente de alcançar.',html:`<div class="reading-page">${section('O limite do resfriamento',p('Na formulação de inatingibilidade da terceira lei da termodinâmica, não se alcança o zero absoluto por um processo físico com recursos finitos em um tempo finito. Experimentos podem preparar sistemas extremamente frios; isso não equivale a atingir exatamente 0 K.')+p('O bloqueio desta simulação é uma escolha didática: ele permite examinar o limite sem fingir que o controle realizou um resfriamento impossível.'))}${section('O que isso não afirma',p('A terceira lei não proíbe escrever matematicamente um estado a T = 0. Também não diz que todos os sistemas próximos de zero se comportam como o pequeno modelo clássico da tela. Nessa região, efeitos quânticos se tornam essenciais.'))}<div class="history-source"><a href="https://www.nature.com/articles/ncomms14538" target="_blank" rel="noopener">Masanes e Oppenheim — A general derivation and quantification of the third law of thermodynamics (2017)</a></div></div>`},
{label:'Incerteza e estado fundamental',title:'Movimento de ponto zero e incerteza',subtitle:'Menor energia não significa uma trajetória imóvel.',html:`<div class="reading-page">${section('Uma restrição quântica',eq('Δx · Δp ≥ ℏ / 2')+p('Aqui Δx e Δp são dispersões de posição e momento, não erros evitáveis de um instrumento. Para uma partícula confinada, não podemos atribuir simultaneamente posição perfeitamente definida e momento perfeitamente definido.')+p('Um oscilador quântico pode ter energia de ponto zero mesmo no estado fundamental, o estado de menor energia. Isso não é calor que possamos remover indefinidamente. O estado pode ser estacionário, embora medidas de posição e momento tenham dispersão.'))}${section('Duas ideias, sem confusão',p('A inatingibilidade de 0 K é uma afirmação termodinâmica sobre processos de resfriamento. A energia de ponto zero é uma propriedade quântica. Portanto, não é correto usar apenas o princípio de Heisenberg para dizer que “uma partícula não pode chegar a zero kelvin”. A animação de pontos não retrata trajetórias quânticas reais.'))}<div class="history-source"><a href="https://www.nist.gov/news-events/news/2015/12/squeezed-motion-massive-object" target="_blank" rel="noopener">NIST — Medidas do movimento de ponto zero</a></div></div>`}
]});
// Os nomes de etapas históricas também dizem diretamente qual assunto será lido.
const historicTitles=[['Experimento de Torricelli','Pressão atmosférica e barômetro','Pressão na superfície de um líquido'],['Arquimedes e os corpos flutuantes','Pascal e a transmissão de pressão','Aplicações de Pascal e Arquimedes'],['Termoscópio e termômetro','Dilatação e medição de temperatura','Materiais e escalas termométricas']];
histories.slice(0,3).forEach((h,j)=>h.slides.forEach((s,i)=>{s.subtitle=s.title;s.title=historicTitles[j][i];s.label=s.title;}));
})();

/* Quinta edição: percursos guiados para estudo autônomo. Cada inserção prepara
   o conceito seguinte, explicita o raciocínio e ensina a conferir a resposta. */
(()=>{
const lessons=window.MM.lessons;
const page=(lead,body)=>`<div class="guided-reading"><p class="chapter-lead">${lead}</p>${body}</div>`;
const h=(title,body)=>`<section><h2>${title}</h2>${body}</section>`;
const p=text=>`<p>${text}</p>`;
const ul=items=>`<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const steps=items=>`<div class="checkpoint"><h3>Roteiro de pensamento</h3>${items.map((x,i)=>`<div class="worked-line"><strong>${i+1}</strong><span>${x}</span></div>`).join('')}</div>`;
const formula=text=>`<div class="formula">${text}</div>`;

const hydro=lessons.find(x=>x.id==='hidrostatica');
hydro.slides.splice(1,0,
 {label:'Como começar',title:'Como estudar um fluido em repouso',subtitle:'Antes das fórmulas, aprenda a identificar o sistema.',html:page('Hidrostática é o estudo dos fluidos em equilíbrio. O ponto de partida não é decorar ρgh: é decidir qual fluido está sendo estudado, onde estão os pontos de interesse e quais pressões atuam nas fronteiras.',
 h('O que é um fluido?',p('Fluido é uma substância que se deforma continuamente quando submetida a uma força tangencial. Líquidos e gases são fluidos, embora tenham comportamentos diferentes: um líquido conserva aproximadamente seu volume e forma uma superfície livre; um gás ocupa o volume disponível e costuma ser muito mais compressível.')+p('Nesta aula, os líquidos serão tratados como incompressíveis e homogêneos em cada região. Isso significa que adotaremos densidade constante. A hipótese funciona bem para muitos problemas escolares com água, óleo ou mercúrio, mas precisa ser revista em grandes profundidades, mudanças intensas de temperatura ou fluidos estratificados.'))+
 h('O significado de equilíbrio',p('Estar em repouso não significa ausência de forças. Uma pequena porção de água recebe forças de pressão do líquido ao redor e sofre a ação da gravidade. O repouso existe porque essas ações se equilibram. É justamente desse balanço que nasce a variação da pressão com a profundidade.')+p('Escolha sempre um eixo vertical e uma referência. Em seguida, observe se a superfície está aberta ao ar, fechada por um gás ou pressionada por um êmbolo. A pressão nessa fronteira será o ponto de partida para calcular a pressão em outro nível.'))+
 steps(['Desenhe o recipiente e marque os pontos comparados.','Identifique o fluido, sua densidade e a aceleração da gravidade adotada.','Descubra a pressão na superfície ou no ponto de referência.','Use apenas a diferença vertical de altura entre os pontos.','Decida se a resposta pedida é absoluta, manométrica ou apenas uma diferença de pressão.']))},
 {label:'Medir densidade',title:'Como medir e interpretar a densidade',subtitle:'Massa e volume contam histórias diferentes sobre a matéria.',html:page('Densidade é uma razão. Ela compara quanta massa existe em certo volume, por isso não deve ser confundida com o tamanho do objeto nem com sua massa isoladamente.',
 h('Uma medição possível',p('Imagine uma peça sólida sem identificação. Primeiro, uma balança fornece sua massa. Depois, o volume pode ser obtido pelas dimensões geométricas ou pelo deslocamento de líquido em uma proveta. Dividir a massa pelo volume produz a densidade média da peça. Se houver cavidades internas, essa média pode ser muito menor que a densidade do material das paredes.')+formula('ρ = m / V')+p('Uma leitura de 2,7 g/cm³ informa que cada centímetro cúbico da amostra tem, em média, 2,7 g. Para escrever o resultado no SI, use 1 g/cm³ = 1.000 kg/m³. Assim, 2,7 g/cm³ corresponde a 2.700 kg/m³.'))+
 h('Como prever antes de calcular',p('Fixe o volume e aumente a massa: a densidade aumenta. Fixe a massa e aumente o volume: a densidade diminui. Essa previsão simples ajuda a detectar uma divisão invertida ou uma conversão errada. Uma esfera oca pode ser grande e leve; um pequeno bloco metálico pode ser muito mais denso.')+p('Ao comparar com a água, observe a densidade média do corpo. Se ela for menor que a da água, o corpo pode flutuar parcialmente; se for maior, tende a afundar quando não existe outra força de sustentação. O mecanismo completo será construído na aula de Arquimedes.'))+
 steps(['Registre massa e volume com unidades.','Converta as duas grandezas para um sistema coerente.','Calcule m/V e leia o resultado como “massa por unidade de volume”.','Compare a ordem de grandeza com materiais conhecidos.','Volte ao laboratório e altere apenas massa ou apenas volume para isolar cada efeito.']))},
 {label:'Pressão no cotidiano',title:'Da área de contato à pressão',subtitle:'Por que distribuir uma força muda seu efeito.',html:page('Pressão média descreve como a componente perpendicular de uma força se distribui por uma área. A mesma força pode produzir efeitos muito diferentes quando concentrada em uma ponta ou espalhada por uma superfície larga.',
 h('A chapa sobre as telhas',p('Quando um pedreiro precisa se apoiar sobre um telhado, uma chapa ou tábua larga pode distribuir a força por várias telhas. A força total associada ao peso não desaparece. O que muda é a área sobre a qual ela é transmitida e, portanto, a pressão média em cada região. A prática real ainda exige avaliar resistência, apoios, estado das telhas e segurança; a razão F/A sozinha não garante que a estrutura suporte a carga.'))+
 h('A faca e o pneu',p('Uma faca afiada concentra a força numa faixa muito estreita, produzindo grande pressão e facilitando o corte. Um pneu largo faz o oposto: aumenta a área de contato e pode reduzir a pressão média sobre um solo macio. Esses exemplos ajudam a interpretar a proporcionalidade, mas cada situação real envolve também deformação, atrito e propriedades do material.')+formula('p = F<sub>⊥</sub> / A'))+
 h('Como ler a relação',p('Se a força dobra e a área permanece fixa, a pressão dobra. Se a área dobra e a força permanece fixa, a pressão cai pela metade. Se força e área aumentam na mesma proporção, a pressão permanece igual. Sempre converta cm² para m² elevando a conversão ao quadrado: 1 cm² = 10⁻⁴ m².'))+
 steps(['Identifique somente a componente perpendicular da força.','Calcule ou leia a área real de contato.','Faça uma previsão de aumento ou diminuição.','Converta a área para m² quando quiser o resultado em pascal.','Interprete a pressão sem confundi-la com uma previsão completa de ruptura.']))},
 {label:'Resolver hidrostática',title:'Como resolver um problema de hidrostática',subtitle:'Um método que evita somar pressões duas vezes.',html:page('Problemas de hidrostática ficam mais simples quando você percorre o fluido a partir de um ponto cuja pressão é conhecida. Descer em um mesmo líquido aumenta a pressão; subir diminui.',
 h('Percorrendo uma coluna de líquido',p('Considere um tanque aberto com água. Na superfície, a pressão absoluta é a atmosférica. Ao descer uma profundidade h, some ρgh. Se a pergunta pedir apenas o quanto a pressão aumentou em relação à atmosfera, a resposta é ρgh. Se pedir pressão absoluta, inclua a pressão atmosférica.')+formula('p<sub>final</sub> = p<sub>inicial</sub> + ρgΔh')+p('O sinal depende do percurso. Nesta escrita, Δh é positivo quando descemos. Você também pode adotar um eixo vertical positivo para cima e escrever a relação com o sinal correspondente; o essencial é manter a convenção do começo ao fim.'))+
 h('Exemplo completo',p('Em água de densidade 1.000 kg/m³, com g = 10 m/s², um ponto está 6 m abaixo de uma superfície aberta a 100 kPa. A contribuição da água é 1.000 × 10 × 6 = 60.000 Pa = 60 kPa. A pressão manométrica vale 60 kPa, enquanto a absoluta vale 100 + 60 = 160 kPa.')+p('A resposta de 60 kPa não está “errada” por si só: ela responde a outra pergunta. Nomear a referência da pressão faz parte da solução.'))+
 steps(['Circule o que o problema pede: diferença, manométrica ou absoluta.','Marque a pressão conhecida na superfície ou em outro ponto.','Percorra verticalmente cada fluido, somando ao descer e subtraindo ao subir.','Converta Pa e kPa com cuidado: 1 kPa = 1.000 Pa.','Confira se a pressão absoluta aumentou ao descer em um líquido.']))}
);

const pa=lessons.find(x=>x.id==='pascal-arquimedes');
pa.slides.splice(1,0,
 {label:'Mapa de forças',title:'Como representar forças em fluidos',subtitle:'O desenho correto vem antes da equação.',html:page('Pascal e Arquimedes tratam de efeitos diferentes da pressão. Para não misturá-los, separe o sistema hidráulico do corpo imerso e desenhe as forças que atuam no objeto escolhido.',
 h('Escolha o corpo analisado',p('Numa prensa, podemos analisar cada êmbolo. A força externa aplicada ao primeiro produz um acréscimo de pressão no fluido; esse acréscimo atua sobre o segundo. Num problema de flutuação, analisamos o corpo: peso para baixo, empuxo para cima e, quando existirem, tração ou força normal.')+p('Uma seta não representa “movimento”. Ela representa uma força. Um corpo pode estar parado sob várias forças, desde que a soma vetorial seja nula. Também pode estar descendo enquanto a resultante aponta para cima, se estiver desacelerando.'))+
 h('Pressão é o elo',p('Forças de pressão atuam perpendicularmente às superfícies. Em um fluido confinado, uma variação de pressão pode ligar dois êmbolos. Em torno de um corpo imerso, a diferença entre as pressões de baixo e de cima produz a resultante chamada empuxo.'))+
 steps(['Escolha um único corpo ou êmbolo.','Desenhe peso, empuxo, tração, normal e forças externas que realmente atuam nele.','Defina um sentido positivo.','Escreva a soma das forças nesse eixo.','Só então use Pascal ou Arquimedes para calcular uma força desconhecida.']))},
 {label:'Prensa passo a passo',title:'Como uma prensa hidráulica multiplica a força',subtitle:'A força cresce; a energia continua obedecendo ao balanço.',html:page('A prensa não transmite a mesma força de um lado ao outro. Ela transmite um acréscimo de pressão. Como força é pressão multiplicada pela área, o êmbolo maior recebe uma força maior.',
 h('Da entrada à saída',p('Se uma força de 80 N atua sobre 5 cm², a pressão acrescentada é 16 N/cm², equivalente a 160 kPa. Num êmbolo de 100 cm², a mesma variação de pressão produz 1.600 N. Usar cm² nos dois lados é permitido na proporção porque as unidades de área se cancelam.')+formula('F<sub>1</sub>/A<sub>1</sub> = F<sub>2</sub>/A<sub>2</sub>'))+
 h('O preço do ganho de força',p('O fluido que sai debaixo do êmbolo pequeno precisa ocupar espaço sob o grande. Se a área de saída é vinte vezes maior, seu percurso é vinte vezes menor. No exemplo ideal, empurrar o primeiro êmbolo 10 cm faz o segundo subir apenas 0,5 cm.')+formula('A<sub>1</sub>d<sub>1</sub> = A<sub>2</sub>d<sub>2</sub>')+p('O trabalho ideal permanece 80 N × 0,10 m = 1.600 N × 0,005 m = 8 J. Uma máquina real exige trabalho adicional por causa de atrito, deformações e perdas.'))+
 steps(['Calcule a razão entre as áreas, lembrando que A = πr² quando forem dados raios.','Use a igualdade das variações de pressão para obter a força.','Use a conservação de volume para obter o percurso.','Converta centímetros para metros antes de calcular trabalho em joules.','Compare entrada e saída e identifique as perdas se o sistema não for ideal.']))},
 {label:'Empuxo passo a passo',title:'Como nasce o empuxo',subtitle:'A força para cima vem da diferença de pressão.',html:page('O empuxo não é uma força misteriosa acrescentada ao problema. Ele é a resultante das forças de pressão exercidas pelo fluido sobre toda a superfície do corpo.',
 h('Por que a resultante aponta para cima?',p('As partes laterais recebem forças que, num fluido em repouso e numa geometria simétrica, cancelam-se horizontalmente. A parte inferior está mais profunda que a superior e recebe maior pressão. Essa diferença produz uma resultante vertical para cima. O teorema de Arquimedes mostra que seu módulo é igual ao peso do fluido deslocado.')+formula('E = ρ<sub>fluido</sub> g V<sub>deslocado</sub>'))+
 h('O volume correto',p('Se o corpo está totalmente imerso, o volume deslocado é o volume externo inteiro. Se flutua parcialmente, conta apenas a parte abaixo da superfície. Uma cavidade fechada participa do volume externo e pode reduzir a densidade média do conjunto, razão pela qual um casco de aço pode flutuar.')+p('A densidade usada no cálculo do empuxo é a do fluido. A densidade do corpo aparece quando calculamos sua massa ou seu peso. Misturar essas duas densidades é uma das causas mais comuns de erro.'))+
 steps(['Converta o volume para m³: 1 L = 10⁻³ m³.','Use a densidade do fluido em E = ρgV.','Calcule o peso do corpo separadamente.','Compare E e P para prever a tendência inicial.','Acrescente tração ou normal quando o corpo estiver preso ou apoiado.']))},
 {label:'Flutuação guiada',title:'Como decidir se um corpo sobe, afunda ou flutua',subtitle:'Compare forças e acompanhe como o volume submerso muda.',html:page('A primeira tendência depende da resultante. O estado final depende de como o empuxo muda durante o movimento e de quais vínculos aparecem.',
 h('Corpo menos denso que o fluido',p('Quando está totalmente imerso, ele desloca fluido suficiente para que o empuxo exceda seu peso. A resultante aponta para cima. Ao emergir, o volume submerso diminui, o empuxo também diminui e o corpo encontra uma posição em que E = P. Para um corpo homogêneo flutuando, a fração submersa iguala a razão entre as densidades.'))+
 h('Corpo mais denso que o fluido',p('Mesmo totalmente imerso, seu peso supera o empuxo máximo correspondente ao seu volume. Ele acelera para baixo até que o arrasto, um fio ou o fundo altere o balanço. Apoiado no fundo, a força normal pode completar o equilíbrio: P = E + N, se o fluido continuar atuando sob o corpo conforme o modelo adotado.'))+
 h('Densidades iguais',p('Com o corpo totalmente imerso, E e P podem se igualar em qualquer profundidade num fluido homogêneo incompressível. Chamamos isso de equilíbrio indiferente no modelo ideal. Pequenas diferenças de densidade, bolhas e correntes tornam a situação real mais delicada.'))+
 steps(['Preveja a tendência comparando as densidades médias.','Calcule P e o empuxo máximo totalmente imerso.','Observe se o volume submerso pode se ajustar durante a subida.','Inclua vínculos como fio ou apoio.','Diferencie tendência inicial, movimento transitório e equilíbrio final.']))}
);

const dil=lessons.find(x=>x.id==='dilatacao');
dil.slides.splice(1,0,
 {label:'Base térmica',title:'Temperatura, calor e equilíbrio térmico',subtitle:'Três ideias que precisam ficar separadas.',html:page('Para compreender dilatação, primeiro precisamos saber o que a temperatura informa e o que significa transferir energia entre corpos.',
 h('Temperatura não é quantidade de calor',p('Temperatura caracteriza o estado térmico e ajuda a prever o sentido espontâneo da transferência de energia: em contato térmico, energia passa do corpo de maior temperatura para o de menor temperatura até o equilíbrio. Calor é o nome dessa energia enquanto está sendo transferida por diferença de temperatura; não é uma substância guardada dentro do corpo.')+p('Dois objetos podem ter a mesma temperatura e energias internas muito diferentes. Uma banheira e um copo de água a 40 °C estão no mesmo estado térmico quanto à temperatura, mas contêm quantidades diferentes de matéria e, em geral, diferentes energias internas.'))+
 h('O modelo microscópico',p('Num sólido cristalino, os constituintes oscilam em torno de posições de equilíbrio. Ao aquecer, a distribuição de energias muda. Como o potencial de interação real não é perfeitamente simétrico, o afastamento médio pode aumentar. As partículas não incham; muda a distância média entre elas.')+p('A animação amplia movimento e espaçamento para torná-los visíveis. Ela não representa trajetórias atômicas medidas e deixa de ser adequada perto de mudanças de fase ou em regimes quânticos extremos.'))+
 steps(['Identifique os estados inicial e final.','Calcule ΔT = Tfinal − Tinicial.','Use kelvin ou Celsius de modo coerente; variações têm o mesmo valor numérico.','Verifique se houve mudança de fase, pois a temperatura pode permanecer constante durante a transferência de energia.','Interprete a dilatação como resposta macroscópica, sem dizer que as partículas cresceram.']))},
 {label:'Coeficientes',title:'Como interpretar o coeficiente de dilatação',subtitle:'O coeficiente informa a sensibilidade do material.',html:page('O coeficiente α não é o alongamento pronto. Ele informa a variação relativa de comprimento por unidade de temperatura, dentro do intervalo em que podemos tratá-lo como constante.',
 h('Lendo a unidade',p('Para o aço, α ≈ 12 × 10⁻⁶ °C⁻¹ significa que cada metro varia cerca de 12 micrômetros para uma mudança de 1 °C. Uma barra maior varia mais porque há mais comprimento inicial; uma variação térmica maior também produz uma mudança maior.')+formula('ΔL/L<sub>0</sub> = αΔT'))+
 h('Sinal e referência',p('Se ΔT é positivo e α positivo, ocorre expansão. Se ΔT é negativo, ocorre contração. A expressão calcula ΔL, e não o comprimento final. Depois de encontrar a variação, use Lfinal = L0 + ΔL. O sinal negativo já faz a subtração no resfriamento.')+p('Coeficientes tabelados são aproximações para faixas de temperatura e materiais específicos. Ligas, direção cristalográfica e tratamentos mecânicos podem alterar o comportamento. Em exercícios escolares, o valor fornecido deve ser usado sob as hipóteses indicadas.'))+
 steps(['Anote L0, T0 e Tfinal.','Calcule ΔT com sinal.','Leia α e sua potência de dez.','Calcule ΔL e converta a unidade apenas ao final.','Some ΔL a L0 e confira se aquecimento ou resfriamento produziu o sentido esperado.']))},
 {label:'Expansão impedida',title:'O que acontece quando a dilatação é impedida',subtitle:'A ausência de movimento não significa ausência de efeito térmico.',html:page('Uma barra livre muda de comprimento ao variar a temperatura. Se apoios rígidos impedem essa mudança, as partes do material interagem para contrariar a deformação térmica e surgem esforços internos.',
 h('Dilatação livre e deformação real',p('A expressão ΔL = L0αΔT informa quanto a barra variaria se estivesse livre. Quando o comprimento é mantido, essa deformação térmica não aparece como deslocamento externo. Em vez disso, surge tensão mecânica, cujo cálculo exige propriedades como módulo de Young, área, regime elástico e detalhes dos apoios.')+p('Por isso, o laboratório mostra a dilatação livre calculada mesmo quando mantém a barra com o comprimento original. Ele não atribui um valor numérico à tensão sem os dados necessários. Essa distinção é essencial em pontes, trilhos, tubulações e estruturas.'))+
 h('Folgas e juntas',p('Uma junta de dilatação oferece espaço para o movimento térmico previsto. Seu projeto considera faixa de temperatura, comprimento dos trechos, materiais, carregamentos e tolerâncias. A presença de uma junta não elimina todas as tensões; ela é parte de uma solução de engenharia mais ampla.'))+
 steps(['Calcule primeiro a variação livre.','Pergunte se o corpo pode realmente se mover.','Se houver restrição, identifique os apoios e propriedades mecânicas disponíveis.','Não trate ΔL = 0 como prova de que α ou ΔT são zero.','Separe o modelo didático do dimensionamento seguro de uma estrutura real.']))},
 {label:'Líquido e recipiente',title:'Como separar líquido, recipiente e transbordamento',subtitle:'O que vemos é a diferença entre duas expansões.',html:page('Quando um frasco cheio é aquecido, líquido e recipiente respondem à temperatura. A quantidade que sobe no gargalo ou transborda não é necessariamente toda a expansão do líquido.',
 h('Três volumes',p('A dilatação real descreve quanto o líquido aumentaria seu volume. A expansão do recipiente descreve quanto sua capacidade interna aumentou. A dilatação aparente é a diferença observável entre essas duas mudanças. Se o recipiente estava cheio e a diferença é positiva, ela corresponde ao volume derramado no modelo sem evaporação.')+formula('ΔV<sub>aparente</sub> = ΔV<sub>real</sub> − ΔV<sub>recipiente</sub>'))+
 h('Um exemplo narrado',p('Um frasco contém inicialmente 1.000 mL. O líquido aumenta 9 mL, mas a capacidade do frasco aumenta 3 mL. Dos 9 mL adicionais, 3 mL cabem no espaço novo criado pelo recipiente; os 6 mL restantes transbordam. Dizer que o líquido “dilatou apenas 6 mL” seria confundir expansão real com aparente.')+p('Se o frasco não começou cheio, ainda existe um volume livre inicial. Nesse caso, pode haver dilatação aparente positiva sem transbordamento. Primeiro compare a diferença de expansões com o espaço disponível.'))+
 steps(['Confirme se recipiente e líquido começam à mesma temperatura.','Calcule a expansão real do líquido.','Calcule o aumento da capacidade do recipiente.','Subtraia para obter a mudança aparente.','Considere o espaço livre inicial antes de concluir que houve derramamento.']))},
 {label:'Resolver dilatação',title:'Como resolver problemas de dilatação térmica',subtitle:'Escolha a grandeza, controle as unidades e interprete o sinal.',html:page('A maior dificuldade costuma aparecer antes da conta: decidir se o problema trata de comprimento, área, volume real, capacidade ou volume aparente.',
 h('Escolha do modelo',p('Barras, fios e trilhos pedem dilatação linear. Chapas e superfícies pedem dilatação superficial. Corpos tridimensionais e capacidades de recipientes pedem dilatação volumétrica. Em materiais isotrópicos e pequenas variações, β ≈ 2α e γ ≈ 3α, mas use os coeficientes fornecidos quando existirem.')+p('Furos acompanham a expansão da placa. Encaixes exigem observar qual peça deve ficar relativamente maior. Água entre 0 e 4 °C exige o comportamento anômalo, e não um coeficiente positivo constante aplicado sem reflexão.'))+
 h('Controle de plausibilidade',p('Dilatações usuais de sólidos são pequenas. Um resultado de metros para uma barra de poucos metros sob algumas dezenas de graus costuma indicar erro na potência de dez. Em líquidos, compare expansão real e do recipiente; o transbordamento deve ser a diferença, não a soma.'))+
 steps(['Sublinhe a grandeza física solicitada.','Liste estado inicial, estado final e coeficiente apropriado.','Calcule ΔT, preservando o sinal.','Resolva em unidades coerentes e só depois converta.','Escreva uma frase final: expandiu ou contraiu, quanto variou e qual grandeza foi calculada.']))}
);

hydro.time='55–75 min';
pa.time='55–75 min';
dil.time='70–95 min';
})();

/* Sexta edição: bloco 4 em tom de aula guiada. As questões importadas ficam
   reservadas ao bloco 5; estas etapas não reproduzem o banco recebido. */
(()=>{
const lessons=window.MM.lessons;
const p=t=>`<p>${t}</p>`;
const box=(title,body)=>`<aside class="teacher-box"><h3>${title}</h3>${body}</aside>`;
const section=(title,body)=>`<section><h2>${title}</h2>${body}</section>`;
const formula=t=>`<div class="formula">${t}</div>`;
const lesson=(opening,body)=>`<div class="teacher-lesson"><p class="lesson-opening">${opening}</p>${body}</div>`;
const insertAfter=(lessonItem,label,newSlides)=>{const i=lessonItem.slides.findIndex(s=>s.label===label);lessonItem.slides.splice(i+1,0,...newSlides);};

const pa=lessons.find(x=>x.id==='pascal-arquimedes');
insertAfter(pa,'Mapa de forças',[
 {label:'Pascal desde o início',title:'Princípio de Pascal: começando do zero',subtitle:'Primeiro entenda o que acontece com o fluido; depois fazemos a conta.',html:lesson('Imagine uma seringa cheia de água e com a ponta fechada. Quando você empurra o êmbolo, não está mandando uma “porção de força” viajar como um objeto pelo líquido. Você está aumentando a pressão do fluido confinado.',
 section('O que significa confinado?',p('O fluido precisa ocupar uma região fechada, sem uma saída livre por onde ele simplesmente possa escoar. Ao empurrar uma parede móvel, como o êmbolo, você produz uma variação de pressão. Essa variação chega às outras partes do fluido e às paredes do recipiente.')+p('É importante falar em <strong>variação de pressão</strong>. Se dois pontos estiverem em alturas diferentes, a pressão total também inclui o efeito da coluna de líquido entre eles. Nos problemas escolares de prensa hidráulica, os êmbolos costumam ser tratados na mesma altura justamente para que possamos concentrar a atenção no efeito de Pascal.'))+
 section('Pressão igual, força diferente',p('A relação básica é p = F/A. Se a mesma variação de pressão atua em dois êmbolos, a força em cada um depende da área. No êmbolo maior, a mesma pressão atua sobre uma área maior e produz uma força maior.')+formula('Δp = F<sub>1</sub>/A<sub>1</sub> = F<sub>2</sub>/A<sub>2</sub>')+p('Isso não quer dizer que a máquina criou energia. Por enquanto, guarde apenas esta ideia: a pressão se mantém; a força muda porque a área mudou. Na etapa seguinte, vamos acompanhar também os deslocamentos.'))+
 box('Pare e confira',p('Se dois êmbolos tiverem a mesma área, a força ideal de saída será igual à força de entrada. Se a área de saída for cinco vezes maior, a força ideal de saída será cinco vezes maior.')))},
 {label:'Prensa com números',title:'Prensa hidráulica: uma conta explicada devagar',subtitle:'Vamos acompanhar unidades, razão entre áreas e significado do resultado.',html:lesson('Considere uma prensa ideal com um êmbolo pequeno de 5 cm² e um êmbolo grande de 100 cm². Uma pessoa aplica 80 N no êmbolo pequeno. Queremos descobrir a força que o êmbolo grande pode exercer.',
 section('Primeiro: compare as áreas',p('A área maior é 100/5 = 20 vezes a área menor. Antes mesmo de usar a fórmula, já podemos prever o resultado: a força de saída deverá ser vinte vezes a força de entrada, dentro do modelo ideal.')+p('Como as duas áreas aparecem numa razão, podemos manter cm² neste cálculo. Não precisamos convertê-las para m², pois a unidade se cancela. Isso só funciona porque estamos dividindo uma área pela outra.'))+
 section('Depois: organize a proporção',formula('F<sub>1</sub>/A<sub>1</sub> = F<sub>2</sub>/A<sub>2</sub>')+p('Substituindo os valores: 80/5 = F₂/100. Multiplicando, F₂ = 80 × 100/5 = 1.600 N. A resposta faz sentido porque 1.600 N é vinte vezes 80 N, exatamente como previmos pela razão das áreas.'))+
 section('O que essa resposta quer dizer?',p('Ela é a força ideal disponível no êmbolo maior devido ao acréscimo de pressão. Numa máquina real, atrito, vedação, deformação das peças e outras perdas reduzem a força útil. O cálculo escolar estabelece um limite ideal e permite entender o princípio de funcionamento.'))+
 box('Erro comum',p('Não use a razão dos raios diretamente. Se o raio do segundo êmbolo for três vezes maior, sua área será nove vezes maior, pois A = πr².')))},
 {label:'Volume e percurso',title:'Por que o êmbolo maior se move menos',subtitle:'O fluido que sai de um lado precisa caber no outro.',html:lesson('Agora acompanhe o líquido. Quando o êmbolo pequeno desce, ele desloca um volume. Como tratamos o líquido como incompressível e sem vazamentos, o mesmo volume precisa aparecer sob o êmbolo grande.',
 section('Área vezes deslocamento',p('Um cilindro que se move uma distância d varre o volume A·d. Por isso, na prensa ideal, A₁d₁ = A₂d₂. Se A₂ é vinte vezes A₁, o deslocamento d₂ será vinte vezes menor que d₁.')+formula('A<sub>1</sub>d<sub>1</sub> = A<sub>2</sub>d<sub>2</sub>')+p('No exemplo anterior, se o êmbolo pequeno descer 10 cm, o grande sobe 10/20 = 0,5 cm. Essa é a compensação física do ganho de força.'))+
 section('Força maior, caminho menor',p('O trabalho mecânico, quando força e deslocamento têm a mesma direção, é W = Fd. Na entrada: 80 N × 0,10 m = 8 J. Na saída ideal: 1.600 N × 0,005 m = 8 J. A força ficou maior, mas o deslocamento ficou menor na mesma proporção.')+p('Em uma prensa real, o trabalho de saída é menor que o de entrada. Dizer que existem perdas não invalida Pascal; apenas mostra que o modelo ideal não descreve atrito e dissipação.'))+
 box('Como usar o laboratório',p('Escolha primeiro a razão 1:1, depois 5:1 e 20:1. Em cada caso, observe três coisas ao mesmo tempo: força de saída, percurso de saída e volume deslocado. O volume deve permanecer o mesmo quando a prensa é acionada.')))}
]);

insertAfter(pa,'Empuxo passo a passo',[
 {label:'Arquimedes desde o início',title:'Princípio de Arquimedes: começando do zero',subtitle:'O empuxo aparece porque a pressão não é a mesma em todas as partes do corpo.',html:lesson('Coloque mentalmente um bloco dentro da água. A água empurra todas as faces do bloco, sempre perpendicularmente à superfície. Nas laterais, as forças se compensam. Na parte de baixo, que está mais profunda, a pressão é maior que na parte de cima.',
 section('Da diferença de pressão ao empuxo',p('Essa diferença produz uma força resultante para cima. Chamamos essa força de empuxo. Arquimedes mostrou que seu módulo é igual ao peso do fluido deslocado pelo corpo.')+formula('E = ρ<sub>fluido</sub> g V<sub>deslocado</sub>')+p('Observe o nome de cada grandeza. A densidade é a do <strong>fluido</strong>. O volume é o volume de fluido deslocado, que corresponde ao volume da parte submersa. Se o corpo estiver apenas pela metade na água, não use seu volume total.'))+
 section('Um exemplo simples',p('Um corpo totalmente imerso desloca 2 L de água. Como 2 L = 0,002 m³, com ρ = 1.000 kg/m³ e g = 10 m/s², o empuxo vale 1.000 × 10 × 0,002 = 20 N. Esse resultado independe da massa do corpo. A massa será usada separadamente para calcular o peso e comparar as forças.'))+
 box('Não pule esta pergunta',p('O corpo está totalmente imerso ou apenas parcialmente? Essa decisão define o volume deslocado e pode mudar toda a solução.')))},
 {label:'Diagrama de forças',title:'Flutuação: leia as forças antes de prever o movimento',subtitle:'Peso, empuxo, tração e apoio precisam aparecer no mesmo desenho.',html:lesson('Saber que existe empuxo não basta para afirmar que um corpo sobe. Precisamos comparar todas as forças verticais que atuam nele.',
 section('Corpo livre na água',p('O peso aponta para baixo e o empuxo aponta para cima. Se E > P, a resultante inicial aponta para cima. Se E < P, aponta para baixo. Se E = P, as forças se equilibram. Essa comparação descreve a tendência naquele instante; durante o movimento, o volume submerso e o arrasto podem mudar.'))+
 section('Corpo preso por um fio',p('Se o corpo está totalmente imerso e preso por um fio vindo de cima, a tração aponta para cima. No equilíbrio, T + E = P. O peso do corpo não diminuiu dentro da água. O que diminuiu foi a força que o fio precisa fazer, porque o fluido passou a sustentar uma parte do peso.'))+
 section('Corpo apoiado no fundo',p('Ao tocar o fundo, aparece a força normal. Num modelo em que a água continua em contato com a parte inferior, o equilíbrio pode ser escrito como E + N = P. Situações de vedação ou contato completo exigem mais cuidado, pois a água pode deixar de exercer pressão sob parte do corpo.'))+
 box('Estratégia segura',p('Desenhe o corpo isolado. Coloque uma seta para cada força real. Escolha o sentido positivo e escreva a soma das forças. Só depois substitua E = ρgV.')))}
]);

const dil=lessons.find(x=>x.id==='dilatacao');
insertAfter(dil,'Base térmica',[
 {label:'Escalas de temperatura',title:'Celsius e kelvin sem confusão',subtitle:'Temperatura e variação de temperatura não são a mesma coisa.',html:lesson('A escala Celsius coloca 0 °C e 100 °C em pontos ligados às propriedades da água sob condições definidas. A escala kelvin começa no zero absoluto. Por isso, o mesmo estado recebe números diferentes nas duas escalas.',
 section('Convertendo uma temperatura',p('Para transformar Celsius em kelvin, some 273,15. Assim, 20 °C correspondem a 293,15 K. Para voltar, subtraia 273,15. Kelvin é escrito sem o símbolo de grau: escrevemos 293 K, e não 293 °K.')+formula('T<sub>K</sub> = θ<sub>C</sub> + 273,15'))+
 section('Convertendo uma variação',p('Se a temperatura passa de 20 °C para 50 °C, a variação é 30 °C. Em kelvin, os estados são 293,15 K e 323,15 K; a diferença também é 30 K. O deslocamento de 273,15 aparece nos dois estados e se cancela na subtração.')+p('É por isso que podemos usar uma variação de 30 °C ou 30 K numa fórmula de dilatação, desde que o coeficiente esteja expresso por grau Celsius ou por kelvin. Não some 273,15 à variação.'))+
 box('Duas frases corretas',p('“A temperatura final é 323,15 K.” “A temperatura aumentou 30 K.” A primeira descreve um estado; a segunda descreve uma diferença.')))},
 {label:'Zero absoluto',title:'0 °C não é ausência de agitação térmica',subtitle:'O zero Celsius está muito acima do zero absoluto.',html:lesson('Quando a água está a 0 °C, sua temperatura absoluta é 273,15 K. Ainda existe agitação microscópica. Portanto, zerar o número na escala Celsius não significa retirar toda a energia térmica do sistema.',
 section('O limite de 0 K',p('Zero kelvin corresponde a −273,15 °C. A terceira lei da Termodinâmica estabelece que não se alcança exatamente esse limite por uma sequência finita de processos físicos. Laboratórios conseguem temperaturas extremamente baixas, mas “muito perto” continua sendo diferente de “exatamente zero”.'))+
 section('O cuidado com a explicação quântica',p('Perto desse limite, o modelo clássico de pequenas partículas seguindo trajetórias definidas deixa de ser suficiente. Sistemas quânticos podem apresentar energia de ponto zero no estado fundamental. Isso não deve ser resumido pela frase “Heisenberg obriga a partícula a continuar andando”. O princípio de incerteza trata das dispersões de posição e momento, e a descrição correta depende do sistema quântico considerado.')+p('No laboratório visual, a nuvem em 0 K marca justamente essa mudança de modelo. Ela não é uma filmagem do movimento de um átomo.'))+
 box('Compare no controle',p('Selecione 0 °C e leia o valor em kelvin. Depois selecione 0 K e observe a mensagem de limite. São situações físicas completamente diferentes.')))}
]);

insertAfter(dil,'Coeficientes',[
 {label:'Dilatação com números',title:'Dilatação linear: uma conta explicada devagar',subtitle:'Vamos separar comprimento inicial, variação e comprimento final.',html:lesson('Uma barra de aço tem 2 m a 20 °C. Ela é aquecida até 120 °C. Adote α = 12 × 10⁻⁶ °C⁻¹. Queremos descobrir quanto o comprimento muda.',
 section('Primeiro: encontre a variação térmica',p('A temperatura final é 120 °C e a inicial é 20 °C. Portanto, ΔT = 120 − 20 = 100 °C. Não usamos 120 diretamente na fórmula, porque a dilatação depende da mudança de temperatura a partir do estado inicial.'))+
 section('Depois: calcule a variação de comprimento',formula('ΔL = L<sub>0</sub> α ΔT')+p('Substituindo: ΔL = 2 × 12 × 10⁻⁶ × 100 = 0,0024 m. Como 1 m = 1.000 mm, isso corresponde a 2,4 mm. O resultado é pequeno, o que combina com a ordem de grandeza esperada para um sólido comum nessa faixa.'))+
 section('Por fim: encontre o comprimento final',p('A pergunta pode pedir apenas o alongamento ou o comprimento final. São respostas diferentes. O alongamento é 2,4 mm. O comprimento final é 2 m + 0,0024 m = 2,0024 m.')+p('Se a barra fosse resfriada pela mesma diferença de temperatura, ΔT seria negativo. O cálculo forneceria ΔL negativo, indicando contração.'))+
 box('Conferência rápida',p('A barra foi aquecida e α é positivo. Portanto, o comprimento final precisa ser maior que o inicial. Se sua resposta indicar diminuição, verifique o sinal de ΔT.')))},
 {label:'Área, volume e furos',title:'Dilatação em duas e três dimensões',subtitle:'O material se expande em todas as direções disponíveis.',html:lesson('Uma barra destaca uma dimensão. Uma placa possui comprimento e largura; um bloco ou recipiente possui três dimensões. Quando o material é isotrópico e a dilatação é pequena, podemos relacionar os coeficientes.',
 section('Da linha para a área',p('Se cada lado de uma placa quadrada aumenta aproximadamente na proporção αΔT, a área sente o efeito nas duas direções. Desprezando termos muito pequenos de ordem (αΔT)², obtemos β ≈ 2α.')+formula('ΔA = A<sub>0</sub> βΔT &nbsp; com &nbsp; β ≈ 2α'))+
 section('Da linha para o volume',p('Num sólido tridimensional isotrópico, o efeito aparece nas três direções. Para pequenas dilatações, γ ≈ 3α. Essas aproximações precisam ser usadas com cuidado em materiais anisotrópicos ou em faixas nas quais os coeficientes variam muito.')+formula('ΔV = V<sub>0</sub> γΔT &nbsp; com &nbsp; γ ≈ 3α'))+
 section('O que acontece com um furo?',p('O furo aumenta quando a placa é aquecida uniformemente. Uma forma útil de imaginar isso é preencher mentalmente a abertura com o mesmo material. Esse pedaço imaginário se expandiria junto com o restante da placa; ao retirá-lo novamente, a abertura final estaria maior.'))+
 box('Experimente',p('Na simulação, alterne entre linear, superficial e volumétrica. Compare o contorno inicial tracejado com a forma final e observe que o furo acompanha a expansão da placa.')))}
]);

insertAfter(dil,'Líquido e recipiente',[
 {label:'Transbordamento guiado',title:'Dilatação dos líquidos: acompanhe cada volume',subtitle:'O líquido cresce, mas o recipiente também ganha capacidade.',html:lesson('Considere um frasco de 1.000 mL completamente cheio. Ao aquecer o conjunto, o líquido tenta ocupar mais espaço e o recipiente também se dilata. O que transborda é a diferença entre essas duas mudanças.',
 section('Expansão real do líquido',p('Se γlíquido = 9 × 10⁻⁴ °C⁻¹ e ΔT = 10 °C, então ΔVreal = 1.000 × 9 × 10⁻⁴ × 10 = 9 mL. Esse é todo o aumento de volume do líquido.'))+
 section('Aumento da capacidade',p('Se γrecipiente = 3 × 10⁻⁴ °C⁻¹, a capacidade cresce 1.000 × 3 × 10⁻⁴ × 10 = 3 mL. O frasco aquecido passa a comportar 3 mL a mais que antes.'))+
 section('O volume aparente',p('Dos 9 mL ganhos pelo líquido, 3 mL cabem na nova capacidade. Restam 6 mL, que transbordam. Chamamos essa diferença de dilatação aparente: ΔVaparente = 9 − 3 = 6 mL.')+p('Se o frasco não estivesse cheio no início, seria necessário descontar também o espaço vazio disponível. Dilatação aparente positiva não garante derramamento quando existe folga.'))+
 box('Leia a palavra pedida',p('“Dilatação real” pede o aumento do líquido. “Aumento da capacidade” pede a expansão do recipiente. “Transbordamento” ou “dilatação aparente” pede a diferença, quando o recipiente começa cheio.')))},
 {label:'Água de 0 a 4 °C',title:'A dilatação anômala da água com calma',subtitle:'Nessa pequena faixa, aquecer pode diminuir o volume.',html:lesson('Para a maioria dos líquidos, aquecer aumenta o volume. A água líquida perto do ponto de congelamento exige mais cuidado. Entre 0 °C e aproximadamente 4 °C, aquecer uma massa fixa de água diminui seu volume e aumenta sua densidade.',
 section('O que muda aos 4 °C?',p('Perto de 4 °C, a água líquida atinge densidade máxima e, portanto, volume mínimo para uma massa fixa. Acima dessa temperatura, volta a predominar o comportamento mais comum: aquecer aumenta o volume e diminui a densidade.')+formula('massa fixa: &nbsp; ρ = m/V')+p('Se a massa não muda, densidade e volume variam em sentidos opostos. Quando o volume diminui de 0 a 4 °C, a densidade aumenta. Quando o volume aumenta acima de 4 °C, a densidade diminui.'))+
 section('Por que o gelo flutua?',p('No gelo comum, as ligações de hidrogênio favorecem uma estrutura mais aberta. O mesmo número de moléculas ocupa um volume maior que na água líquida, produzindo menor densidade média. Por isso o gelo flutua.'))+
 section('O que o gráfico está mostrando',p('A variação de densidade entre 0 e 10 °C é pequena. A simulação amplia a escala vertical para que a curva seja visível. Use o controle para localizar a região próxima de 4 °C e acompanhe, ao mesmo tempo, densidade e volume de uma massa fixa.'))+
 box('Evite uma regra exagerada',p('A explicação sobre lagos no inverno é útil, mas não descreve todos os lagos em qualquer situação. Salinidade, vento, circulação e profundidade também influenciam o comportamento real.')))}
]);

pa.time='80–110 min';
dil.time='105–140 min';
})();


