/* Bloco 4 reconstruído: uma sequência única, sem as duplicações das versões anteriores. */
(()=>{
'use strict';
const {lessons,histories,quizzes,report}=window.MM;
const p=t=>`<p>${t}</p>`, f=t=>`<div class="formula">${t}</div>`;
const sec=(t,b)=>`<section class="lesson-block"><h2>${t}</h2>${b}</section>`;
const note=(t,b)=>`<aside class="teacher-box"><h3>${t}</h3>${b}</aside>`;
const transition=(summary,next)=>`<aside class="topic-transition" aria-label="Síntese e mudança de assunto"><span>Mudança de bloco</span><p><strong>Até aqui:</strong> ${summary}</p><p><strong>Agora vamos ver:</strong> ${next}</p></aside>`;
const page=(lead,body,right='')=>`<div class="lesson-flow${right?' has-lab':''}"><div class="lesson-copy"><p class="lesson-opening">${lead}</p>${body}</div>${right}</div>`;
const lab=(id,label)=>`<div class="lab" data-lab="${id}"><div class="lab-head"><span>${label}</span><span>Explore</span></div><div class="lab-body"></div><div class="observation-bar"><span>Observação interativa</span>${report('observação',label)}</div></div>`;
const quiz=id=>`<div class="quiz" data-quiz="${id}"></div>`;
const why=(from,current,to,text)=>({from,current,to,text});
const check=items=>`<div class="thinking-checklist" data-required-checklist><h2>Roteiro de pensamento</h2><p>Marque um item somente depois de conferir que você fez esse passo. A seta para avançar será liberada quando o roteiro estiver completo; o índice continua livre.</p>${items.map((x,i)=>`<label><input type="checkbox" value="${i}"><span class="organic-check" aria-hidden="true"><svg viewBox="0 0 28 28"><path d="M5 14.5l6 6L23 7"/></svg></span><span>${x}</span></label>`).join('')}<p class="checklist-status" role="status"></p></div>`;
const story=(id,title)=>`<a class="story-link" href="#historia/${id}/0" data-story="${id}"><span>História completa neste site</span><strong>${title}</strong><small>Ler sem sair da plataforma</small></a>`;

const pa=lessons.find(x=>x.id==='pascal-arquimedes');
pa.title='Princípios de Pascal e Arquimedes';pa.time='70–95 min';
pa.slides=[
{label:'Linha de raciocínio',title:'Pascal e Arquimedes: o caminho da aula',subtitle:'Duas ideias diferentes que nascem da pressão.',reason:why('Pressão nos fluidos','Transmissão e diferença de pressão','Prensa, empuxo e flutuação','Primeiro veremos como uma mudança de pressão chega ao fluido inteiro. Depois veremos como a pressão maior nas regiões profundas cria o empuxo.'),html:page('Você não precisa começar decorando duas fórmulas. Vamos responder duas perguntas: como um fluido confinado transmite uma mudança de pressão? Por que um fluido empurra um corpo para cima?',sec('Pascal',p('Uma prensa hidráulica liga dois êmbolos por um líquido. Ao empurrar um deles, aumentamos a pressão no líquido. Essa mudança chega ao outro êmbolo. Como a força depende da área, um êmbolo maior pode produzir uma força maior.'))+sec('Arquimedes',p('Um corpo mergulhado recebe pressão por todos os lados. Como a parte de baixo está mais profunda, ela recebe um empurrão maior. A soma dessas forças produz o empuxo.'))+note('Antes de avançar',p('Pressão, força, movimento e equilíbrio não são a mesma coisa. A aula vai separar cada uma dessas ideias.')))},
{label:'Princípio de Pascal',title:'Princípio de Pascal',subtitle:'O fluido recebe uma mudança de pressão.',reason:why('p = F/A','Mesmo acréscimo de pressão','Forças diferentes','Esta página explica por que uma prensa pode ligar uma força pequena a uma força maior.'),html:page('Imagine uma seringa cheia de água e com a saída fechada. Quando você empurra o êmbolo, o líquido não tem por onde escapar. O que aumenta é a pressão dentro da seringa.',sec('O que se transmite?',p('Transmite-se a <strong>variação de pressão</strong>. Se acrescentamos pressão em uma parte de um fluido confinado e em equilíbrio, esse acréscimo chega às outras partes do fluido e às paredes.')+f('Δp<sub>1</sub> = Δp<sub>2</sub>')+p('Falamos em variação porque a pressão total também pode mudar com a altura. Nas prensas escolares, os êmbolos costumam estar na mesma altura para que possamos observar apenas o efeito de Pascal.'))+sec('Pressão igual, força diferente',p('Pressão é força dividida pela área. A mesma pressão produz uma força maior quando atua numa área maior.'))+note('Na observação interativa',p('Use “Mostrar propagação da pressão”. O pulso luminoso representa a chegada da variação de pressão a todo o fluido e às paredes. Ele não representa uma corrente de água transportando pressão.')),lab('pascal','Veja a pressão chegar aos dois êmbolos'))},
{label:'Prensa hidráulica',title:'Prensa hidráulica: força e área',subtitle:'Uma conta explicada sem pular etapas.',reason:why('Pascal','F₁/A₁ = F₂/A₂','Vantagem de força','As questões muitas vezes escondem a razão de áreas em raios ou diâmetros.'),html:page('Considere um êmbolo de 5 cm² ligado a outro de 100 cm². Aplicamos 80 N no menor. Antes da conta, compare as áreas: a saída é vinte vezes maior. Então já esperamos uma força vinte vezes maior.',sec('Monte a proporção',f('F<sub>1</sub>/A<sub>1</sub> = F<sub>2</sub>/A<sub>2</sub>')+p('Substituindo: 80/5 = F₂/100. Assim, F₂ = 80 × 100/5 = 1.600 N. O resultado confirma a previsão: 1.600 é vinte vezes 80.'))+sec('Quando aparecem raios',p('Se o enunciado fornece o raio, calcule A = πr². Um raio três vezes maior produz uma área nove vezes maior. Usar apenas a razão dos raios é uma pegadinha frequente.'))+note('Unidades',p('Na razão entre duas áreas, cm² pode aparecer dos dois lados e se cancelar. Para calcular pressão em pascal, a área deve estar em m².')))},
{label:'Volume e trabalho',title:'Por que o êmbolo maior anda menos',subtitle:'A máquina troca caminho por força.',reason:why('Força maior','Mesmo volume deslocado','Percurso menor','Esta etapa evita a conclusão errada de que a prensa cria energia.'),html:page('Quando o êmbolo pequeno desce, ele desloca um volume. Como o líquido é tratado como incompressível e não há vazamento, o mesmo volume precisa aparecer no outro lado.',sec('Conservação de volume',f('A<sub>1</sub>d<sub>1</sub> = A<sub>2</sub>d<sub>2</sub>')+p('Se a saída tem área vinte vezes maior, ela percorre uma distância vinte vezes menor. Dez centímetros na entrada produzem apenas 0,5 cm na saída.'))+sec('Trabalho ideal',p('Entrada: 80 N × 0,10 m = 8 J. Saída: 1.600 N × 0,005 m = 8 J. A força aumentou e o percurso diminuiu na mesma proporção. Máquinas reais ainda têm perdas por atrito e deformação.'))+note('Observe no laboratório',p('Compare 1:1, 5:1 e 20:1. A força e o percurso mudam em sentidos opostos; o volume deslocado permanece igual.')),lab('pascal','Força, percurso e volume'))},
{label:'Aplicações de Pascal',title:'Onde o princípio de Pascal aparece',subtitle:'Freios, elevadores e prensas usam a mesma ideia.',reason:why('Pressão transmitida','Sistema hidráulico','Aplicar força a distância','Reconhecer o mecanismo vale mais que memorizar uma lista.'),html:page('Num freio hidráulico, o pedal ajuda a pressionar o fluido. A mudança de pressão chega aos mecanismos próximos das rodas, que exercem força sobre discos ou tambores.',sec('Elevadores e prensas',p('Uma força aplicada a um êmbolo menor pode sustentar uma carga maior no êmbolo de saída. A carga sobe uma distância menor, enquanto a entrada percorre uma distância maior ou recebe várias ações de bombeamento.'))+note('Pergunta para reconhecer Pascal',p('Existe um fluido confinado recebendo uma mudança de pressão? Essa mudança atua em outra área? Se sim, Pascal provavelmente organiza o problema.')))},
{label:'Princípio de Arquimedes',title:'Princípio de Arquimedes',subtitle:'A diferença de pressão produz o empuxo.',reason:why('Pressão aumenta com a profundidade','Base recebe pressão maior','Empuxo para cima','Esta página liga hidrostática ao comportamento de corpos mergulhados.'),html:page('Imagine um bloco dentro da água. A água empurra todas as superfícies. Nas laterais, as forças opostas se equilibram. Embaixo, a pressão é maior que em cima porque a base está mais profunda.',sec('A força resultante',p('Quando somamos as forças de pressão, sobra uma força para cima: o empuxo. Seu valor é igual ao peso do fluido deslocado.')+f('E = ρ<sub>fluido</sub> g V<sub>deslocado</sub>'))+sec('Leia os símbolos',p('A densidade é a do <strong>fluido</strong>. O volume é o da parte mergulhada. Se o corpo está totalmente imerso, usamos todo o volume externo; se está parcialmente imerso, usamos somente a parte abaixo da superfície.'))+note('Pergunta indispensável',p('O corpo está totalmente ou parcialmente imerso? Responda isso antes de substituir números.')),lab('buoyancy','Veja peso, empuxo e resultante'))},
{label:'Empuxo com números',title:'Empuxo: uma conta comentada',subtitle:'Litros precisam virar metros cúbicos.',reason:why('Volume deslocado','Peso do fluido','Empuxo','A conversão de litros costuma decidir a questão.'),html:page('Um corpo totalmente imerso desloca 2 L de água. Adote ρ = 1.000 kg/m³ e g = 10 m/s².',sec('Converta primeiro',p('1 L = 10⁻³ m³. Então, 2 L = 0,002 m³.'))+sec('Calcule',f('E = 1.000 × 10 × 0,002 = 20 N')+p('A água exerce 20 N para cima. Ainda não sabemos se o corpo sobe: precisamos comparar com o peso e com outras forças.'))+note('Dê dimensão ao número',p('Com g ≈ 10 m/s², 20 N correspondem aproximadamente ao peso de uma massa de 2 kg. Essa comparação ajuda a conferir a ordem de grandeza.')))},
{label:'Flutuação',title:'Como prever se o corpo sobe ou afunda',subtitle:'Ter empuxo não significa necessariamente subir.',reason:why('Calcular P e E','Comparar forças','Prever a tendência','Questões tentam induzir “há empuxo, então sobe”. A comparação é indispensável.'),html:page('Num corpo livre, o peso aponta para baixo e o empuxo para cima. Se E > P, a tendência é subir; se E < P, afundar; se E = P, as forças se equilibram.',sec('Como aparece a flutuação',p('Um corpo menos denso sobe. Quando começa a sair da água, o volume mergulhado diminui, o empuxo também diminui e o corpo encontra uma posição em que E = P.'))+sec('Por que um navio de aço flutua?',p('O casco contém grande volume de ar. A densidade média do conjunto — massa total dividida pelo volume externo — pode ficar menor que a da água.'))+note('Preveja antes de soltar',p('Escolha “Flutua”, “Equilíbrio” e “Afunda”. Diga o sentido da resultante antes de apertar o botão.')),lab('buoyancy','Compare três regimes'))},
{label:'Peso aparente',title:'Peso aparente e leitura do dinamômetro',subtitle:'O peso gravitacional continua existindo; muda quanto o instrumento precisa sustentar.',reason:why('Peso e empuxo','Leitura do instrumento','Peso aparente','Esta etapa prepara problemas com dinamômetro, balança e corpos mergulhados.'),html:page('Quando um corpo é suspenso por um dinamômetro e mergulhado, o instrumento não precisa sustentar sozinho todo o peso: a água exerce empuxo para cima.',sec('Peso aparente',f('P<sub>ap</sub> = P − E')+p('Se P = 30 N e E = 20 N, o dinamômetro marca 10 N. Essa leitura é o <strong>peso aparente</strong>. O peso gravitacional continua sendo 30 N; a água sustenta os 20 N restantes.')+p('No diagrama de forças, a força exercida pelo fio ainda pode ser chamada de tração T. No equilíbrio, sua intensidade coincide com P<sub>ap</sub>.'))+sec('Uma pessoa dentro da piscina',p('Sustentar um amigo fora da água exige mais força do que sustentá-lo parcialmente mergulhado. A massa da pessoa não mudou: o empuxo diminuiu a parcela que seus braços precisam sustentar. Carregá-la nas costas ou nos braços também muda postura e torque; por isso essa comparação só representa peso aparente quando comparamos fora e dentro da água.'))+sec('A bola empurrada para baixo',p('Com apenas a ponta da bola mergulhada, o volume deslocado e o empuxo são pequenos. Com metade mergulhada, o empuxo aumenta. Totalmente submersa, a bola desloca seu volume inteiro e recebe o maior empuxo possível nesse modelo. Ao soltá-la, a subida inicial tende a ser mais intensa. A altura alcançada também depende de resistência da água, deformação e modo de soltura.'))+sec('Corpo apoiado',p('Ao tocar o fundo, surge a força normal. Num modelo com água sob o corpo, P = E + N. Uma vedação completa na base mudaria a distribuição de pressão e exigiria outra análise.'))+note('Desenhe antes',p('Isole o corpo e coloque uma seta para cada força real. Depois identifique qual força o instrumento mede e qual valor chamamos de peso aparente.')))},
{label:'Roteiro de pensamento',title:'Roteiro de pensamento: Pascal e Arquimedes',subtitle:'Confira o método antes dos exercícios.',reason:why('Conceitos da aula','Organizar os passos','Resolver sem adivinhar','A lista transforma as ideias num procedimento que você pode repetir.'),html:page('Leia cada item e tente explicá-lo com suas palavras antes de marcar.',check(['Identifiquei se o problema trata de pressão transmitida, empuxo ou dos dois.','Escolhi o corpo ou êmbolo analisado e desenhei as forças.','Verifiquei se foram fornecidas áreas, raios ou diâmetros.','Decidi qual volume está mergulhado e converti litros para m³ quando necessário.','Fiz uma previsão: a resposta deveria aumentar, diminuir, subir ou descer?','Comparei a ordem de grandeza com uma situação conhecida.']))},
{label:'Exercício de Pascal',title:'Exercício: prensa hidráulica',subtitle:'Resolva e avalie o tamanho da resposta.',reason:why('Pascal e áreas','Aplicar a proporção','Julgar o resultado','A questão verifica se a razão entre áreas foi usada na direção correta.'),html:page('Antes de calcular, preveja: como a área de saída é maior, a força de saída deve superar a entrada.',quiz('press'))},
{label:'Exercício de Arquimedes',title:'Exercício: empuxo e tração',subtitle:'Separe peso, empuxo e leitura do dinamômetro.',reason:why('Empuxo','Equilíbrio','Tração','A questão verifica se você entende que o peso continua existindo.'),html:page('Desenhe três setas: peso para baixo, empuxo e tração para cima.',quiz('buoy'))},
{label:'Síntese',title:'Pascal e Arquimedes: síntese',subtitle:'Duas respostas diferentes para a pressão.',reason:why('Pressão','Transmissão ou diferença','Máquinas e flutuação','As duas ideias vêm da pressão, mas não dizem a mesma coisa.'),html:page('Pascal explica como uma mudança de pressão se transmite num fluido confinado. Arquimedes explica a resultante que aparece quando a pressão varia ao redor de um corpo.',sec('Pascal',f('F<sub>1</sub>/A<sub>1</sub> = F<sub>2</sub>/A<sub>2</sub>')+p('Área maior permite força maior e percurso menor.'))+sec('Arquimedes',f('E = ρ<sub>fluido</sub> g V<sub>deslocado</sub>')+p('Compare empuxo com peso, tração e apoio.'))+story('arquimedes-pascal','Arquimedes e Pascal'))}
];

const dil=lessons.find(x=>x.id==='dilatacao');
dil.title='Dilatação térmica dos sólidos e líquidos';dil.time='85–115 min';
dil.slides=[
{label:'Linha de raciocínio',title:'Dilatação térmica: o caminho da aula',subtitle:'Da temperatura às mudanças de comprimento, área e volume.',reason:why('Temperatura muda','Distâncias médias mudam','Dimensões respondem','Começamos no modelo microscópico, passamos pelas três dimensões e terminamos em líquidos e água.'),html:page('O objetivo é entender por que aquecer ou resfriar pode mudar as dimensões de um corpo e como escolher a relação certa em cada situação.',sec('Sólidos',p('Começaremos pela dilatação linear. Depois usaremos a mesma estrutura para área e volume. O ponto de atenção será escolher α, β ou γ conforme a dimensão pedida.'))+sec('Líquidos',p('Depois, separaremos o aumento real do líquido, o aumento da capacidade do recipiente e aquilo que vemos como transbordamento.'))+sec('Água',p('Por fim, veremos por que a água entre 0 °C e 4 °C não segue a regra simples que esperaríamos e como isso se relaciona ao congelamento de lagos.')))},
{label:'Temperatura e agitação',title:'Temperatura e agitação térmica',subtitle:'As partículas não aumentam de tamanho.',reason:why('Aquecer ou resfriar','Agitação e distância média','Dilatação ou contração','Precisamos desta imagem antes de escrever qualquer fórmula.'),html:page('Num sólido, os átomos permanecem ligados aos vizinhos e oscilam em torno de posições de equilíbrio. Quando a temperatura muda, a agitação térmica também muda.',sec('O que cresce?',p('As partículas não incham. Em muitos materiais, aumenta a distância média entre elas. Uma mudança microscópica muito pequena, repetida ao longo do corpo, aparece como mudança de comprimento, área ou volume.'))+sec('Um modelo visual',p('A animação aumenta muito os movimentos e afastamentos para que possamos enxergá-los. Ela ajuda a construir a ideia, mas não é uma filmagem de átomos reais.')),lab('particles','Compare temperatura e agitação'))},
{label:'Celsius e kelvin',title:'Celsius e kelvin',subtitle:'Temperatura e variação não são a mesma coisa.',reason:why('Dois estados','Subtrair final − inicial','Obter ΔT','Questões confundem a temperatura em kelvin com a variação, que tem o mesmo tamanho em °C e K.'),html:page('O mesmo estado pode ser escrito como 20 °C ou 293,15 K. Para transformar uma temperatura Celsius em kelvin, somamos 273,15.',sec('Temperatura',f('T<sub>K</sub> = θ<sub>C</sub> + 273,15')+p('Kelvin não usa o símbolo de grau: escrevemos 293 K, não 293 °K.'))+sec('Variação',p('De 20 °C para 50 °C, ΔT = 30 °C. Em kelvin, vamos de 293,15 K para 323,15 K: a diferença também é 30 K. Não some 273,15 a uma variação.'))+note('0 °C não é 0 K',p('0 °C é igual a 273,15 K e ainda existe agitação térmica. 0 K é o limite inferior da escala. Quanto mais o sistema esfria, mais difícil fica retirar o restante da energia térmica; conseguimos chegar muito perto, mas não exatamente ao limite. A curiosidade explica o aprofundamento sem transformá-lo em requisito.')))},
{label:'Dilatação linear',title:'Dilatação linear',subtitle:'Primeiro calculamos a mudança de comprimento.',reason:why('L₀ e ΔT','Coeficiente α','ΔL','Esta é a base que reaparece nas outras dimensões.'),html:page('Imagine uma barra sendo aquecida. Agora vamos olhar só para o comprimento dela. Para calcular essa mudança, usamos o coeficiente linear α.',sec('A relação',f('ΔL = L<sub>0</sub> α ΔT')+p('L₀ é o comprimento inicial. α informa quanto o material varia por unidade de comprimento e temperatura. ΔT é Tfinal − Tinicial. ΔL é a mudança, não o comprimento final.'))+sec('Exemplo',p('Uma barra de aço de 2 m vai de 20 °C a 120 °C. Com α = 12 × 10⁻⁶ °C⁻¹, ΔT = 100 °C e ΔL = 2 × 12 × 10⁻⁶ × 100 = 0,0024 m = 2,4 mm. O comprimento final é 2,0024 m.'))+note('O número faz sentido?',p('Alguns milímetros para uma barra de metros é plausível. Um resultado de vários metros deveria fazer você revisar a potência de dez.')),lab('bar','Compare materiais'))},
{label:'Uma, duas e três dimensões',title:'Dilatação em uma, duas e três dimensões',subtitle:'Clique numa dimensão e veja a mesma estrutura reaparecer.',reason:why('ΔL com α','ΔA com β / ΔV com γ','Escolher o coeficiente certo','Esta página existe porque muitas questões fornecem o coeficiente linear e pedem uma variação de área ou volume.'),tabs:[{name:'Linear',formula:'ΔL = L₀ α ΔT',text:'Imagine uma barra. Acompanhamos uma direção: o comprimento. Por isso usamos L e α.'},{name:'Superficial',formula:'ΔA = A₀ β ΔT',text:'Olhe uma placa quadrada de frente. Ela cresce no comprimento e na largura. A área sente duas direções; para pequenas dilatações em material isotrópico, β ≈ 2α.'},{name:'Volumétrica',formula:'ΔV = V₀ γ ΔT',text:'Imagine um bloco em perspectiva. Ele cresce em comprimento, largura e altura. O volume sente três direções; nas mesmas condições, γ ≈ 3α.'}],html:page('As três expressões têm a mesma forma. Muda a grandeza observada, o valor inicial e o coeficiente.',`<div class="dimension-explorer" data-dimension-tabs></div>`+sec('A estrutura',f('variação = valor inicial × coeficiente × ΔT')+p('Se a questão fornece α e pede volume, não coloque α diretamente na expressão volumétrica: use γ ≈ 3α nas condições deste capítulo. Para área, use β ≈ 2α. É uma pegadinha recorrente nas questões.'))+note('Como olhar a placa',p('Para estudar a área, olhe a placa de frente, enxergando comprimento e largura. Vista de lado, ela pareceria uma linha e esconderia a segunda direção.')),lab('dimensions','Troque a dimensão'))},
{label:'Furos e encaixes',title:'Furos e encaixes também dilatam',subtitle:'O vazio acompanha o movimento das bordas.',reason:why('Placa se expande','Bordas se afastam','Furo aumenta','Questões usam furos para testar a imagem mental do estudante.'),html:page('Quando uma placa furada é aquecida uniformemente, o furo aumenta. Ele não fecha porque existe mais material ao redor.',sec('Uma imagem útil',p('Imagine o furo preenchido pelo mesmo material. Esse disco imaginário aumentaria junto com a placa. Ao retirá-lo novamente, sobra uma abertura maior.'))+sec('Encaixes',p('Podemos aquecer a peça externa para aumentar o furo ou resfriar a peça interna para diminuí-la. A primeira pergunta deve ser: qual objeto precisa ficar relativamente maior?'))+note('Ideia central',p('No modelo uniforme, todas as distâncias do material são multiplicadas pelo mesmo fator. O contorno interno participa dessa geometria.')))},
{label:'Expansão impedida',title:'Quando a barra não pode dilatar',subtitle:'Não se mover não significa que o calor não teve efeito.',reason:why('Barra tentaria variar ΔL','Apoios impedem','Surge esforço interno','Esta etapa explica por que estruturas precisam de folgas e juntas.'),html:page('A expressão calcula quanto a barra mudaria se estivesse livre. Se apoios rígidos impedem essa mudança, o comprimento pode permanecer igual, mas aparecem esforços internos.',sec('O que sabemos calcular?',p('Com L₀, α e ΔT, calculamos a dilatação livre. Para calcular a tensão da restrição, precisaríamos de propriedades mecânicas e detalhes dos apoios. Sem esses dados, não devemos inventar um valor.'))+sec('Juntas de dilatação',p('Pontes, trilhos e tubulações precisam acomodar mudanças térmicas. Folgas e juntas fazem parte de um projeto que também considera materiais, cargas e segurança.'))+note('Experimente',p('Use “Impedir expansão”. O laboratório mantém o comprimento e mostra quanto a barra tentaria variar.')),lab('bar','Livre ou impedida'))},
{label:'Lâminas bimetálicas',title:'Lâminas bimetálicas',subtitle:'Dois metais unidos não conseguem se dilatar separadamente.',reason:why('Coeficientes diferentes','Comprimentos livres diferentes','A lâmina se curva','Cinco questões do banco usam essa ideia; o estudante precisa construí-la antes de praticar.'),html:page('Imagine duas tiras de metais diferentes, com o mesmo comprimento, presas uma à outra. Ao aquecer, cada metal tentaria aumentar de comprimento de acordo com seu próprio coeficiente. Como eles estão unidos, nenhum deles consegue fazer isso sozinho.',sec('Para que lado ela se curva?',p('O metal com maior coeficiente tenta ficar mais comprido. Ele ocupa o lado de fora da curva, onde o caminho é maior. O metal com menor coeficiente fica no lado de dentro. Assim, durante o aquecimento, a lâmina se curva para o lado do metal que dilata menos.'))+sec('E quando esfria?',p('Ao resfriar, o metal de maior coeficiente também tenta contrair mais. O sentido da curvatura se inverte. Por isso não basta decorar “curva para A” ou “curva para B”: precisamos comparar os coeficientes e observar se houve aquecimento ou resfriamento.'))+note('Antes de mover o controle',p('Escolha os metais, preveja o lado da curva e só então altere a temperatura. A deformação desenhada é muito ampliada para ficar visível.')),lab('bimetal','Compare dois metais unidos'))},
{label:'Líquidos e recipientes',title:'Dilatação dos líquidos e do recipiente',subtitle:'O que vemos é a diferença entre duas expansões.',reason:why('Líquido aumenta','Recipiente ganha capacidade','Aparece o transbordamento','Questões oferecem a expansão real como distração quando pedem a aparente.'),html:page('Imagine um frasco completamente cheio. Ao aquecer, o líquido aumenta de volume e o recipiente também ganha capacidade. Nem toda a expansão do líquido transborda.',transition('vimos que duas chapas de metais diferentes, quando estão unidas e são aquecidas, não conseguem se dilatar livremente. Como uma tenta variar mais que a outra, o conjunto se curva.','continuamos dentro da dilatação térmica, mas mudamos de situação. Vamos observar o que acontece quando aquecemos, ao mesmo tempo, um líquido e o recipiente que o contém.')+sec('Três nomes',p('<strong>Real:</strong> todo o aumento do líquido. <strong>Recipiente:</strong> aumento da capacidade interna. <strong>Aparente:</strong> diferença observada em relação ao recipiente.')+f('ΔV<sub>aparente</sub> = ΔV<sub>real</sub> − ΔV<sub>recipiente</sub>'))+sec('Um exemplo',p('O líquido ganha 9 mL e o recipiente passa a comportar 3 mL a mais. Os 3 mL ficam na nova capacidade; 6 mL transbordam. O líquido dilatou 9 mL, embora vejamos 6 mL saindo.'))+note('Condição',p('Se o frasco não estava cheio, a diferença pode ocupar o espaço vazio e não haverá necessariamente transbordamento.')),lab('liquid','Líquido, recipiente e coletor'))},
{label:'Coeficiente aparente',title:'Coeficiente real e coeficiente aparente',subtitle:'O recipiente participa da medida.',reason:why('Dois corpos se dilatam','Subtrair coeficientes','Obter γaparente','A relação organiza a conta sem repetir o mecanismo do transbordamento.'),html:page('Quando líquido e recipiente começam com o mesmo volume e recebem a mesma variação de temperatura, podemos escrever a diferença com os coeficientes.',sec('A relação',f('γ<sub>aparente</sub> ≈ γ<sub>líquido</sub> − γ<sub>recipiente</sub>')+p('Se os coeficientes forem iguais, a dilatação aparente será zero, embora os dois continuem aumentando de volume.'))+note('Leia a palavra pedida',p('“Real” aponta para o líquido. “Capacidade” aponta para o recipiente. “Aparente” ou “transbordado”, quando começa cheio, aponta para a diferença.')),lab('volume','Separe as parcelas'))},
{label:'Água de 0 a 4 °C',title:'Dilatação anômala da água',subtitle:'Por que um lago congela primeiro na superfície?',reason:why('Convecção e densidade','Máximo perto de 4 °C','Gelo fica em cima','O fenômeno conecta dilatação e densidade a uma situação observável.'),html:page('Se seguíssemos apenas a regra “mais frio é mais denso”, esperaríamos que a água mais fria e o gelo fossem para o fundo. Mas a água tem um comportamento especial.',sec('Comece pela convecção',p('Em muitas situações, uma porção aquecida se expande, fica menos densa e sobe; a parte mais fria e densa desce. É parecida com a circulação de massas de ar estudada em Geografia.'))+sec('O que a água faz?',p('Ao esfriar até perto de 4 °C, a água fica mais densa e desce. Abaixo de aproximadamente 4 °C, a tendência muda: a água que continua esfriando fica menos densa e permanece perto da superfície. Quando congela, o gelo é ainda menos denso e flutua.')+f('massa fixa: ρ = m/V'))+sec('Por que importa?',p('A camada de gelo na superfície reduz a troca de energia com o ar e a água abaixo pode continuar líquida. É uma explicação simplificada: vento, salinidade, circulação e profundidade também influenciam um lago real.'))+note('Observe o gráfico',p('De 0 °C a 4 °C, aquecer diminui o volume e aumenta a densidade. Perto de 4 °C, a densidade é máxima. Acima disso, aquecer volta a aumentar o volume.')),lab('water','Encontre a maior densidade'))},
{label:'Exercício de sólidos',title:'Exercício: dilatação linear',subtitle:'Calcule, converta e confira se milímetros fazem sentido.',reason:why('ΔL = L₀αΔT','Resolver','Avaliar escala','A questão verifica potência de dez e diferença entre ΔL e comprimento final.'),html:page('Estime primeiro: uma barra metálica comum aquecida em 100 °C deve variar milímetros, não metros.',quiz('bar'))},
{label:'Exercício de líquidos',title:'Exercício: líquido e recipiente',subtitle:'A resposta visível é a diferença.',reason:why('Expansão real','Capacidade','Transbordamento','A questão verifica se você desconta a expansão do recipiente.'),html:page('Faça duas contas e dê nome a cada resultado antes de subtrair.',quiz('liquid'))},
{label:'Síntese',title:'Dilatação térmica: síntese',subtitle:'A mesma estrutura aparece em situações diferentes.',reason:why('Temperatura varia','Grandeza responde','Interpretar','A síntese ajuda a localizar a relação certa.'),html:page('Em sólidos, escolha a dimensão. Em líquidos, separe líquido e recipiente. Sempre interprete sinal, unidade e ordem de grandeza.',sec('Sólidos',f('ΔL = L₀αΔT &nbsp; · &nbsp; ΔA = A₀βΔT &nbsp; · &nbsp; ΔV = V₀γΔT')+p('Para pequenas dilatações em materiais isotrópicos: β ≈ 2α e γ ≈ 3α.'))+sec('Líquidos',f('ΔV<sub>aparente</sub> = ΔV<sub>real</sub> − ΔV<sub>recipiente</sub>'))+story('termometros','Como aprendemos a medir temperatura'))}
];

Object.assign(quizzes.press,{sense:'1.600 N correspondem aproximadamente ao peso de uma massa de 160 kg quando usamos g ≈ 10 m/s². A força é grande, mas a saída percorre uma distância vinte vezes menor.',senseLink:'#grandezas'});
Object.assign(quizzes.buoy,{sense:'20 N de empuxo correspondem aproximadamente ao peso de 2 kg. Num corpo de peso 30 N, ainda faltam 10 N para o equilíbrio; a tração encontrada é coerente.',senseLink:'#grandezas'});
Object.assign(quizzes.bar,{sense:'2,4 mm em uma barra de 2 m representam pouco mais de um milésimo do comprimento. Essa escala é plausível para um metal aquecido em 100 °C.',senseLink:'#grandezas'});
Object.assign(quizzes.liquid,{sense:'6 mL são pouco mais de uma colher de chá. O líquido aumentou 9 mL, mas 3 mL ficaram na capacidade adicional do recipiente.',senseLink:'#grandezas'});
Object.assign(quizzes.depth,{sense:'150 kPa são cerca de uma vez e meia a pressão atmosférica adotada. A coluna de água acrescentou 50 kPa aos 100 kPa da superfície.',senseLink:'#grandezas'});
Object.assign(quizzes.density,{sense:'2.700 kg/m³ são 2,7 vezes a densidade da água. Uma peça maciça com essa densidade não flutuaria livremente nela.',senseLink:'#grandezas'});
if(quizzes.kelvin)Object.assign(quizzes.kelvin,{sense:'298,15 K e 25 °C descrevem o mesmo estado. A variação de 25 K tem o mesmo tamanho numérico que 25 °C.',senseLink:'#grandezas'});

['arquimedes-pascal','termometros','zero-absoluto'].forEach(id=>{const h=histories.find(x=>x.id===id);if(!h||h.slides.length===1)return;const old=h.slides;h.slides=[{label:'Leitura completa',title:h.title,subtitle:'A história inteira, com referências, sem sair da plataforma.',html:`<div class="history-landing"><div class="history-timeline">${old.map((s,i)=>`<section><span class="timeline-dot">${i+1}</span><p class="eyebrow">${s.label}</p><h2>${s.title}</h2>${s.html}</section>`).join('')}</div></div>`}];});
})();


