/* Capítulo autoral construído a partir do recorte conceitual do material enviado. */
(()=>{'use strict';
const MM=window.MM;
const p=s=>`<p>${s}</p>`, note=s=>`<div class="callout">${s.replace('<strong>Ou seja:</strong>','<strong class="summary-label">Ou seja</strong>')}</div>`, formula=s=>`<div class="formula">${s}</div>`;
const report=()=>'';
const lab=(id,label)=>`<div class="lab projectile-lab" data-lab="${id}"><div class="lab-head"><span>${label}</span><span>Explore</span></div><div class="lab-body"></div><div class="observation-bar"><span>Observação interativa</span>${report(label)}</div></div>`;
const split=(copy,right)=>`<div class="split"><div class="copy">${copy}</div>${right}</div>`;
const slides=[
 {label:'Situação inicial',title:'Um objeto deixa a mesa. <em>O que acontece agora?</em>',subtitle:'Antes da fórmula, observe e faça uma previsão.',html:split(p('Imagine uma esfera que chega à borda de uma mesa com velocidade horizontal. Assim que perde o apoio, ela não para de avançar. Ao mesmo tempo, começa a cair.')+p('Escolha sua previsão e acione a cena. Observe a posição da esfera em intervalos iguais de tempo. A curva não será apresentada como uma forma pronta: ela será construída ponto a ponto.')+note('Modelo desta aula: desprezamos a resistência do ar, consideramos a gravidade constante e tratamos o objeto como um ponto material.'),lab('projectile-intro','Da borda da mesa ao chão'))},
 {label:'Dois movimentos',title:'Um movimento. <em>Duas leituras.</em>',subtitle:'Separe a trajetória sem separar o tempo.',html:split(p('O lançamento horizontal pode ser estudado como a combinação de dois movimentos que acontecem ao mesmo tempo. Na horizontal, a esfera percorre distâncias iguais em tempos iguais. Na vertical, as distâncias percorridas aumentam porque a gravidade altera a velocidade.')+p('Use os botões para olhar apenas a sombra horizontal, apenas a queda vertical ou os dois movimentos reunidos. O relógio é o mesmo nas três leituras.')+note('<strong>Ou seja:</strong> a esfera avança com movimento uniforme na horizontal e cai em queda livre na vertical.'),lab('projectile-components','Separe horizontal e vertical'))},
 {label:'Independência',title:'Lançar ou soltar: <em>quem chega primeiro?</em>',subtitle:'Duas esferas, a mesma altura e um único relógio.',html:split(p('Uma esfera é lançada horizontalmente enquanto outra é simplesmente solta da mesma altura. A primeira avança; a segunda não. Na vertical, porém, as duas começam com velocidade vertical igual a zero e recebem a mesma aceleração da gravidade.')+p('Faça a previsão antes de iniciar. Depois acompanhe as linhas horizontais: a cada instante, as duas esferas permanecem na mesma altura.')+note('<strong>Ou seja:</strong> aumentar a velocidade horizontal muda o alcance, mas não muda o tempo de queda neste modelo.'),lab('projectile-independence','Lançamento e queda simultâneos'))},
 {label:'Movimento horizontal',title:'Na horizontal: <em>movimento uniforme.</em>',subtitle:'A velocidade horizontal fica constante.',html:split(p('Sem resistência do ar, não existe força horizontal resultante depois que a esfera deixa a mão ou a mesa. Por isso, a componente horizontal da velocidade não aumenta nem diminui.')+formula('x = v<sub>x</sub>t')+p('Se o tempo dobra, o deslocamento horizontal também dobra. As marcações igualmente espaçadas na animação mostram essa regularidade antes da conta.')+note('<strong>Ou seja:</strong> o objeto não precisa de uma força empurrando-o continuamente para continuar avançando.'),lab('projectile-horizontal','Espaços iguais em tempos iguais'))},
 {label:'Movimento vertical',title:'Na vertical: <em>queda livre.</em>',subtitle:'A gravidade muda a velocidade vertical.',html:split(p('No instante do lançamento, a componente vertical da velocidade é zero. Depois disso, a gravidade faz essa componente crescer para baixo. Por isso, em intervalos iguais de tempo, a esfera percorre distâncias verticais cada vez maiores.')+formula('H = <span class="fraction"><span>gt²</span><span>2</span></span> &nbsp; · &nbsp; v<sub>y</sub> = gt')+p('A altura determina quanto tempo a queda pode durar. Massa e velocidade horizontal não aparecem nessa relação.')+note('<strong>Ou seja:</strong> a parte vertical do lançamento horizontal é uma queda livre iniciada sem velocidade vertical.'),lab('projectile-vertical','A queda acelera'))},
 {label:'Trajetória',title:'Por que a trajetória <em>faz uma curva?</em>',subtitle:'A parábola nasce da combinação dos movimentos.',html:split(p('Se olhássemos apenas a horizontal, veríamos pontos igualmente espaçados. Se olhássemos apenas a vertical, veríamos uma queda cada vez mais rápida. Ao sobrepor as duas sequências usando o mesmo relógio, aparece a trajetória curva.')+p('A forma da trajetória não representa uma força curvada. Durante o voo ideal, a aceleração continua vertical e para baixo.')+note('<strong>Ou seja:</strong> a curva é o registro de um avanço uniforme acontecendo junto de uma queda acelerada.'),lab('projectile-components','Construa a trajetória'))},
 {label:'Velocidade',title:'A velocidade resultante <em>muda.</em>',subtitle:'Uma componente permanece; a outra cresce.',html:split(p('A velocidade da esfera é representada pela soma de duas componentes. A seta horizontal mantém o tamanho. A seta vertical cresce para baixo. A resultante acompanha a direção instantânea do movimento e fica tangente à trajetória.')+formula('v<sub>R</sub>² = v<sub>x</sub>² + v<sub>y</sub>²')+p('Pause a animação e compare os vetores no início, no meio e perto do chão.')+note('<strong>Ou seja:</strong> mesmo com v<sub>x</sub> constante, a rapidez total aumenta porque v<sub>y</sub> aumenta.'),lab('projectile-vectors','Componentes e velocidade resultante'))},
 {label:'Tempo e alcance',title:'Quanto tempo cai? <em>Até onde avança?</em>',subtitle:'O mesmo tempo conecta as duas direções.',html:split(p('Primeiro resolvemos a queda vertical para descobrir o tempo. Em seguida usamos exatamente esse tempo no movimento horizontal. Essa ordem evita misturar grandezas de direções diferentes.')+formula('t = √<span class="radicand">2H/g</span> &nbsp; → &nbsp; x = v<sub>x</sub>t')+p('Mude a altura e a velocidade separadamente. A altura altera o tempo disponível; a velocidade horizontal altera quanto o objeto avança a cada segundo.')+note('<strong>Ou seja:</strong> o alcance cresce quando o objeto permanece mais tempo no ar ou quando sua velocidade horizontal é maior.'),lab('projectile-target','Acerte o ponto de chegada'))},
 {label:'Aplicação',title:'Uma entrega pelo ar. <em>Quando soltar?</em>',subtitle:'A caixa continua avançando depois de ser liberada.',html:split(p('Uma aeronave que transporta uma caixa também possui velocidade horizontal. Ao ser solta, a caixa conserva essa componente e começa a cair. Por isso, ela precisa ser liberada antes de a aeronave passar sobre o alvo.')+p('A experiência adota o modelo ideal; numa operação real, vento, formato da carga e resistência do ar também importam.')+note('<strong>Ou seja:</strong> soltar a carga exatamente sobre o alvo faria com que ela atingisse o chão mais adiante.')+`<a class="story-link" href="#historia/voo-hiroshima-nagasaki/0" data-story="voo-hiroshima-nagasaki"><span>História, Física e responsabilidade</span><strong>Quarenta e poucos segundos entre a liberação e a explosão</strong><small>Conheça a história</small></a>`,lab('projectile-target','Observe a conservação do movimento horizontal'))},
 {label:'Como resolver',title:'Do desenho à resposta. <em>Uma direção de cada vez.</em>',subtitle:'Organize o problema antes de substituir números.',html:split(p('Comece identificando a altura, a velocidade horizontal e o que a questão pede. Resolva a parte vertical para obter o tempo. Depois leve esse tempo para a horizontal. Se a velocidade final for pedida, calcule v<sub>y</sub> e só então componha os vetores.')+`<ol class="lesson-steps"><li>Separe horizontal e vertical.</li><li>Calcule o tempo pela queda.</li><li>Use o mesmo tempo no avanço horizontal.</li><li>Calcule as componentes finais, se necessário.</li><li>Confira unidade e ordem de grandeza.</li></ol>`+note('<strong>Ou seja:</strong> o segredo não é decorar muitas fórmulas; é reconhecer dois movimentos ligados pelo mesmo tempo.'),lab('projectile-target','Teste um cenário completo'))},
 {label:'Síntese',title:'Avança enquanto cai. <em>Agora reúna as ideias.</em>',subtitle:'O mapa completo do lançamento horizontal.',html:`<div class="summary-grid"><article><h3>Horizontal</h3>${formula('x = v<sub>x</sub>t')}<p>Movimento uniforme: v<sub>x</sub> constante.</p></article><article><h3>Vertical</h3>${formula('H = gt²/2')}<p>Queda livre: v<sub>y</sub> cresce com o tempo.</p></article><article><h3>Resultado</h3>${formula('v<sub>R</sub>² = v<sub>x</sub>² + v<sub>y</sub>²')}<p>A combinação produz a trajetória parabólica.</p></article></div><aside class="takeaway is-revealed"><span>Ou seja</span><p>O lançamento horizontal é um movimento uniforme na horizontal e uma queda livre na vertical. Eles acontecem simultaneamente, de forma independente, e compartilham o mesmo tempo.</p></aside><div class="next-study"><a class="primary" href="#exercicios">Abrir exercícios</a><a class="secondary" href="#estudos">Voltar aos estudos</a></div>`}
];
MM.lessons.push({id:'lancamento-horizontal',area:'Mecânica',title:'Lançamento horizontal',desc:'Um movimento uniforme na horizontal e uma queda livre na vertical.',symbol:'vₓ · g · t',time:'40–55 min',slides});
MM.histories.push({id:'voo-hiroshima-nagasaki',title:'Quarenta e poucos segundos',date:'Agosto de 1945',lesson:'lancamento-horizontal',desc:'O intervalo de queda, o avanço da aeronave e a dimensão humana dos bombardeios de Hiroshima e Nagasaki.',slides:[
 {label:'Contexto',title:'Uma aplicação da Física marcada <em>pela destruição.</em>',html:`<div class="reading-page"><p>Em agosto de 1945, bombas atômicas foram lançadas sobre Hiroshima e Nagasaki. Estudar a trajetória desses artefatos ajuda a compreender o movimento, mas a explicação não pode transformar o acontecimento em uma demonstração neutra: dezenas de milhares de pessoas morreram imediatamente e muitas outras morreram depois em consequência das explosões e da radiação.</p><div class="callout"><strong>Questão para pensar:</strong> compreender a Física de uma tecnologia também exige discutir as escolhas humanas e as consequências de seu uso.</div></div>`},
 {label:'Hiroshima',title:'Hiroshima: <em>43 segundos de queda.</em>',html:`<div class="reading-page"><p>Em 6 de agosto de 1945, a bomba foi liberada pelo Enola Gay a cerca de 9,5 quilômetros de altitude. Ela permaneceu em queda por aproximadamente 43 segundos e explodiu ainda no ar, a cerca de 600 metros do solo.</p><p>O avião não estava passando lentamente sobre a cidade. Dados técnicos indicam velocidade sobre o solo próxima de 528 km/h. Depois da liberação, o piloto iniciou uma manobra de afastamento. Quando a onda de choque alcançou a aeronave, ela já estava a vários quilômetros do ponto da explosão.</p><div class="callout"><strong>Ligação com a aula:</strong> durante os segundos de queda, a bomba continuou avançando horizontalmente. A tripulação também usou esse intervalo para aumentar a distância em relação ao ponto de detonação.</div></div>`},
 {label:'Comparar',title:'Nagasaki: outro lançamento, <em>outro intervalo.</em>',html:`<div class="reading-page"><p>Três dias depois, a bomba lançada sobre Nagasaki permaneceu aproximadamente 47 segundos em queda. Os registros técnicos indicam velocidade da aeronave próxima de 507 km/h. Diferenças de altitude, formato e comportamento aerodinâmico impedem tratar os dois casos como uma queda livre escolar perfeita.</p><p>O modelo do capítulo ajuda a construir a primeira leitura: movimento horizontal e queda vertical acontecem simultaneamente. A situação histórica real exige ainda resistência do ar, vento, manobra da aeronave e o sistema de detonação em altitude.</p><div class="history-source"><strong>Fontes consultadas</strong><a href="https://www.nps.gov/articles/000/the-atomic-bombings-of-hiroshima-and-nagasaki.htm" target="_blank" rel="noopener">National Park Service — cronologia dos bombardeios</a><a href="https://www.osti.gov/opennet/manhattan-project-history/publications/LANLHiroshimaNagasakiYields.pdf" target="_blank" rel="noopener">Los Alamos / OSTI — parâmetros das trajetórias</a><a href="https://www.osti.gov/opennet/manhattan-project-history/publications/DE99001330.pdf" target="_blank" rel="noopener">Departamento de Energia dos EUA — história do Projeto Manhattan</a></div><div class="next-study"><a class="primary" href="#aula/lancamento-horizontal/8/autodidata">Voltar à aplicação da aula</a></div></div>`}
]});
MM.chapterModes['lancamento-horizontal']={modes:['professor','aluno','autodidata']};
const q=(summary,prompt,choices,correct,hint,focus,board)=>({summary,prompt,choices,correct,hint,focus,board});
MM.modeContent['lancamento-horizontal']=[
q('Ao perder o apoio, o objeto conserva a velocidade horizontal e começa a adquirir velocidade vertical.','Depois que a esfera deixa a mesa, qual descrição é mais adequada?',['Ela para de avançar e apenas cai.','Ela avança e cai ao mesmo tempo.','Ela continua em linha reta sem cair.'],1,'O fim do contato com a mesa não apaga a velocidade que a esfera já possuía.','Recolha previsões antes de acionar a cena. Não corrija pela aparência da curva.','Desenhe a borda da mesa e marque uma seta horizontal no instante da saída.'),
q('O movimento completo pode ser separado em movimento uniforme horizontal e queda livre vertical, ligados pelo mesmo tempo.','Qual grandeza pertence simultaneamente às duas análises?',['O tempo.','A velocidade horizontal.','A distância vertical.'],0,'Os dois movimentos começam e terminam nos mesmos instantes.','Use um relógio único e alterne entre as três visualizações.','Duas colunas, horizontal e vertical, ligadas por t.'),
q('Duas esferas que começam a cair juntas da mesma altura têm a mesma evolução vertical, mesmo que uma avance horizontalmente.','Sem resistência do ar, qual esfera chega primeiro ao chão?',['A lançada horizontalmente.','A simplesmente solta.','As duas chegam juntas.'],2,'Compare somente as alturas em cada instante.','Peça justificativas antes do teste e retorne às previsões depois.','Desenhe linhas horizontais ligando as posições simultâneas.'),
q('Na horizontal, sem força resultante, a velocidade fica constante e os deslocamentos iguais correspondem a tempos iguais.','Se vₓ fica constante e o tempo dobra, o deslocamento horizontal:',['dobra.','cai pela metade.','permanece igual.'],0,'Use x = vₓt e mantenha vₓ fixo.','Conecte as marcações igualmente espaçadas à expressão matemática.','x = vₓt; circule “constante”.'),
q('Na vertical, o objeto começa com vᵧ igual a zero e acelera para baixo por causa da gravidade.','Em intervalos iguais de tempo, as distâncias verticais sucessivas:',['ficam iguais.','aumentam.','diminuem.'],1,'A velocidade vertical cresce com o tempo.','Mostre os pontos antes da fórmula e peça uma descrição verbal.','vᵧ = gt e H = gt²/2.'),
q('A trajetória curva surge ao reunir avanço uniforme e queda acelerada. A aceleração não acompanha a curva.','Durante o voo ideal, para onde aponta a aceleração?',['Tangente à trajetória.','Horizontalmente para a frente.','Verticalmente para baixo.'],2,'A força relevante durante o voo é o peso.','Diferencie direção da velocidade e direção da aceleração.','Desenhe v tangente e g vertical.'),
q('A componente horizontal fica constante; a vertical cresce. A velocidade resultante é a soma vetorial das duas.','Por que a rapidez total aumenta durante a queda?',['Porque vₓ aumenta.','Porque vᵧ aumenta enquanto vₓ fica constante.','Porque a massa aumenta.'],1,'Observe qual das duas setas muda de tamanho.','Pause em três instantes e compare os triângulos de velocidades.','vᵣ² = vₓ² + vᵧ².'),
q('O tempo é encontrado pela queda vertical e depois usado para calcular o alcance horizontal.','Qual ordem organiza melhor a resolução?',['Alcance, massa e depois tempo.','Tempo pela altura e depois alcance com vₓ.','Somar altura e alcance.'],1,'A parte horizontal precisa saber por quanto tempo o objeto ficou no ar.','Resolva um cenário alterando uma variável por vez.','t = √(2H/g) → x = vₓt.'),
q('Uma carga solta por uma aeronave mantém a velocidade horizontal que possuía no instante da soltura.','No modelo ideal, quando a carga deve ser solta para atingir um alvo no chão?',['Antes de passar sobre o alvo.','Exatamente sobre o alvo.','Depois de passar sobre o alvo.'],0,'Durante a queda, a carga continua avançando.','Use a tentativa errada como oportunidade para recuperar a inércia.','Desenhe a aeronave antes do alvo e a parábola até ele.'),
q('Resolver bem exige separar direções, encontrar o tempo, conectar as partes e verificar a plausibilidade.','Qual é o primeiro passo mais seguro?',['Escolher uma fórmula pelo número de dados.','Separar as grandezas horizontais e verticais.','Converter tudo para quilômetros por hora.'],1,'Antes da conta, organize o desenho e as direções.','Faça a turma narrar o roteiro com as próprias palavras.','horizontal | vertical, unidos por t.'),
q('O lançamento horizontal reúne movimento uniforme horizontal e queda livre vertical, independentes e simultâneos.','Qual frase resume o capítulo?',['A gravidade elimina a velocidade horizontal.','O corpo avança uniformemente enquanto cai acelerado.','A velocidade fica constante em todas as direções.'],1,'Procure uma frase que descreva as duas direções.','Feche reconstruindo o mapa sem reler as fórmulas.','MU horizontal + queda livre vertical → trajetória parabólica.')
];

const oldMount=window.MMLabs.mount;
const kinds=new Set(['projectile-intro','projectile-components','projectile-independence','projectile-horizontal','projectile-vertical','projectile-vectors','projectile-target']);
window.MMLabs.mount=function(el,cache,key){if(!kinds.has(el.dataset.lab))return oldMount(el,cache,key);mountProjectile(el,cache,key);};
function mountProjectile(el,cache,key){
 const type=el.dataset.lab,host=el.querySelector('.lab-body'),state=cache.get(key+'|'+type)||{vx:12,h:20,g:10,t:0,view:'both',running:false,release:0,trace:true};if(state.trace===undefined)state.trace=true;cache.set(key+'|'+type,state);
 const flightTime=()=>Math.sqrt(2*state.h/state.g), range=()=>state.vx*flightTime(), tableTop=()=>280-(55+(state.h-5)/40*180);
 const controls=`<div class="projectile-controls"><label>Velocidade horizontal <output data-out-vx>${state.vx} m/s</output><input data-vx type="range" min="4" max="24" value="${state.vx}"></label><label>Altura <output data-out-h>${state.h} m</output><input data-h type="range" min="5" max="45" value="${state.h}"></label>${type==='projectile-components'?`<div class="sim-actions"><button data-view="x">Só horizontal</button><button data-view="y">Só vertical</button><button data-view="both">Reunir</button></div>`:''}<div class="sim-actions"><button data-trace aria-pressed="${state.trace}">${state.trace?'Ocultar trajetória':'Mostrar trajetória'}</button><button data-reset>Recomeçar</button></div><button class="primary-lab-action" data-play>${type==='projectile-independence'?'Soltar as duas esferas':'Acionar movimento'}</button></div>`;
 host.innerHTML=`<div class="projectile-stage"><svg viewBox="0 0 760 330" role="img" aria-label="Simulação de lançamento horizontal"><g data-scene></g></svg></div>${controls}<div class="lab-results" data-results role="status" aria-live="polite"></div>`;
 const scene=host.querySelector('[data-scene]'),results=host.querySelector('[data-results]');let raf=0,start=0;
 const xy=t=>{const top=tableTop();return{x:75+state.vx*t*8,y:top+(0.5*state.g*t*t/state.h)*(280-top)}};
 function draw(){const T=Math.sqrt(2*state.h/state.g),t=Math.min(state.t,T),o=xy(t),top=tableTop(),points=Array.from({length:31},(_,i)=>xy(T*i/30)),markers=Array.from({length:7},(_,i)=>xy(T*i/6));let trail='';for(let i=0;i<points.length;i++)trail+=`${i?'L':'M'}${points[i].x},${points[i].y} `;const showX=state.view!=='y',showY=state.view!=='x';let b=`<line x1="55" y1="280" x2="720" y2="280" stroke="var(--ink)" stroke-width="2"/><path d="M35 ${top}H75V280" fill="none" stroke="var(--ink)" stroke-width="5"/><line x1="44" y1="${top}" x2="44" y2="280" stroke="var(--accent)" stroke-width="1" stroke-dasharray="4 5"/><text x="37" y="${(top+280)/2}" text-anchor="end" fill="var(--accent)" font-size="14" font-weight="700">${state.h} m</text>${state.trace?`<path d="${trail}" fill="none" stroke="var(--tone-2)" stroke-width="3" stroke-dasharray="7 7"/>`:''}`;
 if(state.trace)markers.forEach((p,i)=>{const label=(T*i/6).toFixed(1)+' s',w=label.length*7.4+12,y=Math.max(18,p.y-25);b+=`<circle cx="${p.x}" cy="${p.y}" r="5" fill="var(--tone-2)"/><rect x="${p.x-w/2}" y="${y-13}" width="${w}" height="19" rx="4" fill="var(--paper)" stroke="var(--line)"/><text x="${p.x}" y="${y+1}" text-anchor="middle" fill="var(--ink)" font-size="13" font-weight="700">${label}</text>`;});
 if(type==='projectile-independence'){const dropY=o.y;b+=`<circle cx="75" cy="${dropY}" r="10" fill="var(--tone-3)"/><line x1="75" y1="${dropY}" x2="${o.x}" y2="${o.y}" stroke="var(--accent)" stroke-dasharray="5 5"/><text x="100" y="26" fill="var(--ink)" font-size="14">Mesmo instante, mesma altura</text>`;}
 b+=`<circle cx="${o.x}" cy="${o.y}" r="12" fill="var(--accent)"/>`;
 if(showX)b+=`<line x1="${o.x}" y1="${o.y}" x2="${o.x+55}" y2="${o.y}" stroke="var(--tone-1)" stroke-width="4"/><text x="${o.x+60}" y="${o.y-6}" fill="var(--tone-1)" font-size="14">vₓ</text>`;
 if(showY){const vy=state.g*t;b+=`<line x1="${o.x}" y1="${o.y}" x2="${o.x}" y2="${o.y+Math.min(75,vy*3)}" stroke="var(--tone-3)" stroke-width="4"/><text x="${o.x+8}" y="${o.y+Math.min(85,vy*3+14)}" fill="var(--tone-3)" font-size="14">vᵧ</text>`;}
 if(type==='projectile-target'){const target=635+state.release*3;b+=`<circle cx="${target}" cy="280" r="24" fill="none" stroke="var(--tone-3)" stroke-width="5"/><circle cx="${target}" cy="280" r="7" fill="var(--tone-3)"/>`;}
 scene.innerHTML=b;const vy=state.g*t,vr=Math.hypot(state.vx,vy);results.innerHTML=`<div class="readouts"><div class="readout"><small>Tempo</small><strong>${t.toFixed(2)} s</strong></div><div class="readout"><small>Avanço</small><strong>${(state.vx*t).toFixed(1)} m</strong></div><div class="readout"><small>Queda</small><strong>${(.5*state.g*t*t).toFixed(1)} m</strong></div><div class="readout"><small>Rapidez</small><strong>${vr.toFixed(1)} m/s</strong></div></div><p class="sim-explanation">Na horizontal, v<sub>x</sub> = ${state.vx} m/s fica constante. Na vertical, v<sub>y</sub> = gt cresce. Os dois cálculos usam o mesmo tempo.</p>`;}
 function play(now){if(!start)start=now;const end=flightTime();state.t=Math.min((now-start)/1000,end);draw();if(state.t<end)raf=requestAnimationFrame(play);else{state.running=false;start=0;}}
 host.querySelector('[data-play]').onclick=()=>{cancelAnimationFrame(raf);state.t=0;start=0;state.running=true;raf=requestAnimationFrame(play);};host.querySelector('[data-reset]').onclick=()=>{cancelAnimationFrame(raf);state.t=0;start=0;draw();};const traceButton=host.querySelector('[data-trace]');traceButton.onclick=()=>{state.trace=!state.trace;traceButton.setAttribute('aria-pressed',String(state.trace));traceButton.textContent=state.trace?'Ocultar trajetória':'Mostrar trajetória';draw();};
 const stopAndReset=()=>{cancelAnimationFrame(raf);raf=0;start=0;state.running=false;state.t=0;};
 host.querySelector('[data-vx]').oninput=e=>{stopAndReset();state.vx=+e.target.value;host.querySelector('[data-out-vx]').textContent=state.vx+' m/s';draw();};host.querySelector('[data-h]').oninput=e=>{stopAndReset();state.h=+e.target.value;host.querySelector('[data-out-h]').textContent=state.h+' m';draw();};host.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;draw();});draw();
}
})();

