(()=>{
'use strict';
const MM=window.MM;
const q=(summary,prompt,choices,correct,hint,focus,board,resource='')=>({summary,prompt,choices,correct,hint,focus,board,resource});
MM.modeContent={
hidrostatica:[
q('Mesmo parado, um fluido continua recebendo forças. Ele permanece em equilíbrio porque essas forças se compensam.','Um líquido em repouso está sem forças atuando sobre ele?',['Sim, repouso significa ausência de forças.','Não. As forças existem, mas estão equilibradas.','Somente a gravidade atua.'],1,'Repouso descreve o movimento; equilíbrio descreve a soma das forças.','Diferencie repouso de ausência de forças e peça que a turma identifique gravidade, pressão e apoio.','Desenhe uma pequena porção de líquido e marque forças em sentidos opostos.'),
q('Densidade informa quanta massa está concentrada em cada unidade de volume: ρ = m/V.','Mantendo a massa, o que acontece com a densidade quando o volume diminui?',['Aumenta.','Diminui.','Permanece igual.'],0,'Imagine a mesma quantidade de matéria ocupando menos espaço.','Comece com dois objetos do mesmo tamanho e massas diferentes. Só apresente ρ = m/V depois da comparação.','Escreva “mesmo volume, massas diferentes” e ligue a comparação à densidade.'),
q('Medir densidade exige medir massa e volume, dividir uma grandeza pela outra e interpretar o resultado com uma referência conhecida.','Uma peça tem 540 g e 200 cm³. Qual leitura está correta?',['2,7 g/cm³: cada cm³ corresponde, em média, a 2,7 g.','740 g/cm³: basta somar massa e volume.','0,37 g/cm³: volume sempre deve ficar no numerador.'],0,'Densidade é massa dividida pelo volume.','Não encerre na conta. Compare o resultado com a água e pergunte se a ordem de grandeza parece plausível.','Monte três linhas: dados, divisão com unidade e comparação com 1 g/cm³.'),
q('A mesma força produz maior pressão quando atua numa área menor e menor pressão quando se distribui por uma área maior.','Uma pessoa precisa atravessar telhas frágeis. Por que uma tábua larga ajuda?',['Aumenta o peso da pessoa.','Distribui a força por uma área maior e reduz a pressão.','Elimina a força exercida sobre as telhas.'],1,'O peso permanece praticamente o mesmo; observe o que mudou na área.','Use a tábua do pedreiro e o fio da faca como contrastes. Faça a turma manter a força e variar apenas a área.','Escreva p = F/A e desenhe a mesma força sobre uma área pequena e uma grande.'),
q('A pressão de um líquido parado atua em todas as direções e sempre perpendicularmente à superfície que recebe a força.','Num ponto dentro de um líquido parado, a pressão empurra apenas para baixo?',['Sim, porque a gravidade aponta para baixo.','Não. A pressão atua em todas as direções.','Somente para os lados.'],1,'A gravidade ajuda a explicar a variação com a profundidade, mas a pressão local não possui uma única direção.','Use setas ao redor de uma pequena superfície e destaque que cada força é perpendicular ao contato.','Desenhe um ponto com pequenas superfícies orientadas em direções diferentes.'),
q('A atmosfera exerce pressão. No canudo, reduzimos a pressão na boca e o ar externo ajuda a empurrar a bebida para cima.','O líquido sobe no canudo porque a boca o puxa diretamente?',['Sim, a sucção cria uma força que puxa o líquido.','Não. A diferença de pressão permite que a atmosfera o empurre.','Não. Ele sobe apenas por capilaridade.'],1,'Compare a pressão sobre a bebida com a pressão dentro do canudo.','Evite a frase “a sucção puxa”. Conduza a explicação pela diferença de pressão.','Desenhe p_atm sobre a bebida e uma pressão menor dentro do canudo.'),
q('No mesmo líquido, o aumento de pressão depende de ρ, g e do desnível vertical: Δp = ρgΔh.','Dois pontos estão no mesmo líquido. Qual caminho determina a diferença de pressão?',['O comprimento inclinado do recipiente.','A distância percorrida pelo líquido.','O desnível vertical entre os pontos.'],2,'A expressão usa Δh: altura, não o formato do caminho.','Compare um tubo inclinado e um vertical com o mesmo desnível. Peça uma previsão antes da conta.','Marque uma linha horizontal em cada ponto e destaque apenas Δh.'),
q('Em regiões conectadas do mesmo líquido e na mesma altura, a pressão é a mesma. Essa ideia organiza vasos comunicantes.','Em vasos abertos com o mesmo líquido, o que acontece no equilíbrio?',['As superfícies tendem ao mesmo nível.','O ramo mais largo sempre fica mais alto.','A pressão é maior no ramo mais estreito.'],0,'Compare pontos de uma mesma linha horizontal no líquido conectado.','Faça a turma ignorar o formato do recipiente e procurar uma linha horizontal comum.','Trace uma linha horizontal e escreva p_esq = p_dir.'),
q('Pressão manométrica mede o acréscimo em relação à atmosfera; pressão absoluta inclui a atmosfera: p_abs = p_atm + ρgh.','Uma coluna acrescenta 50 kPa num tanque aberto sob 100 kPa. Qual é a pressão absoluta?',['50 kPa.','100 kPa.','150 kPa.'],2,'A palavra absoluta pede que a referência atmosférica seja incluída.','Pergunte primeiro: “50 kPa em relação a quê?”. Separe visualmente acréscimo e total.','Escreva duas linhas: manométrica = 50 kPa; absoluta = 100 + 50 kPa.'),
q('Uma densidade de 2,6 g/cm³ significa 2,6 vezes a densidade aproximada da água, mas não identifica sozinha o material.','O que 2,6 g/cm³ permite afirmar com segurança?',['A peça é exatamente de alumínio.','Cada cm³ tem, em média, 2,6 g.','A peça sempre afunda, qualquer que seja o líquido.'],1,'A densidade caracteriza a relação massa/volume; identificar a substância exige mais evidências.','Depois da conta, peça uma interpretação verbal e uma comparação com a água.','Converta 780/300 em 2,6 e escreva a frase “2,6 g por cm³”.'),
q('A parcela ρgh é o aumento devido à água. Para obter a pressão absoluta, somamos a pressão atmosférica.','A 12 m de profundidade, ρgh = 120 kPa. Esse valor representa o quê?',['A pressão absoluta completa.','O acréscimo de pressão causado pela coluna de água.','A pressão atmosférica na superfície.'],1,'Pergunte se a atmosfera desapareceu quando o mergulhador entrou na água.','Separe o cálculo em duas caixas: acréscimo e pressão total.','Escreva Δp = 120 kPa e p_abs = 100 + 120 = 220 kPa.'),
q('Hidrostática se organiza por cinco ideias: densidade, pressão, atmosfera, desnível vertical e escolha da referência de pressão.','Qual pergunta deve vir antes de aplicar uma fórmula de pressão?',['Qual é a referência e quais pontos estou comparando?','Qual é o recipiente mais bonito?','Posso usar qualquer distância do desenho?'],0,'A fórmula só ganha sentido depois de identificar sistema, pontos e referência.','Use a síntese para a turma reconstruir a sequência, sem apenas reler fórmulas.','Faça um mapa com densidade → pressão → atmosfera → Stevin → pressão absoluta.')
],
'pascal-arquimedes':[
q('O princípio de Pascal diz que uma variação de pressão aplicada a um fluido confinado é transmitida pelo fluido.','O que se transmite de um êmbolo ao outro numa prensa ideal?',['A mesma força.','A variação de pressão.','O mesmo deslocamento.'],1,'Força e deslocamento podem mudar porque as áreas são diferentes.','Comece com a seringa fechada e insista na expressão “variação de pressão”, não “força transmitida”.','Escreva Δp₁ = Δp₂ antes de qualquer razão entre forças e áreas.'),
q('Na prensa ideal, F₁/A₁ = F₂/A₂. Se a área de saída é vinte vezes maior, a força de saída é vinte vezes maior.','A₂ é quatro vezes A₁. Na situação ideal, como F₂ se compara a F₁?',['F₂ é quatro vezes F₁.','F₂ é um quarto de F₁.','As forças são sempre iguais.'],0,'A mesma pressão multiplicada por uma área quatro vezes maior produz uma força quatro vezes maior.','Faça a turma marcar a razão entre as áreas antes de substituir números.','Desenhe duas colunas: área ×4; força ×4.'),
q('O êmbolo maior anda menos porque o volume deslocado é conservado: A₁d₁ = A₂d₂. A máquina troca caminho por força.','Se A₂ é quatro vezes A₁, qual deslocamento ocorre na saída?',['d₂ é quatro vezes d₁.','d₂ é igual a d₁.','d₂ é um quarto de d₁.'],2,'O mesmo volume precisa caber numa área maior.','Use dois retângulos de mesma área gráfica para mostrar volumes iguais. Relacione força maior com percurso menor.','Escreva área ×4 → deslocamento ÷4 e depois Fd como comparação de trabalho ideal.'),
q('Freios, elevadores e prensas usam a transmissão da variação de pressão e diferenças de área para produzir efeitos úteis.','Num freio hidráulico, o fluido serve principalmente para:',['transmitir a variação de pressão até as rodas.','criar energia dentro do circuito.','diminuir obrigatoriamente a força nas rodas.'],0,'O sistema redistribui força e deslocamento; não cria energia.','Relacione cada aplicação ao mesmo esquema de dois êmbolos. Destaque perdas nos sistemas reais.','Faça uma tabela: aplicação, entrada, fluido, saída.', 'Sugestões para a aula: comparar um içamento de edifício com macacos hidráulicos e o levantamento de um viaduto. Antes de incorporar vídeos, conferir fonte, contexto e permissão de uso.'),
q('O empuxo surge porque a pressão na parte inferior do corpo é maior que na parte superior. Ele equivale ao peso do fluido deslocado.','Por que aparece uma força resultante para cima num corpo imerso?',['Porque o líquido só empurra a base.','Porque a pressão inferior é maior que a superior.','Porque o peso do corpo desaparece.'],1,'O líquido também empurra a parte de cima; compare as intensidades.','Construa o empuxo a partir das setas de pressão antes de apresentar E = ρgV.','Desenhe setas menores em cima, maiores embaixo e laterais que se cancelam.'),
q('Para calcular o empuxo, use o volume de fluido deslocado em metros cúbicos: E = ρgV_deslocado.','Um corpo totalmente imerso desloca 2 L. Qual volume entra na fórmula em unidades SI?',['2 m³.','0,002 m³.','2.000 m³.'],1,'Cada litro corresponde a 10⁻³ m³.','Faça a conversão antes de colocar qualquer número na fórmula. Depois dê dimensão aos 20 N.','Escreva 2 L = 2 × 10⁻³ m³ em uma linha isolada.'),
q('O movimento depende da comparação entre empuxo e peso: E>P faz subir, E<P faz afundar e E=P permite equilíbrio.','Um corpo está livre e recebe empuxo menor que o peso. Qual é a tendência inicial?',['Subir.','Permanecer necessariamente parado.','Afundar.'],2,'Observe o sentido da força resultante.','Peça que os estudantes desenhem apenas duas setas antes de falar em densidade.','Desenhe E para cima e P para baixo em três comparações.'),
q('O peso gravitacional continua existindo. O empuxo reduz a parcela que o instrumento precisa sustentar: P_ap = P − E.','P = 30 N e E = 20 N. Qual peso aparente o dinamômetro indica no equilíbrio?',['10 N.','20 N.','50 N.'],0,'O instrumento sustenta a parte do peso que não foi compensada pelo empuxo.','Não diga que o corpo perdeu peso. Compare uma pessoa sustentada fora e dentro da piscina e varie o volume submerso de uma bola.','Desenhe P para baixo e E para cima; escreva P_ap = P − E. Se usar T no diagrama, explique que, nesse equilíbrio, T tem o mesmo valor da leitura aparente.'),
q('Antes da conta da prensa, compare as áreas. A razão entre elas antecipa a razão entre as forças.','Se A₂/A₁ = 5, qual previsão deve orientar a conta ideal?',['F₂/F₁ = 5.','F₂/F₁ = 1/5.','F₂ = F₁.'],0,'Na mesma variação de pressão, força é proporcional à área.','Use o roteiro dentro do exercício, sem transformá-lo em uma página separada.','Circule A₂/A₁ e escreva a mesma razão ao lado de F₂/F₁.'),
q('No problema de empuxo, desenhe as forças, use o volume realmente mergulhado e só então escreva a equação de equilíbrio.','Qual volume entra no cálculo do empuxo de um corpo parcialmente imerso?',['O volume total do corpo em qualquer situação.','Somente o volume que está dentro do fluido.','O volume do recipiente.'],1,'Empuxo depende de quanto fluido foi deslocado.','Faça a turma sombrear a parte submersa antes de escolher V.','Escreva V_deslocado = V_submerso.'),
q('Pascal trata da transmissão da variação de pressão; Arquimedes trata da resultante causada pela diferença de pressão ao redor de um corpo.','Qual associação está correta?',['Pascal: empuxo; Arquimedes: prensa hidráulica.','Pascal: transmissão de pressão; Arquimedes: empuxo.','Os dois princípios afirmam exatamente a mesma coisa.'],1,'Os dois usam pressão, mas respondem a perguntas diferentes.','Feche a aula pedindo uma frase para cada princípio e uma conexão entre elas.','Faça duas colunas com pergunta central, relação e aplicação.')
],
dilatacao:[
q('Ao aquecer muitos materiais, as partículas não incham; aumenta, em média, a distância entre elas.','O que geralmente aumenta quando um sólido é aquecido?',['O tamanho de cada átomo.','A distância média entre as partículas.','A quantidade de matéria.'],1,'Imagine os mesmos pontos um pouco mais afastados, sem criar novos pontos.','Diferencie partícula de espaçamento e avise que o movimento da animação foi ampliado para ficar visível.','Desenhe os mesmos pontos em duas temperaturas, mantendo a quantidade de partículas.'),
q('Celsius e kelvin podem representar o mesmo estado. A diferença entre duas temperaturas tem o mesmo valor numérico em °C e K.','Uma variação de 20 °C corresponde a qual variação em kelvin?',['20 K.','293 K.','253 K.'],0,'Ao subtrair a temperatura final da inicial, o deslocamento de 273,15 aparece nos dois termos e se cancela.','Separe temperatura medida de variação de temperatura. Use T_C e T_K; não use teta para Celsius.','Escreva T_K = T_C + 273,15 e, abaixo, ΔT_K = ΔT_C.'),
q('Na dilatação linear, o comprimento inicial, o material e a variação de temperatura determinam a mudança de comprimento.','Se apenas o comprimento inicial dobra, mantendo material e ΔT, o que acontece com ΔL?',['Também dobra.','Cai pela metade.','Não muda.'],0,'Compare duas barras do mesmo material: a barra maior reúne mais trechos que podem se expandir.','Construa a fórmula a partir das três dependências. Feche o exemplo distinguindo ΔL de L final e comparando 2,4 mm com uma medida conhecida.','Escreva ΔL = L₀ α ΔT e depois L = L₀ + ΔL.'),
q('Comprimento, área e volume seguem a mesma estrutura. O que muda é a dimensão observada e o coeficiente correspondente.','A questão fornece α e pede dilatação volumétrica. Qual cuidado é necessário?',['Usar α diretamente como γ.','Usar γ ≈ 3α antes da conta.','Dividir α por três.'],1,'Uma placa responde em duas direções; um corpo responde em três.','Use a placa vista de frente e depois um bloco. Mostre β ≈ 2α e γ ≈ 3α como aproximações para pequenas dilatações em sólidos isotrópicos.','Alinhe ΔL, ΔA e ΔV e destaque: variação = valor inicial × coeficiente × ΔT.'),
q('Um furo numa placa aquecida uniformemente aumenta como se estivesse preenchido pelo mesmo material.','Ao aquecer uniformemente uma arruela, o furo central tende a:',['aumentar.','diminuir.','permanecer exatamente igual.'],0,'Imagine preencher o furo, aquecer toda a placa e retirar novamente o disco imaginário.','Recolha a previsão antes da explicação. Confronte a ideia de que o material necessariamente avança para dentro do furo.','Desenhe a arruela antes e depois, preservando a semelhança geométrica.'),
q('Se a dilatação livre é impedida, o comprimento pode não mudar, mas surgem esforços internos.','Uma barra aquecida entre apoios rígidos não se alonga. Isso significa que o aquecimento não teve efeito?',['Sim.','Não. Podem surgir esforços internos.','Somente se a barra for metálica.'],1,'Compare o que a barra tentaria fazer livremente com o que os apoios permitem.','Diferencie dilatação livre de deformação efetiva. Não transforme a fórmula escolar em cálculo de segurança estrutural.','Desenhe uma barra livre e outra travada entre paredes; marque a folga que a primeira precisaria.'),
q('Numa lâmina bimetálica aquecida, o metal com maior coeficiente tenta ficar mais comprido e ocupa o lado externo da curva; a lâmina se curva para o metal que dilata menos.','No aquecimento, α_A é maior que α_B. Para qual lado a lâmina se curva?',['Para o lado de A, que tenta ficar mais comprido.','Para o lado de B, que dilata menos.','Ela permanece reta porque os metais estão unidos.'],1,'O lado de fora da curva percorre um caminho maior. Qual metal precisa desse caminho?','Use duas fitas ou o laboratório. Primeiro compare os comprimentos que cada metal teria se estivesse livre; depois una mentalmente as tiras. Ao resfriar, peça uma nova previsão porque o sentido se inverte.','Desenhe A no lado externo, B no interno e escreva: aquecimento → curva para o menor α.'),
q('Num frasco cheio, o líquido aumenta de volume e o recipiente também ganha capacidade. O transbordamento mostra a diferença entre essas mudanças.','Se o líquido aumenta 9 mL e o recipiente ganha 3 mL de capacidade, quanto transborda?',['3 mL.','6 mL.','12 mL.'],1,'Parte da expansão do líquido ocupa a nova capacidade do frasco.','Use cores distintas para a expansão do líquido e do recipiente. Só apresente a subtração depois de a turma explicar o destino dos 3 mL.','Escreva: real 9 mL; recipiente 3 mL; aparente 6 mL.'),
q('O coeficiente aparente reúne o que conseguimos observar em relação ao recipiente: γ_ap ≈ γ_líquido − γ_recipiente.','Se líquido e recipiente tivessem o mesmo coeficiente volumétrico, o transbordamento ideal seria:',['positivo e grande.','aproximadamente zero.','igual à dilatação real do líquido.'],1,'As duas expansões teriam o mesmo tamanho; uma acompanharia a outra.','Retome o desenho da etapa anterior sem repetir toda a explicação. Agora o objetivo é traduzir a diferença para os coeficientes.','Escreva três setas: líquido, recipiente e diferença observada.'),
q('A água tem densidade máxima perto de 4 °C. Abaixo disso, a água que esfria torna-se menos densa; o gelo também é menos denso e permanece na superfície.','Por que um lago começa a congelar pela superfície?',['A água mais fria sempre afunda.','A água abaixo de 4 °C e o gelo permanecem nas regiões superiores por serem menos densos.','A gravidade deixa de atuar na água fria.'],1,'Pense no que acontece com a densidade quando uma mesma massa ocupa mais volume.','Comece pela pergunta do lago. Relacione a circulação da água ao exemplo de massas de ar, mas deixe claro que a água muda de comportamento perto de 4 °C.','Desenhe o lago em três momentos: resfriamento até 4 °C, água mais fria na superfície e formação do gelo.'),
q('Resolver dilatação linear exige identificar a grandeza, calcular ΔT, usar α, distinguir ΔL de L final e avaliar a ordem de grandeza.','Antes de calcular, qual previsão é razoável para uma barra metálica de alguns metros aquecida em 100 °C?',['Uma mudança de poucos milímetros.','Uma mudança de vários metros.','Nenhuma mudança possível.'],0,'Coeficientes de metais comuns são pequenos; a variação costuma representar uma pequena fração do comprimento.','Use o roteiro dentro do próprio exercício. Marque cada item conforme ele entra na resolução e termine comparando o resultado com o comprimento inicial.','Organize cinco linhas: pedido, ΔT, coeficiente, cálculo e comparação.'),
q('Na dilatação aparente, primeiro damos nome à expansão do líquido e à nova capacidade do recipiente; só depois calculamos a diferença visível.','Qual procedimento evita confundir dilatação real e aparente?',['Dar nome a cada parcela antes de subtrair.','Somar sempre as duas dilatações.','Ignorar o recipiente.'],0,'Pergunte qual parcela pertence ao líquido e qual pertence ao frasco.','Use o roteiro dentro do exercício e retorne ao desenho do coletor. Não revele a subtração antes de o estudante identificar as parcelas.','Use caixas para ΔV_líquido, ΔV_recipiente e ΔV_aparente.'),
q('Para resolver dilatação, identificamos a dimensão, escolhemos o coeficiente compatível, calculamos ΔT e verificamos sinal, unidade e ordem de grandeza.','Qual sequência é mais segura?',['Escolher qualquer fórmula e substituir os números.','Identificar dimensão, coeficiente, ΔT e depois interpretar o resultado.','Converter todas as grandezas para quilogramas.'],1,'A fórmula só funciona quando cada símbolo corresponde ao que o problema realmente pede.','Peça aos estudantes que reconstruam o mapa de decisão e deem um exemplo de erro que cada etapa evita.','Faça um fluxograma: dimensão → coeficiente → ΔT → cálculo → sentido físico.')
]};

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])).replace(/([A-Za-z])_([A-Za-z0-9]+)/g,'<i>$1</i><sub>$2</sub>').replace(/([αβγρΔ])_([A-Za-z0-9]+)/g,'$1<sub>$2</sub>');
MM.getModeScene=(lesson,index)=>MM.modeContent[lesson.id]?.[index]||q(`A ideia central desta etapa é ${lesson.slides[index].title.toLowerCase()}.`,'Qual ideia melhor resume o que acabou de ser apresentado?',['A relação mostrada na explicação.','Uma afirmação sem ligação com o fenômeno.','Uma conclusão que troca as grandezas.'],0,'Volte ao título e identifique quais grandezas estão sendo comparadas.','Conduza a turma do fenômeno para a relação física e só então sintetize.','Registre a relação central e o significado de cada grandeza.');
const activity=(data,mode)=>`<section class="active-prompt" data-mode-activity data-correct="${data.correct}" data-mode="${mode}"><p class="pedagogy-label">Faça uma previsão</p><p class="prediction-note">Você ainda não precisa saber a resposta. Escolha o que imagina agora; depois da explicação, compare novamente.</p><h2>${esc(data.prompt)}</h2><fieldset><legend class="sr-only">Escolha uma resposta</legend>${data.choices.map((choice,i)=>`<label><input type="radio" name="mode-question" value="${i}"><span>${esc(choice)}</span></label>`).join('')}</fieldset><div class="active-actions"><button class="primary" data-mode-check>Registrar minha previsão</button><button data-mode-hint aria-expanded="false">Quero uma pista</button></div><p class="mode-hint" hidden>${esc(data.hint)}</p><div class="mode-feedback" role="status" aria-live="polite"></div></section>`;
const takeaway=data=>`<aside class="takeaway" data-takeaway><span>Ou seja</span><p>${esc(data.summary)}</p></aside>`;
MM.renderModeBody=(lesson,index,mode,html)=>{const data=MM.getModeScene(lesson,index),studentActivity=activity(data,mode);if(mode==='professor')return `<div class="teacher-stage"><section class="classroom-preview"><p class="pedagogy-label">O que a turma recebe</p>${studentActivity}</section><aside class="teacher-guide"><p class="pedagogy-label">Manual do professor</p><section><h2>Objetivo desta etapa</h2><p>${esc(data.summary)}</p></section><section><h2>Como conduzir</h2><p>${esc(data.focus)}</p><p><strong>Primeiro recolha as previsões sem corrigir. Volte a elas depois da explicação.</strong></p></section><section><h2>Resposta da atividade</h2><p><strong>${esc(data.choices[data.correct])}</strong></p><p>${esc(data.hint)}</p></section><section><h2>Sugestão para a lousa</h2><p>${esc(data.board)}</p></section>${data.resource?`<section><h2>Repertório para a aula</h2><p>${esc(data.resource)}</p></section>`:''}${takeaway(data)}</aside></div><details class="supporting-explanation"><summary>Consultar a explicação completa</summary><div>${html}</div></details>`;if(mode==='aluno')return `${studentActivity}<details class="student-reference"><summary>Consultar a explicação e comparar minha previsão</summary><div>${html}</div></details>${takeaway(data)}`;return `${studentActivity}<div class="guided-explanation"><p class="pedagogy-label">Agora organize a ideia e compare sua previsão</p>${html}</div>${takeaway(data)}`;};
MM.initModePedagogy=root=>{root.querySelectorAll('[data-mode-activity]').forEach((box,boxIndex)=>{const correct=Number(box.dataset.correct),feedback=box.querySelector('.mode-feedback'),hint=box.querySelector('.mode-hint'),check=box.querySelector('[data-mode-check]'),hintButton=box.querySelector('[data-mode-hint]'),takeaway=box.closest('.slide')?.querySelector('[data-takeaway]');box.querySelectorAll('input').forEach(input=>input.name=`mode-question-${boxIndex}`);check?.addEventListener('click',()=>{const selected=box.querySelector('input:checked');if(!selected){feedback.innerHTML='<strong>Escolha uma previsão antes de continuar.</strong>';return;}const hit=Number(selected.value)===correct;feedback.innerHTML=hit?'<strong>Sua previsão coincide com a relação física.</strong><p>Agora veja a explicação e descubra por que ela funciona.</p>':'<strong>Previsão registrada.</strong><p>Não há problema em começar por outra ideia. Leia ou explore a explicação e depois volte para comparar o que mudou no seu raciocínio.</p>';check.textContent='Comparar novamente';box.classList.toggle('is-correct',hit);box.classList.toggle('needs-review',!hit);if(takeaway)takeaway.classList.add('is-revealed');});hintButton?.addEventListener('click',()=>{hint.hidden=!hint.hidden;hintButton.setAttribute('aria-expanded',String(!hint.hidden));hintButton.textContent=hint.hidden?'Quero uma pista':'Ocultar pista';});});};
})();
