/* Catálogo pedagógico, Teste-se e diagnóstico determinístico. */
(()=>{const MM=window.MM;
MM.skills={
  interpretar_variacao_termica:{label:'Interpretar variação de temperatura',chapter:'dilatacao',reviewScene:1},
  escolher_coeficiente:{label:'Relacionar α, β e γ',chapter:'dilatacao',reviewScene:3},
  aplicar_dilatacao_linear:{label:'Aplicar dilatação linear',chapter:'dilatacao',reviewScene:2},
  interpretar_orificios:{label:'Interpretar a expansão de orifícios',chapter:'dilatacao',reviewScene:4},
  distinguir_dilatacao_aparente:{label:'Distinguir dilatação real e aparente',chapter:'dilatacao',reviewScene:7},
  explicar_agua_anomala:{label:'Explicar o comportamento da água entre 0 °C e 4 °C',chapter:'dilatacao',reviewScene:9},
  interpretar_lamina_bimetalica:{label:'Prever a curvatura de uma lâmina bimetálica',chapter:'dilatacao',reviewScene:6}
};
MM.diagnosticMetadata={
  'DIL-01':{skills:['distinguir_dilatacao_aparente'],reviewScene:8},'DIL-02':{skills:['interpretar_lamina_bimetalica'],reviewScene:6},'DIL-03':{skills:['explicar_agua_anomala'],reviewScene:9},
  'DIL-06':{skills:['interpretar_lamina_bimetalica'],reviewScene:6},'DIL-08':{skills:['interpretar_orificios'],reviewScene:4},'DIL-10':{skills:['interpretar_lamina_bimetalica'],reviewScene:6},'DIL-13':{skills:['interpretar_lamina_bimetalica'],reviewScene:6},'DIL-18':{skills:['interpretar_lamina_bimetalica'],reviewScene:6},
  'DIL-14':{skills:['aplicar_dilatacao_linear'],reviewScene:2},'DIL-19':{skills:['distinguir_dilatacao_aparente'],reviewScene:8}
};
for(const q of MM.originalQuestions||[])if(MM.diagnosticMetadata[q.id])q.pedagogy=MM.diagnosticMetadata[q.id];
MM.testQuestions=[
 {id:'t-dil-1',skill:'interpretar_variacao_termica',type:'previsao',title:'O mesmo aquecimento em duas escalas',prompt:'Uma barra passa de 20 °C para 70 °C. Qual é a variação de temperatura em kelvin?',options:['50 K','293 K','343 K','323 K'],correct:0,errors:{1:'somou_273_a_variacao',2:'usou_temperatura_final_em_kelvin',3:'confundiu_estado_com_variacao'},help:['Compare apenas a diferença entre o estado final e o inicial.','Em Celsius, faça 70 − 20.','Uma variação de 1 °C tem o mesmo tamanho que uma variação de 1 K.'],explain:'A temperatura mudou 50 °C. Como o tamanho do intervalo é igual nas duas escalas, a variação é 50 K.'},
 {id:'t-dil-2',skill:'escolher_coeficiente',type:'conceitual',title:'Qual coeficiente entra?',prompt:'Uma questão fornece α e pede a variação de volume de um sólido isotrópico. Qual relação deve ser usada?',options:['γ ≈ α','γ ≈ 2α','γ ≈ 3α','γ ≈ α/3'],correct:2,errors:{0:'usou_alpha_no_lugar_de_gamma',1:'confundiu_area_com_volume',3:'inverteu_relacao_dos_coeficientes'},help:['Primeiro conte quantas dimensões estão variando.','Uma área envolve duas direções; um volume envolve três.','Para pequenas dilatações, β ≈ 2α e γ ≈ 3α.'],explain:'O volume sente a expansão nas três dimensões. Na aproximação escolar, γ ≈ 3α.'},
 {id:'t-dil-3',skill:'aplicar_dilatacao_linear',type:'calculo',title:'Uma barra aquecida',prompt:'Uma barra de 2 m tem α = 10 × 10⁻⁶ °C⁻¹ e é aquecida em 100 °C. Quanto aumenta seu comprimento?',options:['0,2 mm','2 mm','20 mm','200 mm'],correct:1,errors:{0:'erro_de_potencia_dez',2:'erro_de_potencia_dez',3:'ignorou_ordem_de_grandeza'},help:['A questão pede ΔL, não o comprimento final.','Use ΔL = L₀αΔT.','Calcule 2 × 10 × 10⁻⁶ × 100 m e depois converta metros para milímetros.'],explain:'ΔL = 2 × 10 × 10⁻⁶ × 100 = 0,002 m. Isso corresponde a 2 mm.'},
 {id:'t-dil-4',skill:'interpretar_orificios',type:'previsao',title:'O furo da placa',prompt:'Uma placa metálica com um furo circular é aquecida uniformemente. O que acontece com o furo?',options:['Diminui','Permanece igual','Aumenta como se fosse feito do mesmo material','Fecha e depois abre'],correct:2,errors:{0:'tratou_orificio_como_objeto_independente',1:'ignorou_expansao_geometrica',3:'inventou_mudanca_de_regime'},help:['Imagine que o furo estivesse preenchido pelo mesmo metal.','A placa inteira aumenta suas distâncias internas.','A borda do furo se afasta do centro.'],explain:'O furo acompanha a expansão da placa. Sua borda se afasta do centro, por isso o diâmetro aumenta.'},
 {id:'t-dil-5',skill:'distinguir_dilatacao_aparente',type:'interpretacao',title:'O líquido que transborda',prompt:'Um frasco cheio é aquecido junto com o líquido. O volume que transborda representa:',options:['A dilatação real do líquido','A dilatação do frasco','A diferença entre as dilatações do líquido e do frasco','O volume inicial do líquido'],correct:2,errors:{0:'ignorou_dilatacao_do_recipiente',1:'confundiu_capacidade_com_transbordamento',3:'confundiu_volume_inicial_com_variacao'},help:['O frasco também aumenta sua capacidade.','Parte da expansão do líquido ocupa o espaço criado pelo frasco.','O que transborda é ΔV do líquido menos ΔV do recipiente.'],explain:'O transbordamento mede a dilatação aparente: a expansão real do líquido descontada da expansão da capacidade do frasco.'},
 {id:'t-dil-6',skill:'explicar_agua_anomala',type:'conceitual',title:'Por que o lago congela por cima?',prompt:'Qual ideia explica a permanência de água líquida abaixo da camada de gelo?',options:['A água a 4 °C é menos densa e sempre sobe','A água tem densidade máxima perto de 4 °C e permanece nas regiões mais profundas','O gelo é mais denso e afunda','Toda a água do lago permanece exatamente a 0 °C'],correct:1,errors:{0:'inverteu_densidade_da_agua',2:'considerou_gelo_mais_denso',3:'ignorou_gradiente_termico'},help:['Compare a densidade da água líquida perto de 4 °C com a do gelo.','A porção mais densa tende a ocupar a região mais baixa.','A água tem densidade máxima perto de 4 °C; o gelo é menos denso.'],explain:'A água próxima de 4 °C é mais densa e tende a ficar no fundo. O gelo, menos denso, permanece na superfície e forma uma camada isolante.'}
];
Object.assign(MM.skills,{
  calcular_densidade:{label:'Relacionar massa, volume e densidade',chapter:'hidrostatica',reviewScene:1},
  interpretar_pressao:{label:'Relacionar força, área e pressão',chapter:'hidrostatica',reviewScene:3},
  aplicar_stevin:{label:'Usar o desnível vertical em Stevin',chapter:'hidrostatica',reviewScene:6},
  distinguir_pressao_absoluta:{label:'Distinguir pressão absoluta e manométrica',chapter:'hidrostatica',reviewScene:8},
  aplicar_pascal:{label:'Relacionar força e área em Pascal',chapter:'pascal-arquimedes',reviewScene:1},
  conservar_volume_hidraulico:{label:'Relacionar força, percurso e volume',chapter:'pascal-arquimedes',reviewScene:2},
  calcular_empuxo:{label:'Relacionar fluido deslocado e empuxo',chapter:'pascal-arquimedes',reviewScene:5},
  prever_flotacao:{label:'Comparar peso, empuxo e flutuação',chapter:'pascal-arquimedes',reviewScene:6}
});
const hydroQuestions=[
 {id:'t-hid-1',skill:'calcular_densidade',type:'calculo',title:'Massa por volume',prompt:'Uma peça tem 600 g e ocupa 200 cm³. Qual é sua densidade?',options:['0,33 g/cm³','3 g/cm³','300 g/cm³','800 g/cm³'],correct:1,errors:{0:'inverteu_massa_e_volume',2:'erro_de_divisao',3:'somou_massa_e_volume'},help:['Densidade compara quanta massa existe em cada unidade de volume.','Divida a massa pelo volume.','Faça 600 ÷ 200.'],explain:'ρ = 600/200 = 3 g/cm³.'},
 {id:'t-hid-2',skill:'interpretar_pressao',type:'previsao',title:'A mesma força em outra área',prompt:'A mesma força passa a atuar numa área duas vezes maior. O que acontece com a pressão média?',options:['Dobra','Cai pela metade','Permanece igual','Zera'],correct:1,errors:{0:'multiplicou_forca_por_area',2:'ignorou_area',3:'confundiu_reducao_com_ausencia'},help:['A força não mudou.','Pressão é força dividida pela área.','Se o denominador dobra, o resultado cai pela metade.'],explain:'Com F constante e área duas vezes maior, p = F/A fica duas vezes menor.'},
 {id:'t-hid-3',skill:'aplicar_stevin',type:'interpretacao',title:'Qual altura entra em Stevin?',prompt:'Um tubo inclinado liga dois pontos de um líquido. Qual distância deve entrar em Δp = ρgΔh?',options:['O comprimento total do tubo','O desnível vertical entre os pontos','A largura do tubo','A distância horizontal'],correct:1,errors:{0:'usou_percurso_no_lugar_do_desnivel',2:'usou_geometria_irrelevante',3:'usou_distancia_horizontal'},help:['A pressão muda quando subimos ou descemos.','O caminho feito pelo tubo não importa.','Marque uma linha horizontal em cada ponto e meça a separação vertical.'],explain:'Stevin usa o desnível vertical entre os pontos.'},
 {id:'t-hid-4',skill:'distinguir_pressao_absoluta',type:'calculo',title:'Pressão no fundo',prompt:'Num tanque aberto, a coluna de água acrescenta 40 kPa. Adote a atmosfera como 100 kPa. Qual é a pressão absoluta?',options:['40 kPa','60 kPa','100 kPa','140 kPa'],correct:3,errors:{0:'respondeu_pressao_manometrica',1:'subtraiu_atmosfera',2:'ignorou_coluna_liquida'},help:['O tanque já começa sob pressão atmosférica.','Pressão absoluta inclui a atmosfera e o acréscimo do líquido.','Some 100 kPa e 40 kPa.'],explain:'p_abs = p_atm + ρgh = 100 + 40 = 140 kPa.'}
];
const pascalQuestions=[
 {id:'t-pa-1',skill:'aplicar_pascal',type:'calculo',title:'A força no êmbolo maior',prompt:'O segundo êmbolo tem área cinco vezes maior. Num sistema ideal, uma força de 40 N na entrada produz qual força na saída?',options:['8 N','40 N','200 N','1.000 N'],correct:2,errors:{0:'inverteu_razao_de_areas',1:'ignorou_razao_de_areas',3:'multiplicou_duas_vezes'},help:['A mudança de pressão é a mesma nos dois êmbolos.','Use F₁/A₁ = F₂/A₂.','Se a área é cinco vezes maior, a força ideal também é cinco vezes maior.'],explain:'F₂ = 5 × 40 = 200 N.'},
 {id:'t-pa-2',skill:'conservar_volume_hidraulico',type:'previsao',title:'Força maior, caminho menor',prompt:'Se o êmbolo de saída tem área dez vezes maior, como seu deslocamento se compara ao da entrada?',options:['É dez vezes maior','É dez vezes menor','É igual','Não se move'],correct:1,errors:{0:'confundiu_forca_com_percurso',2:'ignorou_conservacao_volume',3:'interpretou_area_maior_como_bloqueio'},help:['O líquido deslocado deve ocupar o mesmo volume dos dois lados.','Use A₁d₁ = A₂d₂.','Área dez vezes maior exige percurso dez vezes menor.'],explain:'O ganho de força é acompanhado por uma redução do percurso.'},
 {id:'t-pa-3',skill:'calcular_empuxo',type:'conceitual',title:'De onde vem o empuxo?',prompt:'Por que um fluido exerce uma força resultante para cima sobre um corpo mergulhado?',options:['Porque não existe pressão na parte superior','Porque a pressão na parte inferior é maior','Porque o peso do corpo desaparece','Porque toda pressão aponta para cima'],correct:1,errors:{0:'ignorou_pressao_superior',2:'confundiu_empuxo_com_desaparecimento_do_peso',3:'ignorou_direcoes_da_pressao'},help:['A pressão atua por todos os lados.','Compare a profundidade da parte superior com a inferior.','A região inferior está mais profunda e recebe maior pressão.'],explain:'A diferença de pressão entre a parte inferior e a superior produz uma resultante para cima.'},
 {id:'t-pa-4',skill:'prever_flotacao',type:'previsao',title:'Empuxo maior que o peso',prompt:'Um corpo totalmente mergulhado recebe empuxo maior que seu peso. Qual é a tendência inicial?',options:['Subir','Descer','Permanecer parado obrigatoriamente','Perder massa'],correct:0,errors:{1:'inverteu_resultante',2:'ignorou_forca_resultante',3:'confundiu_forca_com_massa'},help:['Desenhe peso para baixo e empuxo para cima.','Compare o tamanho das duas setas.','A força resultante aponta para o lado da maior força.'],explain:'Com empuxo maior que o peso, a resultante aponta para cima.'}
];
MM.testSets={dilatacao:MM.testQuestions,hidrostatica:hydroQuestions,'pascal-arquimedes':pascalQuestions};
MM.testState={};
const teacherTestPage=lesson=>{const questions=MM.testSets[lesson.id];return `<section class="test-page teacher-test-page section-wrap" data-test-chapter="${lesson.id}" data-test-mode="professor" tabindex="-1"><header class="test-heading"><a href="#mapa/${lesson.id}/-1/professor">← Voltar ao mapa</a><p class="eyebrow">Manual de avaliação / ${lesson.title}</p><h1>O que observar nas respostas</h1><p>Esta tela não avalia o professor. Ela mostra o que cada questão investiga, a resposta esperada, os erros que podem aparecer e o ponto da aula que pode ser retomado.</p></header><div class="teacher-assessment-grid">${questions.map((q,i)=>{const skill=MM.skills[q.skill],errors=Object.entries(q.errors||{});return `<article class="teacher-assessment"><header><span>${String(i+1).padStart(2,'0')}</span><div><small>${q.type} · ${skill.label}</small><h2>${q.title}</h2></div></header><p class="teacher-question">${q.prompt}</p><ol class="teacher-options" type="A">${q.options.map((o,n)=>`<li class="${n===q.correct?'is-answer':''}">${o}${n===q.correct?'<strong>Resposta esperada</strong>':''}</li>`).join('')}</ol><section><h3>O que observar</h3><p>${q.explain}</p></section>${errors.length?`<section><h3>Erros que a questão pode revelar</h3><ul>${errors.map(([n,e])=>`<li><strong>Alternativa ${String.fromCharCode(65+Number(n))}:</strong> ${e.replaceAll('_',' ')}.</li>`).join('')}</ul></section>`:''}<section><h3>Pistas disponíveis ao estudante</h3><ol>${q.help.map(x=>`<li>${x}</li>`).join('')}</ol></section><a class="secondary" href="#aula/${skill.chapter}/${skill.reviewScene}/professor">Abrir o ponto da aula</a></article>`}).join('')}</div></section>`;};
MM.testPage=(lesson,mode='autodidata')=>mode==='professor'?teacherTestPage(lesson):`<section class="test-page section-wrap" data-test-chapter="${lesson.id}" data-test-mode="${mode}" tabindex="-1"><header class="test-heading"><a href="#mapa/${lesson.id}/-1/${mode}">← Voltar ao mapa</a><p class="eyebrow">Teste-se / ${lesson.title}</p><h1>Descubra o que você já entendeu</h1><p>Este teste observa habilidades diferentes. Você pode pedir ajuda, revisar um ponto e tentar novamente. Não há nota nem cronômetro.</p></header><div class="test-progress"><span></span><p aria-live="polite"></p></div><div class="test-host"></div></section>`;
MM.initTestPage=root=>{const page=root.querySelector('.test-page');if(!page||page.dataset.testMode==='professor')return;const lessonId=page.dataset.testChapter,host=root.querySelector('.test-host'),bar=root.querySelector('.test-progress span'),status=root.querySelector('.test-progress p'),state=MM.testState[lessonId]||(MM.testState[lessonId]={answers:{},help:{},checked:{}}),questions=MM.testSets[lessonId];let current=Math.min(Number(sessionStorage.getItem(`mm-test-index-${lessonId}`)||0),questions.length);
 const level=q=>state.help[q.id]||0;
 const renderQuestion=()=>{const q=questions[current],answer=state.answers[q.id];bar.style.width=`${current/questions.length*100}%`;status.textContent=`Questão ${current+1} de ${questions.length}`;host.innerHTML=`<article class="diagnostic-question" data-id="${q.id}"><div class="question-kicker"><span>${q.type}</span><span>${MM.skills[q.skill].label}</span></div><h2>${q.title}</h2><p class="diagnostic-prompt">${q.prompt}</p><fieldset><legend class="sr-only">Alternativas</legend>${q.options.map((o,i)=>`<label class="answer"><input type="radio" name="${q.id}" value="${i}" ${answer===i?'checked':''}><span>${String.fromCharCode(65+i)}) ${o}</span></label>`).join('')}</fieldset><div class="diagnostic-actions"><button class="primary" data-test-check>Conferir resposta</button><button data-test-help>Não entendi</button></div><div class="help-ladder" aria-live="polite">${level(q)?`<small>Ajuda ${level(q)} de ${q.help.length}</small><p>${q.help[level(q)-1]}</p>`:'<p>As ajudas aparecem uma de cada vez e não entregam a solução logo no início.</p>'}</div><div class="diagnostic-feedback" role="status"></div></article>`;};
 const renderReport=()=>{bar.style.width='100%';status.textContent='Teste concluído';const rows=questions.map(q=>({q,answer:state.answers[q.id],correct:state.answers[q.id]===q.correct,error:q.errors[state.answers[q.id]]})),good=rows.filter(x=>x.correct),review=rows.filter(x=>!x.correct),evidence=rows.length;host.innerHTML=`<section class="diagnostic-report"><p class="eyebrow">Seu mapa de aprendizagem</p><h2>O que fazer agora</h2><p class="report-summary">Foram observadas ${evidence} habilidades nesta tentativa. O relatório descreve essas respostas; ele não cria rótulos sobre você.</p><div class="report-columns"><article><h3>Você já demonstrou</h3>${good.length?good.map(x=>`<div class="skill-result is-good"><strong>${MM.skills[x.q.skill].label}</strong><p>Há uma evidência correta nesta atividade. Novas questões podem confirmar esse domínio.</p></div>`).join(''):'<p>Ainda precisamos de mais evidências. Isso é apenas o resultado desta tentativa.</p>'}</article><article><h3>Vale revisar</h3>${review.length?review.map(x=>{const skill=MM.skills[x.q.skill];return `<div class="skill-result"><strong>${skill.label}</strong><p>${x.error?`Nesta tentativa apareceu o padrão: ${x.error.replaceAll('_',' ')}.`:'Ainda não houve resposta suficiente para esta habilidade.'}</p><a href="#aula/${skill.chapter}/${skill.reviewScene}/autodidata/teste">Revisar este ponto</a></div>`}).join(''):'<p>Nesta tentativa, todas as habilidades avaliadas tiveram resposta correta.</p>'}</article></div><div class="report-actions"><button class="primary" data-test-retry>Fazer uma nova tentativa</button><a class="secondary" href="#mapa/${lessonId}">Voltar ao mapa</a></div></section>`;};
 const draw=()=>current>=questions.length?renderReport():renderQuestion();
 host.onclick=e=>{const q=questions[current];if(e.target.closest('[data-test-help]')){state.help[q.id]=Math.min(level(q)+1,q.help.length);draw();return;}if(e.target.closest('[data-test-check]')){const selected=host.querySelector('input:checked'),out=host.querySelector('.diagnostic-feedback');if(!selected){out.textContent='Escolha uma alternativa antes de conferir.';return;}const value=Number(selected.value);state.answers[q.id]=value;state.checked[q.id]=true;out.innerHTML=`<strong>${value===q.correct?'Você construiu a ideia corretamente.':'Esta tentativa mostra um ponto que merece atenção.'}</strong><p>${value===q.correct?q.explain:'Leia a ajuda seguinte ou revise a ideia depois do teste. A resposta não define o que você sabe; ela é uma evidência desta tentativa.'}</p><button data-test-next>${current===questions.length-1?'Ver meu diagnóstico':'Continuar'}</button>`;return;}if(e.target.closest('[data-test-next]')){current++;sessionStorage.setItem(`mm-test-index-${lessonId}`,String(current));draw();return;}if(e.target.closest('[data-test-retry]')){state.answers={};state.help={};state.checked={};current=0;sessionStorage.setItem(`mm-test-index-${lessonId}`,'0');draw();}};
 host.onchange=e=>{if(e.target.matches('input[type=radio]'))state.answers[questions[current].id]=Number(e.target.value)};draw();};
})();
