/* Laboratórios locais. Os efeitos geométricos são esquemáticos; os valores
   seguem as hipóteses explicitadas no conteúdo. Nenhuma dependência externa. */
window.MMLabs=(()=>{
const $=(s,r)=>r.querySelector(s),$$=(s,r)=>[...r.querySelectorAll(s)];
const C={cream:'#FBF9E7',gold:'#FDB813',blue:'#82C8E5',green:'#7CFC00',ink:'#102B36',dim:'#42616d'};
const fmt=(v,d=1)=>Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const text=(x,y,t,color=C.cream,size=15,anchor='start')=>`<text class="${size<=13&&String(t).length>30?'diagram-caption':'diagram-label'}" x="${x}" y="${y}" fill="${color}" font-size="${size}" text-anchor="${anchor}">${t}</text>`;
const sub=(a,b)=>`${a}<tspan baseline-shift="sub" font-size="11">${b}</tspan>`;
const line=(x,y,X,Y,color=C.dim,width=1,extra='')=>`<line x1="${x}" y1="${y}" x2="${X}" y2="${Y}" stroke="${color}" stroke-width="${width}" ${extra}/>`;
const rect=(x,y,w,h,color,extra='')=>`<rect x="${x}" y="${y}" width="${Math.max(0,w)}" height="${Math.max(0,h)}" fill="${color}" ${extra}/>`;
const arrow=(x,y,X,Y,color=C.gold,width=2)=>{const a=Math.atan2(Y-y,X-x),l=7;return line(x,y,X,Y,color,width)+`<path d="M${X-l*Math.cos(a-.5)},${Y-l*Math.sin(a-.5)}L${X},${Y}L${X-l*Math.cos(a+.5)},${Y-l*Math.sin(a+.5)}" fill="none" stroke="${color}" stroke-width="${width}"/>`;};
const svg=(b,label)=>`<svg viewBox="0 0 600 340" role="img" aria-label="${label}"><defs><linearGradient id="water-shade" x2="0" y2="1"><stop stop-color="#82C8E5" stop-opacity=".32"/><stop offset="1" stop-color="#82C8E5" stop-opacity=".08"/></linearGradient><linearGradient id="metal-shade"><stop stop-color="#FDB813"/><stop offset=".5" stop-color="#FBF9E7"/><stop offset="1" stop-color="#b47b00"/></linearGradient></defs>${b}</svg>`;
const grid=()=>Array.from({length:7},(_,i)=>line(35,45+i*40,565,45+i*40,'#ffffff0a')).join('');
const range=(id,label,min,max,val,step=1,unit='')=>`<div class="control"><div class="control-line"><label for="${id}">${label}</label><output for="${id}" data-value="${id}"></output></div><input id="${id}" type="range" min="${min}" max="${max}" value="${val}" step="${step}" data-unit="${unit}"></div>`;
const select=(id,label,options)=>`<div class="control-line"><label for="${id}">${label}</label><select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></div>`;
const stats=(...xs)=>`<div class="readouts">${xs.map(([a,b])=>`<div class="readout"><small>${a}</small><strong>${b}</strong></div>`).join('')}</div>`;
const status=(s)=>`<p class="sim-explanation">${s}</p>`;
const chain=(...xs)=>`<div class="causal-strip" aria-label="Cadeia de causa e efeito">${xs.map((x,i)=>`<span>${x}${i<xs.length-1?'<b aria-hidden="true">→</b>':''}</span>`).join('')}</div>`;
function mount(el,cache,key){
 const type=el.dataset.lab,host=$('.lab-body',el);const saved=cache.get(key+'|v2|'+type)||{};cache.set(key+'|v2|'+type,saved);
 let controls='', raf=0, motion=null, current={},lastFrame=0, phase=0;
 switch(type){
 case 'depth':controls=select('fluid','Líquido',[[1000,'Água · 1.000 kg/m³'],[800,'Óleo · 800 kg/m³'],[13600,'Mercúrio · 13.600 kg/m³']])+range('depth','Profundidade do sensor',0,10,3,.1,'m')+`<div class="sim-actions scenarios"><button data-mark>Marcar esta leitura</button><button data-clear-mark>Limpar comparação</button></div>`;break;
 case 'density':controls=range('mass','Massa do corpo',100,2000,600,50,'g')+range('volume','Volume externo',100,2000,1000,50,'cm³')+`<div class="sim-actions scenarios"><button data-density="600">Menos denso</button><button data-density="1000">Igual à água</button><button data-density="1400">Mais denso</button></div>`;break;
 case 'pressure':controls=range('force','Força aplicada',10,1000,300,10,'N')+range('area','Área de contato',10,200,100,5,'cm²')+`<div class="sim-actions scenarios"><button data-pressure="wide">Chapa larga</button><button data-pressure="narrow">Apoio estreito</button><button data-pressure="knife">Fio de faca</button></div><button data-replay>Repetir carregamento</button>`;break;
 case 'pascal':controls=`<div class="pascal-journey"><section class="sim-step"><span class="sim-step-number">1</span><div><strong>Faça uma previsão</strong><p>Ao aumentar a área do êmbolo de saída, o que deve acontecer com a força produzida?</p></div></section><div class="sim-actions prediction-actions" role="group" aria-label="Previsão sobre a força de saída"><button data-pascal-predict="same">Fica igual</button><button data-pascal-predict="greater">Fica maior</button><button data-pascal-predict="smaller">Fica menor</button></div><p class="pascal-prediction" role="status" aria-live="polite">Escolha uma hipótese antes de mover os controles.</p><section class="sim-step"><span class="sim-step-number">2</span><div><strong>Monte o cenário</strong><p>Altere uma grandeza por vez e acompanhe a reação do sistema.</p></div></section></div>`+range('force','Força aplicada no êmbolo menor',10,200,80,10,'N')+range('ratio','Quantas vezes a área de saída é maior?',1,20,10,1,'')+`<div class="sim-actions scenarios" aria-label="Cenários rápidos"><button data-ratio="1">Áreas iguais</button><button data-ratio="5">Saída 5× maior</button><button data-ratio="20">Saída 20× maior</button></div><section class="sim-step sim-step-action"><span class="sim-step-number">3</span><div><strong>Observe a causa e a resposta</strong><p>Mostre primeiro a pressão chegando ao fluido inteiro. Depois acione a prensa e compare os percursos.</p></div></section><div class="sim-actions"><button class="primary-lab-action" data-propagation aria-pressed="false">Mostrar a pressão se espalhando</button><button data-stroke>Acionar a prensa</button></div>`;break;
 case 'buoyancy':controls=`<p class="sim-instruction"><strong>Faça uma previsão:</strong> compare a densidade do corpo com a da água e imagine o sentido do movimento.</p>`+range('bodydensity','Densidade média do bloco',200,1600,600,50,'kg/m³')+range('submerged','Quanto do bloco começa mergulhado?',0,100,100,5,'%')+`<div class="sim-actions scenarios" aria-label="Comparações rápidas de densidade"><button data-buoyancy="600">Menos denso</button><button data-buoyancy="1000">Mesma densidade</button><button data-buoyancy="1400">Mais denso</button></div><button data-release>Soltar o bloco</button>`;break;
 case 'particles':controls=select('unit','Escala de temperatura',[['C','Celsius (°C)'],['K','Kelvin (K)']])+range('temperature','Temperatura',-273.15,326.85,20,.01,'°C')+`<div class="sim-actions"><button data-zero-c>0 °C</button><button data-zero-k>0 K · explorar limite</button><button data-extreme>∞ · e se?</button><button data-pause aria-pressed="false">Pausar movimento</button></div><div class="zero-message" hidden></div>`;break;
 case 'bar':controls=select('material','Material e coeficiente α',[[12,'Aço · 12 × 10⁻⁶ °C⁻¹'],[23,'Alumínio · 23 × 10⁻⁶ °C⁻¹'],[17,'Cobre · 17 × 10⁻⁶ °C⁻¹']])+range('heat','Temperatura final',-20,120,20,1,'°C')+`<button data-constrain aria-pressed="false">Impedir expansão</button>`;break;
 case 'bimetal':controls=select('alphaA','Metal A',[[12,'Aço · α = 12'],[17,'Cobre · α = 17'],[23,'Alumínio · α = 23']])+select('alphaB','Metal B',[[23,'Alumínio · α = 23'],[17,'Cobre · α = 17'],[12,'Aço · α = 12']])+range('heat','Temperatura final',-20,140,80,1,'°C');break;
 case 'dimensions':controls=`<div class="dimension-buttons">${['Linear','Superficial','Volumétrica'].map((t,i)=>`<button data-dim="${i+1}" aria-pressed="${(saved.dim||1)===i+1}">${t}</button>`).join('')}</div>`+range('heat','Variação de temperatura',0,100,40,1,'°C');break;
 case 'liquid':controls=range('heat','Aquecimento do conjunto',0,50,10,1,'°C')+`<button data-outline aria-pressed="false">Comparar contorno inicial</button>`;break;
 case 'volume':controls=range('heat','Variação de temperatura',0,30,10,1,'°C')+`<div class="dimension-buttons">${[['real','Real'],['apparent','Aparente'],['container','Recipiente']].map(([v,t])=>`<button data-part="${v}" aria-pressed="${(saved.part||'real')===v}">${t}</button>`).join('')}</div>`;break;
 case 'water':controls=range('temp','Temperatura da água',0,10,0,.1,'°C')+`<button data-peak>Encontrar 4 °C</button>`;break;
 }
 host.innerHTML=`<div class="diagram ${type==='particles'?'particle-stage':''}"></div><div class="lab-controls">${controls}</div><div class="lab-results" role="status" aria-live="polite" aria-atomic="true"></div>`;
 const diagram=$('.diagram',host),results=$('.lab-results',host);
 if(type==='particles')diagram.innerHTML='<canvas width="1200" height="680" role="img" aria-label="Rede de partículas vibrando em torno das posições de equilíbrio; amplitude e distância média respondem à temperatura"></canvas><span class="thermal-badge"></span>';
 $$('input,select',host).forEach(i=>{if(saved[i.id]!==undefined)i.value=saved[i.id];i.oninput=()=>{saved[i.id]=i.value;if(type==='particles'){if(i.id==='unit')updateUnit();else{saved.k=+i.value+(saved.unit==='K'?0:273.15);saved.extreme=false;saved.zero=saved.k<=.00001;}if(i.id!=='unit')updateTemperature();}if(type==='buoyancy'){saved.released=false;saved.motion=0;}update();};});
 const v=id=>+$('#'+id,host).value;
 function values(){const x={};$$('input,select',host).forEach(i=>{if(i.id!=='unit')x[i.id]=+i.value;});x.stroke=saved.stroke||0;x.motion=saved.motion||0;return x;}
 function updateUnit(){saved.unit=$('#unit',host).value;updateTemperature();}
 function updateTemperature(){const i=$('#temperature',host),k=saved.k??293.15,kelvin=(saved.unit||'C')==='K';i.min=kelvin?0:-273.15;i.max=kelvin?600:326.85;i.value=kelvin?k:k-273.15;i.dataset.unit=kelvin?'K':'°C';}
 if(type==='particles'){saved.k??=293.15;saved.unit??='C';saved.paused=false;updateTemperature();}
 function displayControls(){ $$('input',host).forEach(i=>{const precision=type==='particles'?2:Number(i.step)<1?1:0;const label=$(`[data-value="${i.id}"]`,host);label.textContent=fmt(+i.value,precision)+' '+i.dataset.unit;i.setAttribute('aria-valuetext',label.textContent);}); }
 function update(instant=false){displayControls();const target=values();if(type==='particles'){renderParticleStatus();if(!raf)raf=requestAnimationFrame(loopParticles);return;}
 if(!Object.keys(current).length||instant||reduced()){current=target;draw(current,true);return;}const from={...current},start=performance.now();cancelAnimationFrame(raf);draw(target,true,false);const animate=now=>{if(!el.isConnected){raf=0;return;}const t=clamp((now-start)/500,0,1),ease=1-(1-t)**3;for(const k in target)current[k]=from[k]+(target[k]-from[k])*ease;draw(current,false);if(t<1)raf=requestAnimationFrame(animate);else{raf=0;draw(target,true);}};raf=requestAnimationFrame(animate); }
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-mark'))saved.mark={depth:v('depth'),fluid:v('fluid'),pressure:v('fluid')*10*v('depth')/1000};
 if(b.hasAttribute('data-clear-mark'))delete saved.mark;
 if(b.hasAttribute('data-density')){$('#mass',host).value=b.dataset.density;saved.mass=b.dataset.density;$('#volume',host).value=1000;saved.volume=1000;}
 if(b.hasAttribute('data-pressure')){const presets={wide:[800,200],narrow:[800,20],knife:[300,10]},[f,a]=presets[b.dataset.pressure];$('#force',host).value=f;saved.force=f;$('#area',host).value=a;saved.area=a;current.force=0;}
 if(b.hasAttribute('data-replay')){current.force=0;}
 if(b.hasAttribute('data-ratio')){$('#ratio',host).value=b.dataset.ratio;saved.ratio=b.dataset.ratio;}
 if(b.hasAttribute('data-pascal-predict')){saved.pascalPrediction=b.dataset.pascalPredict;$$('[data-pascal-predict]',host).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const out=$('.pascal-prediction',host);out.textContent=b.dataset.pascalPredict==='greater'?'Boa hipótese. Agora use a propagação e os controles para explicar por que a força aumenta.':b.dataset.pascalPredict==='same'?'A pressão transmitida é a mesma, mas força e pressão não são a mesma grandeza. Teste uma área de saída maior.':'Observe que a mesma pressão atua numa área maior. Teste o cenário e compare com sua hipótese.';}
 if(b.hasAttribute('data-stroke')){saved.stroke=saved.stroke?0:1;if(saved.propagation)saved.pulse=Date.now();b.textContent=saved.stroke?'Recolher êmbolos':'Acionar prensa';}
 if(b.hasAttribute('data-propagation')){saved.propagation=!saved.propagation;saved.pulse=false;b.setAttribute('aria-pressed',String(saved.propagation));b.textContent=saved.propagation?'Pressão pronta · agora acione':'Mostrar a pressão se espalhando';}
 if(b.hasAttribute('data-buoyancy')){$('#bodydensity',host).value=b.dataset.buoyancy;saved.bodydensity=b.dataset.buoyancy;$('#submerged',host).value=100;saved.submerged=100;saved.released=false;saved.motion=0;}
 if(b.hasAttribute('data-release')){saved.released=!saved.released;saved.motion=saved.released?1:0;b.textContent=saved.released?'Reposicionar bloco':'Soltar o bloco';}
 if(b.hasAttribute('data-dim'))saved.dim=+b.dataset.dim;
 if(b.hasAttribute('data-outline')){saved.outline=!saved.outline;b.setAttribute('aria-pressed',saved.outline);}
 if(b.hasAttribute('data-part'))saved.part=b.dataset.part;
 if(b.hasAttribute('data-peak')){$('#temp',host).value=4;saved.temp=4;}
 if(b.hasAttribute('data-constrain')){saved.constrained=!saved.constrained;b.setAttribute('aria-pressed',saved.constrained);b.textContent=saved.constrained?'Liberar expansão':'Impedir expansão';}
 if(b.hasAttribute('data-zero-c')){saved.k=273.15;saved.zero=false;saved.extreme=false;updateTemperature();}
 if(b.hasAttribute('data-zero-k')){saved.k=0;saved.zero=true;saved.extreme=false;updateTemperature();}
 if(b.hasAttribute('data-extreme')){saved.extreme=!saved.extreme;saved.zero=false;}
 if(b.hasAttribute('data-pause')){saved.paused=!saved.paused;b.textContent=saved.paused?'Retomar movimento':'Pausar movimento';b.setAttribute('aria-pressed',saved.paused);}
 update();});
 function draw(x,announce=false,paint=true){let b=grid(),r='';switch(type){
 case 'depth':{const h=x.depth,rho=x.fluid,ph=rho*10*h/1000,pa=100+ph,y=60+h*17,scale=Math.cbrt(100/pa),radius=32*scale,force=clamp(ph/3,8,46);b+=rect(35,60,280,220,'url(#water-shade)')+line(35,60,315,60,C.blue,2)+line(35,280,315,280,C.blue,2);for(let i=0;i<=10;i+=2)b+=line(35,60+i*17,45,60+i*17,C.blue)+text(49,65+i*17,i+' m',C.blue,12);b+=`<path d="M175 30V${y-radius-5}" stroke="#b5cbd5" stroke-dasharray="3 4"/>`+`<circle cx="175" cy="${y}" r="${radius+4}" fill="#82c8e529" stroke="${C.cream}"/><circle cx="175" cy="${y}" r="${radius}" fill="#FBF9E730"/>`;
 for(const a of [0,Math.PI/2,Math.PI,Math.PI*1.5]){const q=radius+10; b+=arrow(175+Math.cos(a)*(q+force),y+Math.sin(a)*(q+force),175+Math.cos(a)*q,y+Math.sin(a)*q,C.gold,2);}if(saved.mark){const my=60+saved.mark.depth*17;b+=line(35,my,315,my,C.green,2,'stroke-dasharray="5 5"')+text(305,my-7,'leitura marcada',C.green,12,'end');}
 const gaugeMax=rho>2000?1500:150;const angle=-Math.PI*.8+Math.min(ph/gaugeMax,1)*Math.PI*1.6;b+=`<circle cx="440" cy="135" r="68" fill="#ffffff04" stroke="#82c8e540" stroke-width="8"/>`;for(let i=0;i<=10;i++){const a=-Math.PI*.8+i/10*Math.PI*1.6;b+=line(440+Math.sin(a)*53,135-Math.cos(a)*53,440+Math.sin(a)*61,135-Math.cos(a)*61,C.blue,1);}b+=arrow(440,135,440+Math.sin(angle)*49,135-Math.cos(angle)*49,C.gold,3)+`<circle cx="440" cy="135" r="4" fill="${C.cream}"/>`+text(440,35,'MANÔMETRO',C.blue,13,'middle')+text(440,231,fmt(ph)+' kPa',C.gold,25,'middle')+text(440,255,'escala: 0 a '+fmt(gaugeMax,0)+' kPa',C.cream,12,'middle')+text(175,316,'Cápsula flexível de gás',C.cream,13,'middle');const delta=saved.mark?ph-saved.mark.pressure:null;r=stats(['Hidrostática',`${fmt(ph)} kPa`],['Absoluta',`${fmt(pa)} kPa`],['Variação desde a marca',delta===null?'—':`${delta>=0?'+':''}${fmt(delta)} kPa`],['Volume do gás',`${fmt(100/pa*100)}%`])+chain(`ρ = ${fmt(rho,0)} kg/m³`,`h = ${fmt(h)} m`,`pₕ = ρgh = ${fmt(ph)} kPa`,`pₐᵦₛ = ${fmt(pa)} kPa`)+status(`A pressão comprime a cápsula igualmente em todas as direções. V/V₀ = p₀/p = ${fmt(100/pa,3)} (gás ideal, temperatura constante). Marque uma leitura e altere apenas profundidade ou líquido para comparar. Setas e deformação ampliadas; g = 10 m/s².`);break;}
 case 'density':{const m=x.mass,vol=x.volume,rho=m/vol,w=80+Math.cbrt(vol/2000)*95,h=w*.8,area=w*h,cols=Math.max(3,Math.floor(w/14)),dots=Math.round(m/25),rows=Math.ceil(dots/cols),spY=Math.min(12,(h-12)/Math.max(rows,1));b+=rect(45,160-h,w,h,'#82c8e51a',`stroke="${C.blue}"`);for(let i=0;i<dots;i++)b+=`<circle cx="${53+(i%cols)*(w-16)/Math.max(cols-1,1)}" cy="${152-Math.floor(i/cols)*spY}" r="2.1" fill="${C.gold}"/>`;b+=rect(28,174,205,12,C.dim)+line(130,187,130,220,C.cream,3)+rect(62,220,136,37,'#ffffff08',`stroke="${C.dim}"`)+text(130,246,fmt(m,0)+' g',C.gold,22,'middle')+text(130,292,fmt(vol,0)+' cm³',C.cream,16,'middle');
 const by=rho<=1?145-(1-rho)*72:195;b+=rect(320,145,235,133,'url(#water-shade)')+line(320,145,555,145,C.blue,2)+rect(399,by,72,72,C.gold,'rx="3"')+text(440,90,'Na água',C.blue,16,'middle')+text(440,318,rho<1?'Flutua':Math.abs(rho-1)<.0001?'Equilíbrio imerso':'Afunda',C.cream,18,'middle');const behavior=rho<1?'flutua':Math.abs(rho-1)<.0001?'equilíbrio imerso':'afunda';r=stats(['Massa',`${fmt(m,0)} g`],['Volume',`${fmt(vol,0)} cm³`],['Densidade média',`${fmt(rho,2)} g/cm³`],['Comparação com a água',`${fmt(rho,2)} ×`])+chain(`${fmt(m,0)} g ÷ ${fmt(vol,0)} cm³`,`ρ = ${fmt(rho,2)} g/cm³`,rho<1?'ρcorpo < ρágua':rho>1?'ρcorpo > ρágua':'ρcorpo = ρágua',behavior)+status(`Faça uma previsão antes de escolher um cenário. Massa e volume são independentes: mudar apenas uma delas altera a densidade média. Cada ponto representa 25 g, não um átomo. ${rho<1?`${fmt(rho*100,0)}% do volume ficaria submerso em equilíbrio.`:rho>1?'O peso excede o empuxo máximo e o corpo afunda.':'Igualando as densidades, o corpo pode permanecer totalmente imerso.'}`);break;}
 case 'pressure':{const f=x.force,a=x.area,pressure=f/a*10,load=pressure/150,broken=load>1,def=clamp(load*25,0,30),w=30+a*.9,cy=185+def;b+=rect(85,218,18,78,C.dim)+rect(496,218,18,78,C.dim);if(broken){b+=`<path d="M75 192L267 219L281 246M315 246L330 219L525 192" stroke="${C.gold}" stroke-width="11" fill="none"/><path d="M279 214l16 14 -10 15 18 19" stroke="${C.cream}" fill="none"/>`;}else b+=`<path d="M75 192Q300 ${192+def*2} 525 192" stroke="${C.blue}" stroke-width="11" fill="none"/>`;b+=rect(300-w/2,cy-28,w,25,C.gold)+arrow(300,45,300,cy-40,C.gold,2+f/300)+text(330,92,fmt(f,0)+' N',C.gold,18)+line(300-w/2,cy+32,300+w/2,cy+32,C.cream)+text(300,cy+56,fmt(a,0)+' cm²',C.cream,16,'middle')+text(45,32,broken?'LIMITE ILUSTRATIVO EXCEDIDO':'DISTRIBUIÇÃO DO CARREGAMENTO',C.blue,13);const analogy=a>=150?'Como a chapa do pedreiro sobre as telhas':a<=15?'Como o fio de uma faca':a<=30?'Como um apoio estreito':'Área de contato intermediária';r=stats(['Força',`${fmt(f,0)} N`],['Área',`${fmt(a,0)} cm²`],['Pressão média',`${fmt(pressure)} kPa`],['Placa fictícia',broken?'Cedeu':'Deformação elástica'])+chain(`F = ${fmt(f,0)} N`,`A = ${fmt(a,0)} cm²`,`p = ${fmt(pressure)} kPa`,broken?'limite ilustrativo excedido':'carga distribuída')+status(`${analogy}. Limite ilustrativo: 150 kPa. ${broken?'A concentração de força acionou a ruptura desenhada.':'A deformação cresce com a pressão aplicada.'} A cena exagera o efeito e não prevê a resistência de uma mesa, telha ou lâmina real.`);break;}
 case 'pascal':{const ratio=x.ratio,f=x.force,d=x.stroke,ww=60+(ratio-1)*5.5,right=505-ww,leftY=125+d*44,rightY=125-d*44/ratio,pc={ink:'var(--ink)',accent:'var(--accent)',water:'var(--tone-3)'};const channelTop=244;b+=`<defs><linearGradient id="pascal-water" x2="0" y2="1"><stop stop-color="var(--tone-3)" stop-opacity=".55"/><stop offset="1" stop-color="var(--tone-1)" stop-opacity=".22"/></linearGradient></defs><path d="M70 70V284H505V70M130 70V244H${right}V70" fill="none" stroke="${pc.ink}" stroke-width="2"/>`;
 b+=rect(71,leftY,58,283-leftY,'url(#pascal-water)')+rect(129,245,right-128,38,'url(#pascal-water)')+rect(right,rightY,504-right,283-rightY,'url(#pascal-water)')+rect(64,leftY-10,72,10,pc.accent)+rect(right-6,rightY-10,ww+12,10,pc.accent)+line(100,leftY-10,100,leftY-42,pc.ink,6)+line(right+ww/2,rightY-10,right+ww/2,rightY-42,pc.ink,6)+rect(right-10,rightY-48,ww+20,8,pc.ink)+arrow(100,35,100,70,pc.accent,3)+arrow(right+ww/2,70,right+ww/2,35,pc.accent,3)+text(145,54,sub('F','1'),pc.accent,18)+text(right+ww/2+20,54,sub('F','2'),pc.accent,18)+text(100,319,'5 cm²',pc.ink,15,'middle')+text(right+ww/2,319,fmt(5*ratio,0)+' cm²',pc.ink,15,'middle');
 for(let i=0;i<4;i++)b+=arrow(180+i*48,264,202+i*48,264,pc.water,1.5);
 if(saved.propagation&&saved.pulse){const rx=right+ww/2,path=`M100 150 V264 H${rx} V${rightY+38}`;b+=`<path class="pressure-route" d="${path}" fill="none" stroke="${pc.accent}" stroke-width="2" stroke-dasharray="5 8" opacity=".22"/><g class="pressure-probe"><circle cx="0" cy="0" r="7" fill="${pc.accent}" opacity=".22"/>${arrow(0,-5,0,-28,pc.accent,2)}${arrow(0,5,0,28,pc.accent,2)}${arrow(-5,0,-28,0,pc.accent,2)}${arrow(5,0,28,0,pc.accent,2)}<animateMotion dur="${reduced()?'.01s':'2.8s'}" repeatCount="1" fill="freeze" path="${path}"/></g>`+text(145,120,'Δp em todas as direções',pc.accent,14);}
 const dp=f/5*10;r=stats(['Aumento de pressão',`${fmt(dp)} kPa`],['Força de saída',`${fmt(f*ratio,0)} N`],['Percurso de saída',`${fmt(d*10/ratio,2)} cm`],['Volume deslocado',`${fmt(d*50,0)} cm³`])+chain(`F₁/A₁ = ${fmt(dp)} kPa`,'mesmo Δp no fluido',`F₂ = ${fmt(f*ratio,0)} N`,`d₂ = ${fmt(d*10/ratio,2)} cm`)+status(`Entrada: ${fmt(d*10,1)} cm. Saída: ${fmt(d*10/ratio,2)} cm. A₁d₁ = A₂d₂: ganhar força custa percurso, e o circuito permanece cheio em qualquer razão. Trabalho útil ideal: ${fmt(f*d*.1,2)} J. Áreas e movimentos visuais sem escala; desprezamos perdas e o pequeno desnível.`);break;}
 case 'buoyancy':{const rho=x.bodydensity,start=185-(1-x.submerged/100)*80,target=rho<1000?185-(1-rho/1000)*80:rho===1000?195:255,top=start+(target-start)*x.motion,frac=clamp((top+80-185)/80,0,1),P=rho*.002*10,E=20*frac,contact=top>=254.99,N=contact?Math.max(P-E,0):0,resultant=P-E-N,pc={ink:'var(--ink)',accent:'var(--accent)',water:'var(--tone-3)',support:'var(--tone-1)'};b+=`<defs><linearGradient id="buoy-water" x2="0" y2="1"><stop stop-color="var(--tone-3)" stop-opacity=".58"/><stop offset="1" stop-color="var(--tone-1)" stop-opacity=".22"/></linearGradient></defs>`+rect(55,185,365,150,'url(#buoy-water)')+line(55,185,420,185,pc.water,2)+line(55,336,420,336,pc.ink,2)+rect(180,top,80,80,pc.accent,'rx="3"')+arrow(208,top+40,208,top+40+P*1.25,pc.ink,3)+arrow(233,top+40,233,top+40-E*1.25,pc.water,3)+text(470,100,'FORÇAS',pc.ink,13)+arrow(457,125,457,170,pc.ink,3)+text(473,153,'P',pc.ink,20)+arrow(457,230,457,185,pc.water,3)+text(473,214,'E',pc.water,20);if(contact)b+=arrow(275,315,275,280,pc.support,2)+text(285,305,'N',pc.support,17);b+=text(75,40,'Corpo de 2 L · água a 1.000 kg/m³',pc.ink,14);r=stats(['Peso',`${fmt(P)} N`],['Empuxo',`${fmt(E)} N`],['Resultante vertical',`${fmt(Math.abs(resultant))} N ${resultant>0?'↓':resultant<0?'↑':'—'}`],['Volume submerso',`${fmt(frac*2,2)} L`])+chain(`ρ do corpo: ${fmt(rho,0)} kg/m³`,`P = ${fmt(P)} N · E = ${fmt(E)} N`,resultant>0?'resultante para baixo':resultant<0?'resultante para cima':'forças equilibradas',contact?'apoio completa o equilíbrio':rho<1000?'flutuação':rho===1000?'equilíbrio imerso':'afundamento')+status(contact?`O bloco chegou ao fundo: P = E + N, com N = ${fmt(N)} N, supondo água sob o corpo e apoio pontual.`:saved.released?rho<1000?'O bloco sobe até reduzir o volume mergulhado e alcançar E = P.':rho===1000?'Com densidades iguais, peso e empuxo se equilibram quando o corpo está totalmente imerso.':'O peso supera o maior empuxo possível e o corpo afunda.':`O bloco está mantido na posição inicial. Compare as setas, faça uma previsão e só então clique em “Soltar o bloco”.`);break;}
 case 'bar':{const dt=x.heat-20,alpha=x.material,dl=2*alpha*1e-6*dt,constrained=!!saved.constrained;b+=text(35,30,constrained?'EXPANSÃO IMPEDIDA':'COMPARAÇÃO NA MESMA TEMPERATURA',C.blue,13);[[12,'Aço'],[17,'Cobre'],[23,'Alumínio']].forEach(([a,name],i)=>{const y=80+i*63,free=310+2*a*1e-6*dt*14000,ww=constrained?310:free;b+=rect(55,y,ww,22,a===alpha?'url(#metal-shade)':'#82C8E52a',`rx="3" stroke="${a===alpha?C.gold:C.dim}"`)+text(575,y+17,name,a===alpha?C.gold:C.blue,14,'end');if(constrained){b+=line(45,y-8,45,y+35,C.green,5)+line(375,y-8,375,y+35,C.green,5)+arrow(45,y+11,64,y+11,C.green,2)+arrow(375,y+11,356,y+11,C.green,2);}});b+=line(365,52,365,262,C.cream,1,'stroke-dasharray="4 5"')+line(55,269,365,269,C.cream)+text(210,292,sub('L','0')+' = 2 m',C.cream,15,'middle')+text(35,328,constrained?'O apoio impede ΔL e produz esforço interno':'Alongamentos ampliados × 90 na direção horizontal',C.blue,12);r=stats(['Dilatação livre calculada',`${fmt(dl*1000,2)} mm`],['Comprimento mostrado',constrained?'2,00000 m':`${fmt(2+dl,5)} m`],['Condição',constrained?'Impedida':'Livre'])+chain(`ΔT = ${fmt(dt,0)} °C`,`α = ${alpha} × 10⁻⁶ °C⁻¹`,`ΔL livre = ${fmt(dl*1000,2)} mm`,constrained?'restrição → esforço interno':'barra muda de comprimento')+status(`${constrained?'A barra tentaria variar o comprimento, mas os apoios impedem o deslocamento; surge esforço interno. Não calculamos a tensão porque o módulo elástico e as condições do apoio não foram fornecidos.':'As três barras têm 2 m a 20 °C. O material selecionado está destacado; compare os comprimentos sem mudar a temperatura.'} Coeficientes aproximados e constantes neste intervalo.`);break;}
 case 'bimetal':{const a=x.alphaA,beta=x.alphaB,dt=x.heat-20,diff=(a-beta)*dt,bend=clamp(diff*.055,-105,105),midY=175-bend,endY=175-bend*.35;const upper=`M90 170 Q300 ${midY-8} 510 ${endY-8}`,lower=`M90 186 Q300 ${midY+8} 510 ${endY+8}`;b+=text(30,30,'LÂMINA BIMETÁLICA · CURVATURA AMPLIADA',C.blue,13)+`<path d="${upper}" fill="none" stroke="${C.gold}" stroke-width="14"/><path d="${lower}" fill="none" stroke="${C.blue}" stroke-width="14"/>`+text(68,167,'A',C.gold,18,'middle')+text(68,194,'B',C.blue,18,'middle')+line(90,135,90,220,C.cream,5)+text(300,302,dt===0?'Sem variação de temperatura':bend>0?'Curva para B, que varia menos':'Curva para A, que varia menos',C.cream,17,'middle');const larger=a===beta?'iguais':a>beta?'A':'B',inside=a===beta?'nenhum':dt>=0?(a>beta?'B':'A'):(a>beta?'A':'B');r=stats(['ΔT',`${fmt(dt,0)} °C`],['α<sub>A</sub>',`${fmt(a,0)} × 10⁻⁶ °C⁻¹`],['α<sub>B</sub>',`${fmt(beta,0)} × 10⁻⁶ °C⁻¹`],['Lado interno',inside])+chain(`comparar α<sub>A</sub> e α<sub>B</sub>`,a===beta?'coeficientes iguais':`${larger} tentaria variar mais`,dt===0?'sem diferença de comprimento':dt>0?'aquecimento':'resfriamento',a===beta||dt===0?'lâmina reta':`curva para ${inside}`)+status(`${a===beta?'Como os coeficientes são iguais, não aparece curvatura neste modelo.':dt===0?'A 20 °C, usamos a lâmina reta como referência.':`O metal ${larger} teria a maior variação livre. Como as tiras estão unidas, a lâmina se curva para ${inside}.`} A curvatura visual foi muito ampliada; o modelo considera união perfeita, temperatura uniforme e pequenas deformações.`);break;}
 case 'dimensions':{const d=saved.dim||1,k=1+x.heat*.0015,eps=23e-6*x.heat;$$('[data-dim]',host).forEach(b=>b.setAttribute('aria-pressed',+b.dataset.dim===d));const center=`translate(${300*(1-k)},${170*(1-k)}) scale(${k})`;let geom=d===1?rect(130,162,340,16,C.gold):d===2?`<path d="M210 85H390V255H210Z M325 170a25 25 0 1 0 -50 0a25 25 0 1 0 50 0" fill="${C.blue}" fill-rule="evenodd"/>`:`<path d="M220 105l80 -42 80 42 -80 42z" fill="${C.cream}"/><path d="M220 105v125l80 42V147z" fill="${C.blue}"/><path d="M300 147v125l80 -42V105z" fill="${C.gold}"/>`;b+=`<g transform="${center}">${geom}</g><g opacity=".6" fill="none" stroke="${C.cream}" stroke-dasharray="4 5">${d===1?'<rect x="130" y="162" width="340" height="16"/>':d===2?'<rect x="210" y="85" width="180" height="170"/><circle cx="300" cy="170" r="25"/>':'<path d="M220 105l80 -42 80 42v125l-80 42 -80 -42zM220 105l80 42 80 -42M300 147v125"/>'}</g>`+text(30,30,'CONTORNO TRACEJADO: ESTADO INICIAL',C.blue,13)+text(300,325,d===2?'O furo cresce junto com a placa.':'Uma expansão em '+d+(d===1?' dimensão.':' dimensões.'),C.cream,14,'middle');r=stats(['Variação relativa aproximada',`${fmt(d*eps*100,3)}%`],['Coeficiente',d===1?'α':d===2?'β ≈ 2α':'γ ≈ 3α'])+status('Exemplo: alumínio, α = 23 × 10⁻⁶ °C⁻¹. O efeito visual é ampliado; o valor numérico usa pequenas dilatações. O volume relativo cresce aproximadamente três vezes mais que o comprimento relativo.');break;}
 case 'liquid':{const dt=x.heat,real=.9*dt,rec=.3*dt,ap=.6*dt,growth=dt*.6,overflow=dt>0;b+=text(115,35,'INICIAL',C.blue,13,'middle')+text(335,35,'AQUECIDO',C.blue,13,'middle')+rect(57,93,116,187,'url(#water-shade)')+`<path d="M55 82V282H175V82M${275-growth*.3} ${82-growth}V282H${395+growth*.3}V${82-growth}" fill="none" stroke="${C.cream}" stroke-width="2"/>`+rect(277-growth*.3,93-growth,116+growth*.6,187+growth,'url(#water-shade)');if(saved.outline)b+=`<path d="M275 82V282H395V82" stroke="${C.gold}" fill="none" stroke-dasharray="4 4"/>`;
 if(overflow){b+=`<path d="M${395+growth*.3} ${93-growth}Q438 ${70-growth} 452 239" stroke="${C.blue}" stroke-width="${1+dt/20}" fill="none"/><circle class="flow-drop" cx="449" cy="205" r="3" fill="${C.blue}"/>`;}
 b+=`<path d="M431 244V298H534V244" fill="none" stroke="${C.cream}"/>`+rect(433,296-ap*1.1,99,ap*1.1,'#82c8e565')+text(115,315,'1.000 mL',C.cream,16,'middle')+text(335,315,fmt(1000+rec,1)+' mL de capacidade',C.cream,13,'middle')+text(485,330,fmt(ap,1)+' mL',C.gold,17,'middle');r=stats(['Expansão real',`${fmt(real)} mL`],['Capacidade extra',`${fmt(rec)} mL`],['Transbordamento',`${fmt(ap)} mL`])+status('Recipiente inicialmente cheio até a borda. Parte da expansão cabe no recipiente aquecido; o excesso vai para o coletor. Escalas de volume e expansão visual ampliadas. Sem evaporação ou mudança de fase.');break;}
 case 'volume':{const dt=x.heat,real=.9*dt,rec=.3*dt,ap=.6*dt,part=saved.part||'real';$$('[data-part]',host).forEach(b=>b.setAttribute('aria-pressed',b.dataset.part===part));b+=text(40,35,'BALANÇO DE VOLUMES',C.blue,13);const max=dt*14;b+=rect(50,75,max,52,C.gold,`opacity="${part==='real'?1:.35}"`)+rect(50,178,max*2/3,52,C.blue,`opacity="${part==='container'?.2:1}"`)+rect(50+max*2/3,178,max/3,52,C.green,`opacity="${part==='apparent'?.2:.65}"`)+text(50,61,'Real: '+fmt(real)+' mL',C.gold,17)+text(50,265,'Aparente: '+fmt(ap)+' mL',C.blue,16)+text(320,265,'Recipiente: '+fmt(rec)+' mL',C.green,15)+text(50,319,fmt(real)+' = '+fmt(ap)+' + '+fmt(rec)+' mL',C.cream,25);r=status({real:'Real: todo o aumento de volume do líquido, independentemente de onde ele fica.',apparent:'Aparente: parte que excede a capacidade adicional; transborda se o recipiente já estava cheio.',container:'Recipiente: volume extra que passa a caber por causa da expansão da capacidade interna.'}[part]);break;}
 case 'water':{const t=x.temp,density=T=>999.842594+.06793952*T-.00909529*T*T+.0001001685*T**3-.000001120083*T**4+.000000006536332*T**5;const rho=density(t),Y=T=>245-(density(T)-999.68)*430;let path='';for(let i=0;i<=10.01;i+=.1)path+=`${i===0?'M':'L'}${55+i*31},${Y(i)} `;b+=line(50,40,50,255,C.dim)+line(50,255,370,255,C.dim)+`<path d="${path}" fill="none" stroke="${C.blue}" stroke-width="3"/>`+line(179,Y(4),179,255,C.gold,1,'stroke-dasharray="4 4"')+`<circle cx="${55+t*31}" cy="${Y(t)}" r="6" fill="${C.gold}"/>`+text(45,282,'0',C.cream,14)+text(175,282,'4',C.cream,14)+text(340,282,'10 °C',C.cream,14)+text(52,28,'Densidade (kg/m³)',C.blue,14)+text(20,90,'1.000',C.cream,10)+text(20,245,'999,7',C.cream,10);const h=110+(1000/rho-1)*180000;b+=rect(427,260-h,95,h,'url(#water-shade)',`stroke="${C.blue}"`)+line(415,150,535,150,C.gold,1,'stroke-dasharray="3 4"')+text(475,300,'Mesma massa',C.cream,14,'middle');r=stats(['Densidade aproximada',`${fmt(rho,3)} kg/m³`],['Volume de 1 kg',`${fmt(1000000/rho,3)} mL`])+status(`${t<3.98?'Ao aquecer nesta região, a água se contrai.':t<4.05?'Densidade próxima do máximo; volume próximo do mínimo.':'Acima do máximo de densidade, aquecer aumenta o volume.'} Curva aproximada para água pura à pressão atmosférica. A variação vertical do recipiente é muito ampliada para ser visível.`);break;}
 }
 if(paint)diagram.innerHTML=svg(b,'Modelo interativo: '+type);
 if(announce)results.innerHTML=r;
 }
 function renderParticleStatus(){const k=saved.k,zero=saved.zero,extra=saved.extreme,heat=clamp(k/600,0,1),amp=zero?0:2+Math.sqrt(heat)*9,spacing=42+heat*12,msg=$('.zero-message',host);msg.hidden=!(zero||extra);msg.innerHTML=extra?'<strong>∞ não é uma temperatura deste modelo.</strong><p>Antes de extrapolar sem limite, o sólido mudaria de fase e a aproximação deixaria de valer. O efeito visual é uma brincadeira, não um cálculo.</p>':`<strong>0 K: limite ideal, não atingido por este controle.</strong><p>A terceira lei da Termodinâmica impede alcançá-lo por um número finito de processos. No estado fundamental, sistemas quânticos ainda podem ter energia de ponto zero; isso não se reduz à frase “a partícula precisa se mover por causa de Heisenberg”.</p><a href="#historia/zero-absoluto/0" data-story="zero-absoluto">É possível chegar ao zero absoluto? Conheça a curiosidade.</a>`;$('.thermal-badge',host).textContent=extra?'FORA DO MODELO':zero?'LIMITE QUÂNTICO':'REDE CRISTALINA · MODELO';results.innerHTML=stats(['Escala Celsius',`${fmt(k-273.15,2)} °C`],['Escala Kelvin',`${fmt(k,2)} K`],['Amplitude visual',zero?'nuvem quântica':`${fmt(amp,1)} px`],['Espaçamento visual',`${fmt(spacing,1)} px`])+chain(`T = ${fmt(k,2)} K`,zero?'modelo clássico insuficiente':'agitação térmica aumenta',zero?'estado fundamental':'amplitude e espaçamento aumentam',extra?'aproximação deixa de valer':'rede continua ligada')+status(zero?'A nuvem representa a impossibilidade de descrever o estado fundamental como partículas clássicas imóveis. Ela não é uma trajetória medida.':'A amplitude de vibração e o afastamento médio respondem ao aquecimento. A rede permanece ligada; partículas não crescem. Em 0 °C ainda há agitação térmica.');}
 function loopParticles(now){raf=0;if(!el.isConnected)return;const canvas=$('canvas',host),ctx=canvas.getContext('2d'),k=saved.k||0,halt=reduced()||saved.paused;const dt=lastFrame?Math.min((now-lastFrame)/1000,.05):0;lastFrame=now;if(!halt)phase+=dt;ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,600,340);const heat=k/600,spacing=42+heat*12,amp=saved.extreme?25:2+Math.sqrt(heat)*9,pts=[];ctx.strokeStyle='#82c8e518';ctx.lineWidth=1;for(let j=0;j<6;j++)for(let i=0;i<9;i++){const index=j*9+i,bx=300+(i-4)*spacing,by=170+(j-2.5)*spacing,speed=1.5+heat*5;const dx=saved.zero?0:Math.sin(phase*speed+index*2.39)*amp,dy=saved.zero?0:Math.cos(phase*speed*1.17+index*1.31)*amp;pts.push({x:bx+dx,y:by+dy,bx,by});}for(let i=0;i<pts.length;i++){const q=pts[i];for(const offset of [1,9])if(pts[i+offset]&&(offset===9||i%9!==8)){ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(pts[i+offset].x,pts[i+offset].y);ctx.stroke();}}
 for(let i=0;i<pts.length;i++){const q=pts[i];if(saved.zero){const g=ctx.createRadialGradient(q.x,q.y,0,q.x,q.y,12);g.addColorStop(0,'#82c8e580');g.addColorStop(1,'#82c8e500');ctx.fillStyle=g;ctx.beginPath();ctx.arc(q.x,q.y,12,0,Math.PI*2);ctx.fill();}else{ctx.strokeStyle='#FDB81320';ctx.beginPath();ctx.ellipse(q.bx,q.by,amp+3,amp+3,0,0,Math.PI*2);ctx.stroke();}ctx.fillStyle=i%5===0?C.gold:C.blue;ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=saved.extreme?12:5;ctx.beginPath();ctx.arc(q.x,q.y,3.4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}
 if(saved.extreme){ctx.strokeStyle=C.gold;ctx.setLineDash([7,9]);ctx.strokeRect(20,20,560,300);ctx.setLineDash([]);}if(!halt)raf=requestAnimationFrame(loopParticles);
 }
 update(true);
}
return {mount};
})();






