/* Reconstrução de Hidrostática e biblioteca inicial de exercícios. */
(()=>{
const MM=window.MM,p=t=>`<p>${t}</p>`,h=(t,b)=>`<section><h2>${t}</h2>${b}</section>`,eq=t=>`<div class="equation">${t}</div>`,note=t=>`<aside class="callout">${t}</aside>`,lab=(id,title)=>`<div class="lab" data-lab="${id}"><div class="lab-head"><span>${title}</span><span>Explore</span></div><div class="lab-body"></div><div class="observation-bar"><span>Observação interativa</span>${MM.report('observação',title)}</div></div>`,page=(lead,body)=>`<div class="teacher-lesson"><p class="lesson-opening">${lead}</p>${body}</div>`,why=(from,current,to,text)=>({from,current,to,text});
const checklist=items=>`<div class="thinking-checklist" data-required-checklist><h3>Roteiro de pensamento</h3><p>Marque cada etapa depois de conferi-la.</p>${items.map((x,i)=>`<label><input type="checkbox" value="${i}"><span class="organic-check"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12.5 9.5 17 19 7"></path></svg></span><span>${x}</span></label>`).join('')}<p class="checklist-status" role="status"></p></div>`;
const hydro=MM.lessons.find(x=>x.id==='hidrostatica');
hydro.time='45–65 min'; hydro.desc='Densidade, pressão, atmosfera, lei de Stevin e leitura crítica de resultados.';
hydro.slides=[
{label:'Linha de raciocínio',title:'O caminho desta aula',subtitle:'Da matéria que ocupa espaço até a pressão dentro de um líquido.',reason:why('Massa e volume','Pressão','Stevin e referências','O mapa mostra por que cada página existe e quais pegadinhas ela prepara.'),html:page('Vamos construir a Hidrostática como uma conversa. Primeiro descrevemos o material; depois vemos como uma força se distribui; por fim, entramos no líquido e acompanhamos a pressão enquanto descemos.',h('O encadeamento',p('<strong>Densidade</strong> compara massa e volume. <strong>Pressão</strong> compara força e área. A <strong>lei de Stevin</strong> explica a variação de pressão entre dois níveis. Depois distinguimos pressão absoluta, atmosférica e manométrica.')+note('A amostra usa quatro armadilhas com frequência: divisão invertida, área de contato, altura vertical e referência da pressão.')))},
{label:'Fluidos em repouso',title:'O que a Hidrostática estuda',subtitle:'Repouso não significa ausência de forças.',reason:why('Situação','Equilíbrio','Escolher o modelo','Antes de calcular, precisamos saber se as relações desta aula se aplicam.'),html:page('Hidrostática é o estudo dos fluidos em equilíbrio. Um líquido parado continua sob ação da gravidade e de forças de pressão. Ele permanece em repouso porque essas ações se equilibram.',h('Comece pelas fronteiras',p('A superfície está aberta ao ar? Há um êmbolo? Existe outro líquido? Essa informação determina a pressão de partida. Nesta aula, tratamos líquidos como homogêneos e praticamente incompressíveis, uma boa aproximação para muitos problemas escolares.')))},
{label:'Densidade',title:'Densidade',subtitle:'Quanta massa existe em cada porção de volume.',reason:why('Massa e volume','ρ = m/V','Comparar materiais','Densidade aparece diretamente e dentro da lei de Stevin.'),html:`<div class="split"><div class="copy">${p('Imagine dois blocos do mesmo tamanho: um de madeira e outro de alumínio. Eles ocupam volumes parecidos, mas o alumínio tem mais massa. Dizemos que ele é mais denso.')}${eq('ρ = <span class="fraction"><span>m</span><span>V</span></span>')}${p('Uma peça grande pode ter baixa densidade média se for oca. Portanto, densidade não é sinônimo de peso nem de tamanho.')}${note('Mantendo o volume, mais massa significa maior densidade. Mantendo a massa, mais volume significa menor densidade.')}</div>${lab('density','Massa, volume e densidade')}</div>`},
{label:'Medindo densidade',title:'Como medir e interpretar a densidade',subtitle:'A conta só termina quando o número ganha significado.',reason:why('Medidas','Unidades','Resultado crítico','As questões cobram conversão e comparação, não somente divisão.'),html:page('Uma balança fornece a massa. O volume pode vir das dimensões ou do deslocamento de água numa proveta.',h('Exemplo',p('Uma peça tem 540 g e ocupa 200 cm³. Sua densidade é 540/200 = 2,7 g/cm³, ou 2.700 kg/m³.')+p('A água tem densidade próxima de 1 g/cm³. Portanto, a peça tem densidade 2,7 vezes maior que a da água. Essa comparação ajuda a perceber se a potência de dez faz sentido.')))},
{label:'Pressão',title:'Pressão e área de contato',subtitle:'A força pode ser a mesma e produzir efeitos muito diferentes.',reason:why('Força perpendicular','p = F/A','Interpretar o efeito','Pneus, fundações e objetos cortantes aparecem várias vezes na amostra.'),html:`<div class="split"><div class="copy">${p('Um pedreiro que precisa passar sobre telhas pode usar uma tábua larga. O peso não desaparece: ele se distribui por uma área maior e reduz a pressão média em cada região.')}${p('Uma faca faz o contrário. Sua borda estreita concentra a força e aumenta a pressão.')}${eq('p = <span class="fraction"><span>F<sub>⊥</sub></span><span>A</span></span>')}${p('No SI, 1 pascal corresponde a 1 newton por metro quadrado.')}</div>${lab('pressure','Força, área e pressão')}</div>`},
{label:'Pressão no líquido',title:'Como um líquido exerce pressão',subtitle:'A força chega perpendicularmente a cada superfície.',reason:why('Pressão','Peso da coluna','Profundidade','Esta etapa prepara a explicação física da lei de Stevin.'),html:page('Dentro de um líquido parado, a pressão atua em todas as direções. Uma região profunda precisa sustentar o líquido que está acima dela; por isso a pressão aumenta quando descemos.',h('A forma engana',p('Um recipiente pode ser largo, estreito ou inclinado. Para comparar pressões, o que importa é o desnível vertical. É por isso que barragens precisam ser mais robustas perto da base.')))},
{label:'Atmosfera',title:'Pressão atmosférica',subtitle:'O ar também empurra.',reason:why('Atmosfera','Diferença de pressão','Canudos e garrafas','A amostra usa situações cotidianas para testar a ação do ar.'),html:page('Ao beber com um canudo, você reduz a pressão dentro da boca. A atmosfera que atua sobre a bebida ajuda a empurrar o líquido para cima.',h('Dois canudos',p('Se um segundo canudo fica aberto ao ar, fica difícil reduzir a pressão da boca: o ar entra livremente. Sem diferença de pressão suficiente, o suco não sobe como antes.'))+h('Garrafa tampada',p('Quando água sai de uma garrafa rígida fechada, a pressão interna diminui e o escoamento é dificultado. Ao abrir a tampa, o ar entra e mantém a superfície próxima da pressão atmosférica.')))},
{label:'Lei de Stevin',title:'Pressão hidrostática',subtitle:'Mais fundo significa maior pressão.',reason:why('Peso da coluna','Δp = ρgΔh','Escolher a altura','A altura correta é uma das decisões mais recorrentes nas questões.'),html:`<div class="split"><div class="copy">${p('Ao descer num mesmo líquido em repouso, a pressão aumenta. O aumento depende da densidade, da gravidade e do desnível vertical.')}${eq('Δp = ρgΔh')}${note('Use a altura vertical. O comprimento inclinado do tubo e o caminho percorrido pela água não substituem Δh.')}${p('Pontos na mesma altura, no mesmo líquido conectado e em repouso, possuem a mesma pressão.')}</div>${lab('depth','Profundidade, densidade e pressão')}</div>`},
{label:'Vasos comunicantes',title:'Mesmo nível, mesma pressão',subtitle:'Uma regra simples resolve desenhos complicados.',reason:why('Stevin','Comparar níveis','Vasos e manômetros','O formato costuma funcionar como distração visual.'),html:page('Em vasos comunicantes com o mesmo líquido e superfícies abertas à mesma atmosfera, o líquido tende a atingir o mesmo nível.',h('Líquidos diferentes',p('Escolha uma linha horizontal numa região conectada e iguale as pressões. Um líquido menos denso costuma precisar de uma coluna mais alta para produzir a mesma variação de pressão.')))},
{label:'Pressão absoluta',title:'Pressão absoluta e manométrica',subtitle:'Toda pressão usa uma referência.',reason:why('Atmosfera + líquido','Nomear a referência','Evitar a soma errada','A amostra alterna pressão total e variação de pressão.'),html:page('Num tanque aberto, a superfície já está sob pressão atmosférica. A coluna de líquido acrescenta ρgh.',eq('p<sub>abs</sub> = p<sub>atm</sub> + ρgh')+p('Se ρgh vale 50 kPa e a atmosfera foi adotada como 100 kPa, a pressão manométrica é 50 kPa e a absoluta é 150 kPa. São respostas para perguntas diferentes.')+note('Circule no enunciado: absoluta, atmosférica, manométrica ou diferença.'))},
{label:'Método de resolução',title:'Como resolver problemas de Hidrostática',subtitle:'Percorra o fluido a partir de uma pressão conhecida.',reason:why('Dados e desenho','Percurso vertical','Resposta com referência','O roteiro reúne as decisões que mais se repetem na amostra.'),html:page('Comece num ponto conhecido. Ao descer num líquido, some ρgΔh; ao subir, subtraia. Quando mudar de líquido, mude também a densidade.',checklist(['Marquei os pontos e a diferença vertical.','Identifiquei a densidade de cada fluido.','Registrei a pressão no ponto inicial.','Defini se a resposta é absoluta, manométrica ou uma diferença.','Converti Pa e kPa corretamente.','Comparei a ordem de grandeza com uma situação conhecida.']))},
{label:'Exercício de densidade',title:'Exercício guiado: densidade',subtitle:'Calcule e interprete.',reason:why('m e V','ρ','Comparação','O resultado precisa dizer algo sobre o material.'),html:page('Uma peça tem massa de 780 g e volume de 300 cm³.',eq('ρ = 780/300 = 2,6 g/cm³ = 2.600 kg/m³')+p('O valor é 2,6 vezes a densidade da água. Isso torna o resultado plausível para um material denso, mas não identifica sozinho a substância.')+`<a class="primary" href="#exercicios">Praticar densidade</a>${MM.report('questão','Exercício guiado de densidade')}`)},
{label:'Exercício de Stevin',title:'Exercício guiado: pressão no mergulho',subtitle:'Separe aumento e pressão absoluta.',reason:why('Profundidade','ρgh','Atmosfera + coluna','Mergulho aparece na amostra como aplicação direta de Stevin.'),html:page('Um mergulhador está 12 m abaixo da superfície. Adote ρ = 1.000 kg/m³, g = 10 m/s² e p<sub>atm</sub> = 100 kPa.',eq('ρgh = 120 kPa')+p('Esse é o aumento causado pela água. A pressão absoluta vale 100 + 120 = 220 kPa, cerca de 2,2 atmosferas no modelo usado.')+`<a class="primary" href="#exercicios">Praticar pressão e Stevin</a>${MM.report('questão','Exercício guiado de Stevin')}`)},
{label:'Síntese',title:'O que você precisa levar desta aula',subtitle:'Cinco ideias organizam a introdução à Hidrostática.',reason:why('Conceitos','Relações','Exercícios','A síntese prepara a prática.'),html:page('Densidade compara massa e volume. Pressão compara força perpendicular e área. A atmosfera participa dos fenômenos cotidianos. Stevin usa o desnível vertical. Pressão absoluta inclui a referência da superfície.',h('Pegadinhas observadas',p('A amostra insiste em quatro decisões: usar área ao quadrado em mudanças de escala, escolher a altura vertical, não confundir pressão com volume e reconhecer quando a atmosfera deve ser incluída.')+`<div class="next-study"><a class="primary" href="#exercicios">Fazer exercícios</a><a class="secondary" href="#aula/pascal-arquimedes/0">Continuar para Pascal e Arquimedes</a></div>`))}
];

const raw=[
['h01','Hidrostática','Pressão','Aplicação','Fácil','Pneus mais largos mantêm o peso do trator. O que ocorre com a pressão média no solo?',['Aumenta','Diminui','Não muda','Zera'],1,'A área aumenta e p = F/A diminui.'],
['h02','Hidrostática','Stevin','Cálculo','Médio','Uma coluna de água de 8 m, com ρ = 1.000 kg/m³ e g = 10 m/s², produz qual pressão manométrica?',['8 kPa','80 kPa','100 kPa','180 kPa'],1,'ρgh = 80.000 Pa = 80 kPa.'],
['h03','Hidrostática','Pressão absoluta','Cálculo','Médio','Se a coluna anterior está aberta a uma atmosfera de 100 kPa, qual pressão absoluta há na base?',['20 kPa','80 kPa','100 kPa','180 kPa'],3,'100 kPa + 80 kPa = 180 kPa.'],
['h04','Hidrostática','Densidade','Interpretação','Fácil','Um corpo tem densidade relativa 0,7. O que isso informa?',['Sua densidade é 0,7 vez a da água','Sua massa é 0,7 kg','Seu volume é 0,7 m³','Sua pressão é 0,7 Pa'],0,'Densidade relativa é uma razão entre densidades.'],
['h05','Hidrostática','Atmosfera','Interpretação','Médio','Por que um segundo canudo aberto ao ar dificulta beber o líquido?',['Aumenta a densidade','Dificulta reduzir a pressão na boca','Dobra o peso','Elimina a atmosfera'],1,'O ar entra e reduz a diferença de pressão que elevaria o líquido.'],
['h06','Hidrostática','Stevin','Aplicação','Médio','A pressão de uma ducha ligada a uma caixa depende principalmente de qual medida?',['Comprimento do cano','Desnível vertical entre superfície e ducha','Altura do telhado','Volume da caixa'],1,'Stevin depende do desnível vertical.'],
['h07','Hidrostática','Escala','Comparação','Difícil','Um modelo do mesmo material tem dimensões 10 vezes menores. Como muda a pressão sobre sua base?',['10 vezes menor','100 vezes menor','Igual','10 vezes maior'],0,'Massa varia com L³ e área com L²; a pressão varia com L.'],
['h08','Hidrostática','Recipientes','Interpretação','Médio','Dois recipientes têm o mesmo líquido, altura e área da base, mas formatos diferentes. As pressões no fundo são:',['Maior onde há mais volume','Iguais','Maior no estreito','Nulas'],1,'Com p₀, ρ e h iguais, as pressões são iguais.'],
['d01','Dilatação','Coeficientes','Conversão','Médio','Uma questão fornece α e pede dilatação volumétrica de um sólido isotrópico. Qual coeficiente usar?',['α','2α','3α','α/3'],2,'Para pequenas dilatações, γ ≈ 3α.'],
['d02','Dilatação','Volume','Cálculo','Médio','Um cubo de 400 cm³ aumenta 0,6 cm³ em 100 °C. Qual é γ?',['1,5×10⁻⁵','5×10⁻⁶','1,5×10⁻³','6×10⁻¹'],0,'γ = 0,6/(400×100) = 1,5×10⁻⁵ °C⁻¹.'],
['d03','Dilatação','Cabos','Aplicação','Fácil','Por que cabos de transmissão são instalados com curvatura?',['Para reduzir densidade','Para acomodar contração no frio','Para aumentar corrente','Para impedir vento'],1,'A folga acomoda mudanças térmicas de comprimento.'],
['d04','Dilatação','Bimetal','Comparação','Médio','A tem α maior que B. Ao aquecer as lâminas unidas, o conjunto se curva para qual lado?',['A','B','Nenhum','Depende só da massa'],1,'A fica no lado externo; a curvatura ocorre para B, de menor α.'],
['d05','Dilatação','Encaixes','Aplicação','Médio','Dois copos estão presos. Qual estratégia ajuda a separá-los?',['Aquecer o interno','Resfriar o interno e aquecer o externo','Aquecer ambos','Resfriar ambos'],1,'O interno contrai e o externo dilata.'],
['d06','Dilatação','Trilhos','Interpretação','Fácil','Por que trilhos precisam de folgas adequadas?',['Aumentar massa','Acomodar variações térmicas','Eliminar gravidade','Zerar α'],1,'Sem folga, surgem tensões e deformações.'],
['d07','Dilatação','Líquidos','Comparação','Médio','Três líquidos têm V₀ e ΔT iguais. C apresenta maior ΔV. O que concluímos?',['C tem menor γ','C tem maior γ','γ é igual','C não tem massa'],1,'Em ΔV = V₀γΔT, só γ diferencia os casos.'],
['d08','Dilatação','Aparente','Cálculo','Difícil','V₀=1.000 mL, γlíq=8×10⁻⁴, γrec=2×10⁻⁴ e ΔT=20 °C. Quanto transborda?',['4 mL','12 mL','16 mL','20 mL'],1,'1.000(8−2)×10⁻⁴×20 = 12 mL.'],
['d09','Dilatação','Água','Interpretação','Médio','Por que água próxima de 4 °C tende a ficar no fundo de um lago?',['Tem densidade máxima','Congela primeiro','Perde massa','A atmosfera zera'],0,'A água tem densidade máxima perto de 4 °C.'],
['d10','Dilatação','Escalas','Conversão','Difícil','α=3,6×10⁻⁶ °C⁻¹. Aproximadamente quanto vale em °F⁻¹?',['2,0×10⁻⁶','3,6×10⁻⁶','6,5×10⁻⁶','18×10⁻⁶'],0,'Divida por 1,8: 2,0×10⁻⁶ °F⁻¹.']];
const bank=raw.map(([id,subject,topic,skill,difficulty,q,options,correct,explanation])=>({id,subject,topic,skill,difficulty,q,options,correct,explanation})); MM.exerciseBank=bank;
MM.exercisePage=()=>`<section class="section-wrap catalog-page patterns-page exercise-library"><p class="eyebrow">Exercícios</p><h1>Pratique e reconheça os padrões</h1><p class="intro">${bank.length} questões didaticamente adaptadas da amostra. A ordem muda a cada abertura; os filtros montam sessões por assunto, raciocínio e dificuldade.</p><div class="sample-summary"><article><strong>32</strong><span>questões analisadas</span></article><article><strong>10</strong><span>de Hidrostática</span></article><article><strong>22</strong><span>de dilatação</span></article><article><strong>${bank.length}</strong><span>questões funcionais</span></article></div><form class="exercise-bank-filters"><div><label for="bank-subject">Assunto</label><select id="bank-subject"><option value="all">Todos</option><option>Hidrostática</option><option>Dilatação</option></select></div><div><label for="bank-skill">Raciocínio</label><select id="bank-skill"><option value="all">Todos</option>${[...new Set(bank.map(q=>q.skill))].map(x=>`<option>${x}</option>`).join('')}</select></div><div><label for="bank-difficulty">Dificuldade</label><select id="bank-difficulty"><option value="all">Todas</option><option>Fácil</option><option>Médio</option><option>Difícil</option></select></div><button type="reset">Limpar</button><p class="filter-result" role="status"></p></form><div class="exercise-bank"></div><section class="pattern-analysis"><p class="eyebrow">Análise da amostra</p><h2>Padrões que orientam as aulas</h2><div class="magnitude-grid"><article><span>Hidrostática</span><h3>Altura vertical</h3><p>Stevin aparece ligado ao desnível, à atmosfera e a situações cotidianas.</p></article><article><span>Pressão</span><h3>Área e escala</h3><p>Pneus, fundações e modelos reduzidos exigem relacionar força, área e volume.</p></article><article><span>Dilatação</span><h3>Coeficiente certo</h3><p>α, β e γ são alternados para testar a dimensão observada.</p></article></div><p class="method-note">As frequências descrevem apenas os dois arquivos recebidos; ainda não representam todo o ENEM ou outro vestibular.</p></section></section>`;
MM.initExercisePage=root=>{const host=root.querySelector('.exercise-bank'),form=root.querySelector('.exercise-bank-filters'),status=form.querySelector('.filter-result');let order=[...bank].sort(()=>Math.random()-.5);const draw=()=>{const s=form.querySelector('#bank-subject').value,k=form.querySelector('#bank-skill').value,d=form.querySelector('#bank-difficulty').value,list=order.filter(q=>(s==='all'||q.subject===s)&&(k==='all'||q.skill===k)&&(d==='all'||q.difficulty===d));status.textContent=`${list.length} ${list.length===1?'questão disponível':'questões disponíveis'}`;host.innerHTML=list.map((q,n)=>`<article class="bank-question" data-id="${q.id}"><header><span>${String(n+1).padStart(2,'0')}</span><div><small>${q.subject} · ${q.topic}</small><h2>${q.q}</h2></div></header><p class="question-meta">Questão adaptada da amostra · ${q.skill} · ${q.difficulty}</p><fieldset><legend class="sr-only">Alternativas</legend>${q.options.map((o,i)=>`<label class="answer"><input type="radio" name="${q.id}" value="${i}"><span>${String.fromCharCode(65+i)}) ${o}</span></label>`).join('')}</fieldset><div class="quiz-actions"><button class="primary" data-check>Verificar</button><button data-hint>Mostrar pista</button></div><p class="bank-hint" hidden>Antes da fórmula, diga qual grandeza deve aumentar ou diminuir.</p><div class="bank-feedback" role="status"></div>${MM.report('questão',q.id)}</article>`).join('')||'<p class="empty-filter">Nenhuma questão combina os filtros.</p>';};form.onchange=draw;form.onreset=()=>setTimeout(draw);host.onclick=e=>{const card=e.target.closest('.bank-question');if(!card)return;const q=bank.find(x=>x.id===card.dataset.id);if(e.target.matches('[data-hint]'))card.querySelector('.bank-hint').hidden=false;if(e.target.matches('[data-check]')){const a=card.querySelector('input:checked'),out=card.querySelector('.bank-feedback');out.innerHTML=!a?'Escolha uma alternativa.':`<strong>${+a.value===q.correct?'Resposta correta.':'Ainda não.'}</strong> ${q.explanation}<aside class="sense-check"><p class="eyebrow">Esse resultado faz sentido?</p><p>Compare o sentido e a ordem de grandeza antes de seguir.</p><a href="#grandezas">Ver comparações</a></aside>`;}};draw();};
})();
